// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.getPinnedStories#5821a5dc peer:InputPeer offset_id:int limit:int = stories.Stories`
  @TLObject(id: 0x5821a5dc, returning: TL.Stories.Stories.self)
  public struct GetPinnedStories: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var offsetId: Int32
    public var limit: Int32
  }
}
