// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.updateAlbum#5e5259b6 flags:# peer:InputPeer album_id:int title:flags.0?string delete_stories:flags.1?Vector<int> add_stories:flags.2?Vector<int> order:flags.3?Vector<int> = StoryAlbum`
  @TLObject(id: 0x5e5259b6, returning: TL.StoryAlbum.self)
  @TLFlagsEquatable
  public struct UpdateAlbum: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var albumId: Int32
    @TLConditional("flags", bit: 0) public var title: String? = nil
    @TLConditional("flags", bit: 1) public var deleteStories: [Int32]? = nil
    @TLConditional("flags", bit: 2) public var addStories: [Int32]? = nil
    @TLConditional("flags", bit: 3) public var order: [Int32]? = nil
  }
}
