// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.getPeerStories#2c4ada50 peer:InputPeer = stories.PeerStories`
  @TLObject(id: 0x2c4ada50, returning: TL.Stories.PeerStories.self)
  public struct GetPeerStories: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
