// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.readStories#a556dac8 peer:InputPeer max_id:int = Vector<int>`
  @TLObject(id: 0xa556dac8, returning: [Int32].self)
  public struct ReadStories: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var maxId: Int32
  }
}
