// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.sendStory#8f9e6898 flags:# pinned:flags.2?true noforwards:flags.4?true fwd_modified:flags.7?true peer:InputPeer media:InputMedia media_areas:flags.5?Vector<MediaArea> caption:flags.0?string entities:flags.1?Vector<MessageEntity> privacy_rules:Vector<InputPrivacyRule> random_id:long period:flags.3?int fwd_from_id:flags.6?InputPeer fwd_from_story:flags.6?int albums:flags.8?Vector<int> music:flags.9?InputDocument = Updates`
  @TLObject(id: 0x8f9e6898, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct SendStory: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var pinned: Bool = false
    @TLConditional("flags", bit: 4) public var noforwards: Bool = false
    @TLConditional("flags", bit: 7) public var fwdModified: Bool = false
    public var peer: TL.InputPeerType
    public var media: TL.InputMediaType
    @TLConditional("flags", bit: 5) public var mediaAreas: [TL.MediaAreaType]? = nil
    @TLConditional("flags", bit: 0) public var caption: String? = nil
    @TLConditional("flags", bit: 1) public var entities: [TL.MessageEntityType]? = nil
    public var privacyRules: [TL.InputPrivacyRuleType]
    public var randomId: Int64
    @TLConditional("flags", bit: 3) public var period: Int32? = nil
    @TLConditional("flags", bit: 6) public var fwdFromId: TL.InputPeerType? = nil
    @TLConditional("flags", bit: 6) public var fwdFromStory: Int32? = nil
    @TLConditional("flags", bit: 8) public var albums: [Int32]? = nil
    @TLConditional("flags", bit: 9) public var music: TL.InputDocumentType? = nil
  }
}
