// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.reorderAlbums#8535fbd9 peer:InputPeer order:Vector<int> = Bool`
  @TLObject(id: 0x8535fbd9, returning: Bool.self)
  public struct ReorderAlbums: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var order: [Int32]
  }
}
