// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.createAlbum#a36396e5 peer:InputPeer title:string stories:Vector<int> = StoryAlbum`
  @TLObject(id: 0xa36396e5, returning: TL.StoryAlbum.self)
  public struct CreateAlbum: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var title: String
    public var stories: [Int32]
  }
}
