// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.getAlbums#25b3eac7 peer:InputPeer hash:long = stories.Albums`
  @TLObject(id: 0x25b3eac7, returning: TL.Stories.AlbumsType.self)
  public struct GetAlbums: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var hash: Int64
  }
}
