// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.editStory#2c63a72b flags:# peer:InputPeer id:int media:flags.0?InputMedia media_areas:flags.3?Vector<MediaArea> caption:flags.1?string entities:flags.1?Vector<MessageEntity> privacy_rules:flags.2?Vector<InputPrivacyRule> music:flags.4?InputDocument = Updates`
  @TLObject(id: 0x2c63a72b, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct EditStory: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var id: Int32
    @TLConditional("flags", bit: 0) public var media: TL.InputMediaType? = nil
    @TLConditional("flags", bit: 3) public var mediaAreas: [TL.MediaAreaType]? = nil
    @TLConditional("flags", bit: 1) public var caption: String? = nil
    @TLConditional("flags", bit: 1) public var entities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 2) public var privacyRules: [TL.InputPrivacyRuleType]? = nil
    @TLConditional("flags", bit: 4) public var music: TL.InputDocumentType? = nil
  }
}
