// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.togglePinned#9a75a1ef peer:InputPeer id:Vector<int> pinned:Bool = Vector<int>`
  @TLObject(id: 0x9a75a1ef, returning: [Int32].self)
  public struct TogglePinned: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var id: [Int32]
    public var pinned: Bool
  }
}
