// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stickers {

  /// TL: `stickers.checkShortName#284b3639 short_name:string = Bool`
  @TLObject(id: 0x284b3639, returning: Bool.self)
  public struct CheckShortName: Equatable, Sendable {
    public var shortName: String
  }
}
