// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stats {

  /// TL: `stats.getMessagePublicForwards#5f150144 channel:InputChannel msg_id:int offset:string limit:int = stats.PublicForwards`
  @TLObject(id: 0x5f150144, returning: TL.Stats.PublicForwards.self)
  public struct GetMessagePublicForwards: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var msgId: Int32
    public var offset: String
    public var limit: Int32
  }
}
