// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stats {

  /// TL: `stats.getMessageStats#b6e0a3f5 flags:# dark:flags.0?true channel:InputChannel msg_id:int = stats.MessageStats`
  @TLObject(id: 0xb6e0a3f5, returning: TL.Stats.MessageStats.self)
  @TLFlagsEquatable
  public struct GetMessageStats: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var dark: Bool = false
    public var channel: TL.InputChannelType
    public var msgId: Int32
  }
}
