// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stats {

  /// TL: `stats.loadAsyncGraph#621d5fa0 flags:# token:string x:flags.0?long = StatsGraph`
  @TLObject(id: 0x621d5fa0, returning: TL.StatsGraphType.self)
  @TLFlagsEquatable
  public struct LoadAsyncGraph: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var token: String
    @TLConditional("flags", bit: 0) public var x: Int64? = nil
  }
}
