// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Upload {

  /// TL: `upload.saveFilePart#b304a621 file_id:long file_part:int bytes:bytes = Bool`
  @TLObject(id: 0xb304a621, returning: Bool.self)
  public struct SaveFilePart: Equatable, Sendable {
    public var fileId: Int64
    public var filePart: Int32
    public var bytes: Data
  }
}
