// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Langpack {

  /// TL: `langpack.getDifference#cd984aa5 lang_pack:string lang_code:string from_version:int = LangPackDifference`
  @TLObject(id: 0xcd984aa5, returning: TL.LangPackDifference.self)
  public struct GetDifference: Equatable, Sendable {
    public var langPack: String
    public var langCode: String
    public var fromVersion: Int32
  }
}
