// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Langpack {

  /// TL: `langpack.getLanguage#6a596502 lang_pack:string lang_code:string = LangPackLanguage`
  @TLObject(id: 0x6a596502, returning: TL.LangPackLanguage.self)
  public struct GetLanguage: Equatable, Sendable {
    public var langPack: String
    public var langCode: String
  }
}
