// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.getDeepLinkInfo#3fedc75f path:string = help.DeepLinkInfo`
  @TLObject(id: 0x3fedc75f, returning: TL.Help.DeepLinkInfoType.self)
  public struct GetDeepLinkInfo: Equatable, Sendable {
    public var path: String
  }
}
