// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.getAppConfig#61e3f854 hash:int = help.AppConfig`
  @TLObject(id: 0x61e3f854, returning: TL.Help.AppConfigType.self)
  public struct GetAppConfig: Equatable, Sendable {
    public var hash: Int32
  }
}
