// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.getAppUpdate#522d5a7d source:string = help.AppUpdate`
  @TLObject(id: 0x522d5a7d, returning: TL.Help.AppUpdateType.self)
  public struct GetAppUpdate: Equatable, Sendable {
    public var source: String
  }
}
