// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.acceptTermsOfService#ee72f79a id:DataJSON = Bool`
  @TLObject(id: 0xee72f79a, returning: Bool.self)
  public struct AcceptTermsOfService: Equatable, Sendable {
    public var id: TL.DataJSON
  }
}
