// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.getSupportName#d360e72c = help.SupportName`
  @TLObject(id: 0xd360e72c, returning: TL.Help.SupportName.self)
  public struct GetSupportName: Equatable, Sendable {
  }
}
