// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.hidePromoData#1e251c95 peer:InputPeer = Bool`
  @TLObject(id: 0x1e251c95, returning: Bool.self)
  public struct HidePromoData: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
