// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.cancelCode#1f040578 phone_number:string phone_code_hash:string = Bool`
  @TLObject(id: 0x1f040578, returning: Bool.self)
  public struct CancelCode: Equatable, Sendable {
    public var phoneNumber: String
    public var phoneCodeHash: String
  }
}
