// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.requestPasswordRecovery#d897bc66 = auth.PasswordRecovery`
  @TLObject(id: 0xd897bc66, returning: TL.Auth.PasswordRecovery.self)
  public struct RequestPasswordRecovery: Equatable, Sendable {
  }
}
