// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.resetLoginEmail#7e960193 phone_number:string phone_code_hash:string = auth.SentCode`
  @TLObject(id: 0x7e960193, returning: TL.Auth.SentCodeType.self)
  public struct ResetLoginEmail: Equatable, Sendable {
    public var phoneNumber: String
    public var phoneCodeHash: String
  }
}
