// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.reportMissingCode#cb9deff6 phone_number:string phone_code_hash:string mnc:string = Bool`
  @TLObject(id: 0xcb9deff6, returning: Bool.self)
  public struct ReportMissingCode: Equatable, Sendable {
    public var phoneNumber: String
    public var phoneCodeHash: String
    public var mnc: String
  }
}
