// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.checkPaidAuth#56e59f9c phone_number:string phone_code_hash:string form_id:long = auth.SentCode`
  @TLObject(id: 0x56e59f9c, returning: TL.Auth.SentCodeType.self)
  public struct CheckPaidAuth: Equatable, Sendable {
    public var phoneNumber: String
    public var phoneCodeHash: String
    public var formId: Int64
  }
}
