// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.signUp#aac7b717 flags:# no_joined_notifications:flags.0?true phone_number:string phone_code_hash:string first_name:string last_name:string = auth.Authorization`
  @TLObject(id: 0xaac7b717, returning: TL.Auth.AuthorizationType.self)
  @TLFlagsEquatable
  public struct SignUp: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var noJoinedNotifications: Bool = false
    public var phoneNumber: String
    public var phoneCodeHash: String
    public var firstName: String
    public var lastName: String
  }
}
