// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsFragment
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `fragment.*` methods.
  public var fragment: FragmentMethods {
    FragmentMethods(client: self)
  }
  /// The `fragment.*` methods of a `TLClient`.
  public struct FragmentMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `fragment.getCollectibleInfo#be1e85ba collectible:InputCollectible = fragment.CollectibleInfo`
    public func getCollectibleInfo(collectible: TL.InputCollectibleType) async throws -> TL.Fragment.CollectibleInfo {
      try await client.invoke(TL.Fragment.GetCollectibleInfo(collectible: collectible))
    }
  }
}
