// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.tmpPassword#db64fd34 tmp_password:bytes valid_until:int = account.TmpPassword`
  @TLObject(id: 0xdb64fd34)
  public struct TmpPassword: Equatable, Sendable {
    public var tmpPassword: Data
    public var validUntil: Int32
  }
}
