// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.authorizationForm#ad2e1cd8 flags:# required_types:Vector<SecureRequiredType> values:Vector<SecureValue> errors:Vector<SecureValueError> users:Vector<User> privacy_policy_url:flags.0?string = account.AuthorizationForm`
  @TLObject(id: 0xad2e1cd8)
  @TLFlagsEquatable
  public struct AuthorizationForm: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var requiredTypes: [TL.SecureRequiredTypeType]
    public var values: [TL.SecureValue]
    public var errors: [TL.SecureValueErrorType]
    public var users: [TL.UserType]
    @TLConditional("flags", bit: 0) public var privacyPolicyUrl: String? = nil
  }
}
