// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `accountDaysTTL#b8d0afdf days:int = AccountDaysTTL`
  @TLObject(id: 0xb8d0afdf)
  public struct AccountDaysTTL: Equatable, Sendable {
    public var days: Int32
  }
}
