// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.passwordInputSettings#c23727c9 flags:# new_algo:flags.0?PasswordKdfAlgo new_password_hash:flags.0?bytes hint:flags.0?string email:flags.1?string new_secure_settings:flags.2?SecureSecretSettings = account.PasswordInputSettings`
  @TLObject(id: 0xc23727c9)
  @TLFlagsEquatable
  public struct PasswordInputSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var newAlgo: TL.PasswordKdfAlgoType? = nil
    @TLConditional("flags", bit: 0) public var newPasswordHash: Data? = nil
    @TLConditional("flags", bit: 0) public var hint: String? = nil
    @TLConditional("flags", bit: 1) public var email: String? = nil
    @TLConditional("flags", bit: 2) public var newSecureSettings: TL.SecureSecretSettings? = nil
  }
}
