// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.autoSaveSettings#4c3e069d users_settings:AutoSaveSettings chats_settings:AutoSaveSettings broadcasts_settings:AutoSaveSettings exceptions:Vector<AutoSaveException> chats:Vector<Chat> users:Vector<User> = account.AutoSaveSettings`
  @TLObject(id: 0x4c3e069d)
  public struct AutoSaveSettings: Equatable, Sendable {
    public var usersSettings: TL.AutoSaveSettings
    public var chatsSettings: TL.AutoSaveSettings
    public var broadcastsSettings: TL.AutoSaveSettings
    public var exceptions: [TL.AutoSaveException]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
