// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// The TL type `account.SavedRingtone` (2 constructors).
  @TLType
  public indirect enum SavedRingtoneType: Equatable, Sendable {
    /// `account.savedRingtone#b7263f6d = account.SavedRingtone`
    case savedRingtone(TL.Account.SavedRingtone)
    /// `account.savedRingtoneConverted#1f307eb7 document:Document = account.SavedRingtone`
    case savedRingtoneConverted(TL.Account.SavedRingtoneConverted)
  }

  /// TL: `account.savedRingtone#b7263f6d = account.SavedRingtone`
  @TLObject(id: 0xb7263f6d)
  public struct SavedRingtone: Equatable, Sendable {
  }

  /// TL: `account.savedRingtoneConverted#1f307eb7 document:Document = account.SavedRingtone`
  @TLObject(id: 0x1f307eb7)
  public struct SavedRingtoneConverted: Equatable, Sendable {
    public var document: TL.DocumentType
  }
}
