// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.connectedBots#17d7f87b connected_bots:Vector<ConnectedBot> users:Vector<User> = account.ConnectedBots`
  @TLObject(id: 0x17d7f87b)
  public struct ConnectedBots: Equatable, Sendable {
    public var connectedBots: [TL.ConnectedBot]
    public var users: [TL.UserType]
  }
}
