// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.passkeyRegistrationOptions#e16b5ce1 options:DataJSON = account.PasskeyRegistrationOptions`
  @TLObject(id: 0xe16b5ce1)
  public struct PasskeyRegistrationOptions: Equatable, Sendable {
    public var options: TL.DataJSON
  }
}
