// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.takeout#4dba4501 id:long = account.Takeout`
  @TLObject(id: 0x4dba4501)
  public struct Takeout: Equatable, Sendable {
    public var id: Int64
  }
}
