// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// The TL type `account.SavedRingtones` (2 constructors).
  @TLType
  public indirect enum SavedRingtonesType: Equatable, Sendable {
    /// `account.savedRingtonesNotModified#fbf6e8b1 = account.SavedRingtones`
    case savedRingtonesNotModified(TL.Account.SavedRingtonesNotModified)
    /// `account.savedRingtones#c1e92cc5 hash:long ringtones:Vector<Document> = account.SavedRingtones`
    case savedRingtones(TL.Account.SavedRingtones)
  }

  /// TL: `account.savedRingtonesNotModified#fbf6e8b1 = account.SavedRingtones`
  @TLObject(id: 0xfbf6e8b1)
  public struct SavedRingtonesNotModified: Equatable, Sendable {
  }

  /// TL: `account.savedRingtones#c1e92cc5 hash:long ringtones:Vector<Document> = account.SavedRingtones`
  @TLObject(id: 0xc1e92cc5)
  public struct SavedRingtones: Equatable, Sendable {
    public var hash: Int64
    public var ringtones: [TL.DocumentType]
  }
}
