// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// The TL type `account.SavedMusicIds` (2 constructors).
  @TLType
  public indirect enum SavedMusicIdsType: Equatable, Sendable {
    /// `account.savedMusicIdsNotModified#4fc81d6e = account.SavedMusicIds`
    case savedMusicIdsNotModified(TL.Account.SavedMusicIdsNotModified)
    /// `account.savedMusicIds#998d6636 ids:Vector<long> = account.SavedMusicIds`
    case savedMusicIds(TL.Account.SavedMusicIds)
  }

  /// TL: `account.savedMusicIdsNotModified#4fc81d6e = account.SavedMusicIds`
  @TLObject(id: 0x4fc81d6e)
  public struct SavedMusicIdsNotModified: Equatable, Sendable {
  }

  /// TL: `account.savedMusicIds#998d6636 ids:Vector<long> = account.SavedMusicIds`
  @TLObject(id: 0x998d6636)
  public struct SavedMusicIds: Equatable, Sendable {
    public var ids: [Int64]
  }
}
