// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// The TL type `account.WebBrowserSettings` (2 constructors).
  @TLType
  public indirect enum WebBrowserSettingsType: Equatable, Sendable {
    /// `account.webBrowserSettingsNotModified#c31c8f4e = account.WebBrowserSettings`
    case webBrowserSettingsNotModified(TL.Account.WebBrowserSettingsNotModified)
    /// `account.webBrowserSettings#79eb8cb3 flags:# open_external_browser:flags.0?true display_close_button:flags.1?true external_exceptions:Vector<WebDomainException> inapp_exceptions:Vector<WebDomainException> hash:long = account.WebBrowserSettings`
    case webBrowserSettings(TL.Account.WebBrowserSettings)
  }

  /// TL: `account.webBrowserSettingsNotModified#c31c8f4e = account.WebBrowserSettings`
  @TLObject(id: 0xc31c8f4e)
  public struct WebBrowserSettingsNotModified: Equatable, Sendable {
  }

  /// TL: `account.webBrowserSettings#79eb8cb3 flags:# open_external_browser:flags.0?true display_close_button:flags.1?true external_exceptions:Vector<WebDomainException> inapp_exceptions:Vector<WebDomainException> hash:long = account.WebBrowserSettings`
  @TLObject(id: 0x79eb8cb3)
  @TLFlagsEquatable
  public struct WebBrowserSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var openExternalBrowser: Bool = false
    @TLConditional("flags", bit: 1) public var displayCloseButton: Bool = false
    public var externalExceptions: [TL.WebDomainException]
    public var inappExceptions: [TL.WebDomainException]
    public var hash: Int64
  }
}
