// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.businessChatLinks#ec43a2d1 links:Vector<BusinessChatLink> chats:Vector<Chat> users:Vector<User> = account.BusinessChatLinks`
  @TLObject(id: 0xec43a2d1)
  public struct BusinessChatLinks: Equatable, Sendable {
    public var links: [TL.BusinessChatLink]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
