// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// The TL type `account.EmojiStatuses` (2 constructors).
  @TLType
  public indirect enum EmojiStatusesType: Equatable, Sendable {
    /// `account.emojiStatusesNotModified#d08ce645 = account.EmojiStatuses`
    case emojiStatusesNotModified(TL.Account.EmojiStatusesNotModified)
    /// `account.emojiStatuses#90c467d1 hash:long statuses:Vector<EmojiStatus> = account.EmojiStatuses`
    case emojiStatuses(TL.Account.EmojiStatuses)
  }

  /// TL: `account.emojiStatusesNotModified#d08ce645 = account.EmojiStatuses`
  @TLObject(id: 0xd08ce645)
  public struct EmojiStatusesNotModified: Equatable, Sendable {
  }

  /// TL: `account.emojiStatuses#90c467d1 hash:long statuses:Vector<EmojiStatus> = account.EmojiStatuses`
  @TLObject(id: 0x90c467d1)
  public struct EmojiStatuses: Equatable, Sendable {
    public var hash: Int64
    public var statuses: [TL.EmojiStatusType]
  }
}
