// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `aiComposeToneExample#f1d628ec from:TextWithEntities to:TextWithEntities = AiComposeToneExample`
  @TLObject(id: 0xf1d628ec)
  public struct AiComposeToneExample: Equatable, Sendable {
    public var from: TL.TextWithEntities
    public var to: TL.TextWithEntities
  }
}
