// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `AttachMenuBots` (2 constructors).
  @TLType
  public indirect enum AttachMenuBotsType: Equatable, Sendable {
    /// `attachMenuBotsNotModified#f1d88a5c = AttachMenuBots`
    case attachMenuBotsNotModified(TL.AttachMenuBotsNotModified)
    /// `attachMenuBots#3c4301c0 hash:long bots:Vector<AttachMenuBot> users:Vector<User> = AttachMenuBots`
    case attachMenuBots(TL.AttachMenuBots)
  }

  /// TL: `attachMenuBotsNotModified#f1d88a5c = AttachMenuBots`
  @TLObject(id: 0xf1d88a5c)
  public struct AttachMenuBotsNotModified: Equatable, Sendable {
  }

  /// TL: `attachMenuBots#3c4301c0 hash:long bots:Vector<AttachMenuBot> users:Vector<User> = AttachMenuBots`
  @TLObject(id: 0x3c4301c0)
  public struct AttachMenuBots: Equatable, Sendable {
    public var hash: Int64
    public var bots: [TL.AttachMenuBot]
    public var users: [TL.UserType]
  }
}
