// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `attachMenuBotsBot#93bf667f bot:AttachMenuBot users:Vector<User> = AttachMenuBotsBot`
  @TLObject(id: 0x93bf667f)
  public struct AttachMenuBotsBot: Equatable, Sendable {
    public var bot: TL.AttachMenuBot
    public var users: [TL.UserType]
  }
}
