// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Auth {

  /// TL: `auth.firebasePnvIntent#df5ac00c nonce:string digital_credential_payload:string = auth.FirebasePnvIntent`
  @TLObject(id: 0xdf5ac00c)
  public struct FirebasePnvIntent: Equatable, Sendable {
    public var nonce: String
    public var digitalCredentialPayload: String
  }
}
