// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `autoDownloadSettings#baa57628 flags:# disabled:flags.0?true video_preload_large:flags.1?true audio_preload_next:flags.2?true phonecalls_less_data:flags.3?true stories_preload:flags.4?true photo_size_max:int video_size_max:long file_size_max:long video_upload_maxbitrate:int small_queue_active_operations_max:int large_queue_active_operations_max:int = AutoDownloadSettings`
  @TLObject(id: 0xbaa57628)
  @TLFlagsEquatable
  public struct AutoDownloadSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var disabled: Bool = false
    @TLConditional("flags", bit: 1) public var videoPreloadLarge: Bool = false
    @TLConditional("flags", bit: 2) public var audioPreloadNext: Bool = false
    @TLConditional("flags", bit: 3) public var phonecallsLessData: Bool = false
    @TLConditional("flags", bit: 4) public var storiesPreload: Bool = false
    public var photoSizeMax: Int32
    public var videoSizeMax: Int64
    public var fileSizeMax: Int64
    public var videoUploadMaxbitrate: Int32
    public var smallQueueActiveOperationsMax: Int32
    public var largeQueueActiveOperationsMax: Int32
  }
}
