// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `availableReaction#c077ec01 flags:# inactive:flags.0?true premium:flags.2?true reaction:string title:string static_icon:Document appear_animation:Document select_animation:Document activate_animation:Document effect_animation:Document around_animation:flags.1?Document center_icon:flags.1?Document = AvailableReaction`
  @TLObject(id: 0xc077ec01)
  @TLFlagsEquatable
  public struct AvailableReaction: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var inactive: Bool = false
    @TLConditional("flags", bit: 2) public var premium: Bool = false
    public var reaction: String
    public var title: String
    public var staticIcon: TL.DocumentType
    public var appearAnimation: TL.DocumentType
    public var selectAnimation: TL.DocumentType
    public var activateAnimation: TL.DocumentType
    public var effectAnimation: TL.DocumentType
    @TLConditional("flags", bit: 1) public var aroundAnimation: TL.DocumentType? = nil
    @TLConditional("flags", bit: 1) public var centerIcon: TL.DocumentType? = nil
  }
}
