// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `botAppSettings#c99b1950 flags:# placeholder_path:flags.0?bytes background_color:flags.1?int background_dark_color:flags.2?int header_color:flags.3?int header_dark_color:flags.4?int = BotAppSettings`
  @TLObject(id: 0xc99b1950)
  @TLFlagsEquatable
  public struct BotAppSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var placeholderPath: Data? = nil
    @TLConditional("flags", bit: 1) public var backgroundColor: Int32? = nil
    @TLConditional("flags", bit: 2) public var backgroundDarkColor: Int32? = nil
    @TLConditional("flags", bit: 3) public var headerColor: Int32? = nil
    @TLConditional("flags", bit: 4) public var headerDarkColor: Int32? = nil
  }
}
