// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `BotCommandScope` (7 constructors).
  @TLType
  public indirect enum BotCommandScopeType: Equatable, Sendable {
    /// `botCommandScopeDefault#2f6cb2ab = BotCommandScope`
    case botCommandScopeDefault(TL.BotCommandScopeDefault)
    /// `botCommandScopeUsers#3c4f04d8 = BotCommandScope`
    case botCommandScopeUsers(TL.BotCommandScopeUsers)
    /// `botCommandScopeChats#6fe1a881 = BotCommandScope`
    case botCommandScopeChats(TL.BotCommandScopeChats)
    /// `botCommandScopeChatAdmins#b9aa606a = BotCommandScope`
    case botCommandScopeChatAdmins(TL.BotCommandScopeChatAdmins)
    /// `botCommandScopePeer#db9d897d peer:InputPeer = BotCommandScope`
    case botCommandScopePeer(TL.BotCommandScopePeer)
    /// `botCommandScopePeerAdmins#3fd863d1 peer:InputPeer = BotCommandScope`
    case botCommandScopePeerAdmins(TL.BotCommandScopePeerAdmins)
    /// `botCommandScopePeerUser#0a1321f3 peer:InputPeer user_id:InputUser = BotCommandScope`
    case botCommandScopePeerUser(TL.BotCommandScopePeerUser)
  }

  /// TL: `botCommandScopeDefault#2f6cb2ab = BotCommandScope`
  @TLObject(id: 0x2f6cb2ab)
  public struct BotCommandScopeDefault: Equatable, Sendable {
  }

  /// TL: `botCommandScopeUsers#3c4f04d8 = BotCommandScope`
  @TLObject(id: 0x3c4f04d8)
  public struct BotCommandScopeUsers: Equatable, Sendable {
  }

  /// TL: `botCommandScopeChats#6fe1a881 = BotCommandScope`
  @TLObject(id: 0x6fe1a881)
  public struct BotCommandScopeChats: Equatable, Sendable {
  }

  /// TL: `botCommandScopeChatAdmins#b9aa606a = BotCommandScope`
  @TLObject(id: 0xb9aa606a)
  public struct BotCommandScopeChatAdmins: Equatable, Sendable {
  }

  /// TL: `botCommandScopePeer#db9d897d peer:InputPeer = BotCommandScope`
  @TLObject(id: 0xdb9d897d)
  public struct BotCommandScopePeer: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }

  /// TL: `botCommandScopePeerAdmins#3fd863d1 peer:InputPeer = BotCommandScope`
  @TLObject(id: 0x3fd863d1)
  public struct BotCommandScopePeerAdmins: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }

  /// TL: `botCommandScopePeerUser#0a1321f3 peer:InputPeer user_id:InputUser = BotCommandScope`
  @TLObject(id: 0x0a1321f3)
  public struct BotCommandScopePeerUser: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var userId: TL.InputUserType
  }
}
