// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `BotInlineResult` (2 constructors).
  @TLType
  public indirect enum BotInlineResultType: Equatable, Sendable {
    /// `botInlineResult#11965f3a flags:# id:string type:string title:flags.1?string description:flags.2?string url:flags.3?string thumb:flags.4?WebDocument content:flags.5?WebDocument send_message:BotInlineMessage = BotInlineResult`
    case botInlineResult(TL.BotInlineResult)
    /// `botInlineMediaResult#17db940b flags:# id:string type:string photo:flags.0?Photo document:flags.1?Document title:flags.2?string description:flags.3?string send_message:BotInlineMessage = BotInlineResult`
    case botInlineMediaResult(TL.BotInlineMediaResult)
  }

  /// TL: `botInlineResult#11965f3a flags:# id:string type:string title:flags.1?string description:flags.2?string url:flags.3?string thumb:flags.4?WebDocument content:flags.5?WebDocument send_message:BotInlineMessage = BotInlineResult`
  @TLObject(id: 0x11965f3a)
  @TLFlagsEquatable
  public struct BotInlineResult: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var id: String
    public var type: String
    @TLConditional("flags", bit: 1) public var title: String? = nil
    @TLConditional("flags", bit: 2) public var description: String? = nil
    @TLConditional("flags", bit: 3) public var url: String? = nil
    @TLConditional("flags", bit: 4) public var thumb: TL.WebDocumentType? = nil
    @TLConditional("flags", bit: 5) public var content: TL.WebDocumentType? = nil
    public var sendMessage: TL.BotInlineMessageType
  }

  /// TL: `botInlineMediaResult#17db940b flags:# id:string type:string photo:flags.0?Photo document:flags.1?Document title:flags.2?string description:flags.3?string send_message:BotInlineMessage = BotInlineResult`
  @TLObject(id: 0x17db940b)
  @TLFlagsEquatable
  public struct BotInlineMediaResult: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var id: String
    public var type: String
    @TLConditional("flags", bit: 0) public var photo: TL.PhotoType? = nil
    @TLConditional("flags", bit: 1) public var document: TL.DocumentType? = nil
    @TLConditional("flags", bit: 2) public var title: String? = nil
    @TLConditional("flags", bit: 3) public var description: String? = nil
    public var sendMessage: TL.BotInlineMessageType
  }
}
