// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.exportedBotToken#3c60b621 token:string = bots.ExportedBotToken`
  @TLObject(id: 0x3c60b621)
  public struct ExportedBotToken: Equatable, Sendable {
    public var token: String
  }
}
