// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `botVerifierSettings#b0cd6617 flags:# can_modify_custom_description:flags.1?true icon:long company:string custom_description:flags.0?string = BotVerifierSettings`
  @TLObject(id: 0xb0cd6617)
  @TLFlagsEquatable
  public struct BotVerifierSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var canModifyCustomDescription: Bool = false
    public var icon: Int64
    public var company: String
    @TLConditional("flags", bit: 0) public var customDescription: String? = nil
  }
}
