// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `businessAwayMessage#ef156a5c flags:# offline_only:flags.0?true shortcut_id:int schedule:BusinessAwayMessageSchedule recipients:BusinessRecipients = BusinessAwayMessage`
  @TLObject(id: 0xef156a5c)
  @TLFlagsEquatable
  public struct BusinessAwayMessage: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var offlineOnly: Bool = false
    public var shortcutId: Int32
    public var schedule: TL.BusinessAwayMessageScheduleType
    public var recipients: TL.BusinessRecipients
  }
}
