// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `businessGreetingMessage#e519abab shortcut_id:int recipients:BusinessRecipients no_activity_days:int = BusinessGreetingMessage`
  @TLObject(id: 0xe519abab)
  public struct BusinessGreetingMessage: Equatable, Sendable {
    public var shortcutId: Int32
    public var recipients: TL.BusinessRecipients
    public var noActivityDays: Int32
  }
}
