// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `businessChatLink#b4ae666f flags:# link:string message:string entities:flags.0?Vector<MessageEntity> title:flags.1?string views:int = BusinessChatLink`
  @TLObject(id: 0xb4ae666f)
  @TLFlagsEquatable
  public struct BusinessChatLink: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var link: String
    public var message: String
    @TLConditional("flags", bit: 0) public var entities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 1) public var title: String? = nil
    public var views: Int32
  }
}
