// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `ButtonType` (7 constructors).
  @TLType
  public indirect enum ButtonTypeType: Equatable, Sendable {
    /// `buttonTypeDefault#c9dd90e9 = ButtonType`
    case buttonTypeDefault(TL.ButtonTypeDefault)
    /// `buttonTypeRequestPhone#df3d36f9 = ButtonType`
    case buttonTypeRequestPhone(TL.ButtonTypeRequestPhone)
    /// `buttonTypeRequestGeoLocation#9beee140 = ButtonType`
    case buttonTypeRequestGeoLocation(TL.ButtonTypeRequestGeoLocation)
    /// `buttonTypeRequestPoll#aacfff84 flags:# quiz:flags.0?Bool = ButtonType`
    case buttonTypeRequestPoll(TL.ButtonTypeRequestPoll)
    /// `buttonTypeRequestPeer#4f58a237 flags:# button_id:int peer_type:RequestPeerType max_quantity:int = ButtonType`
    case buttonTypeRequestPeer(TL.ButtonTypeRequestPeer)
    /// `inputButtonTypeRequestPeer#3fe268fe flags:# name_requested:flags.0?true username_requested:flags.1?true photo_requested:flags.2?true button_id:int peer_type:RequestPeerType max_quantity:int = ButtonType`
    case inputButtonTypeRequestPeer(TL.InputButtonTypeRequestPeer)
    /// `buttonTypeSimpleWebView#c01a597a url:string = ButtonType`
    case buttonTypeSimpleWebView(TL.ButtonTypeSimpleWebView)
  }

  /// TL: `buttonTypeDefault#c9dd90e9 = ButtonType`
  @TLObject(id: 0xc9dd90e9)
  public struct ButtonTypeDefault: Equatable, Sendable {
  }

  /// TL: `buttonTypeRequestPhone#df3d36f9 = ButtonType`
  @TLObject(id: 0xdf3d36f9)
  public struct ButtonTypeRequestPhone: Equatable, Sendable {
  }

  /// TL: `buttonTypeRequestGeoLocation#9beee140 = ButtonType`
  @TLObject(id: 0x9beee140)
  public struct ButtonTypeRequestGeoLocation: Equatable, Sendable {
  }

  /// TL: `buttonTypeRequestPoll#aacfff84 flags:# quiz:flags.0?Bool = ButtonType`
  @TLObject(id: 0xaacfff84)
  @TLFlagsEquatable
  public struct ButtonTypeRequestPoll: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var quiz: Bool? = nil
  }

  /// TL: `buttonTypeRequestPeer#4f58a237 flags:# button_id:int peer_type:RequestPeerType max_quantity:int = ButtonType`
  @TLObject(id: 0x4f58a237)
  @TLFlagsEquatable
  public struct ButtonTypeRequestPeer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var buttonId: Int32
    public var peerType: TL.RequestPeerTypeType
    public var maxQuantity: Int32
  }

  /// TL: `inputButtonTypeRequestPeer#3fe268fe flags:# name_requested:flags.0?true username_requested:flags.1?true photo_requested:flags.2?true button_id:int peer_type:RequestPeerType max_quantity:int = ButtonType`
  @TLObject(id: 0x3fe268fe)
  @TLFlagsEquatable
  public struct InputButtonTypeRequestPeer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var nameRequested: Bool = false
    @TLConditional("flags", bit: 1) public var usernameRequested: Bool = false
    @TLConditional("flags", bit: 2) public var photoRequested: Bool = false
    public var buttonId: Int32
    public var peerType: TL.RequestPeerTypeType
    public var maxQuantity: Int32
  }

  /// TL: `buttonTypeSimpleWebView#c01a597a url:string = ButtonType`
  @TLObject(id: 0xc01a597a)
  public struct ButtonTypeSimpleWebView: Equatable, Sendable {
    public var url: String
  }
}
