// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.channelParticipant#dfb80317 participant:ChannelParticipant chats:Vector<Chat> users:Vector<User> = channels.ChannelParticipant`
  @TLObject(id: 0xdfb80317)
  public struct ChannelParticipant: Equatable, Sendable {
    public var participant: TL.ChannelParticipantType
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
