// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `channelAdminLogEvent#1fad68cd id:long date:int user_id:long action:ChannelAdminLogEventAction = ChannelAdminLogEvent`
  @TLObject(id: 0x1fad68cd)
  public struct ChannelAdminLogEvent: Equatable, Sendable {
    public var id: Int64
    public var date: Int32
    public var userId: Int64
    public var action: TL.ChannelAdminLogEventActionType
  }
}
