// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `ChannelMessagesFilter` (2 constructors).
  @TLType
  public indirect enum ChannelMessagesFilterType: Equatable, Sendable {
    /// `channelMessagesFilterEmpty#94d42ee7 = ChannelMessagesFilter`
    case channelMessagesFilterEmpty(TL.ChannelMessagesFilterEmpty)
    /// `channelMessagesFilter#cd77d957 flags:# exclude_new_messages:flags.1?true ranges:Vector<MessageRange> = ChannelMessagesFilter`
    case channelMessagesFilter(TL.ChannelMessagesFilter)
  }

  /// TL: `channelMessagesFilterEmpty#94d42ee7 = ChannelMessagesFilter`
  @TLObject(id: 0x94d42ee7)
  public struct ChannelMessagesFilterEmpty: Equatable, Sendable {
  }

  /// TL: `channelMessagesFilter#cd77d957 flags:# exclude_new_messages:flags.1?true ranges:Vector<MessageRange> = ChannelMessagesFilter`
  @TLObject(id: 0xcd77d957)
  @TLFlagsEquatable
  public struct ChannelMessagesFilter: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var excludeNewMessages: Bool = false
    public var ranges: [TL.MessageRange]
  }
}
