// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// The TL type `channels.ChannelParticipants` (2 constructors).
  @TLType
  public indirect enum ChannelParticipantsType: Equatable, Sendable {
    /// `channels.channelParticipants#9ab0feaf count:int participants:Vector<ChannelParticipant> chats:Vector<Chat> users:Vector<User> = channels.ChannelParticipants`
    case channelParticipants(TL.Channels.ChannelParticipants)
    /// `channels.channelParticipantsNotModified#f0173fe9 = channels.ChannelParticipants`
    case channelParticipantsNotModified(TL.Channels.ChannelParticipantsNotModified)
  }

  /// TL: `channels.channelParticipants#9ab0feaf count:int participants:Vector<ChannelParticipant> chats:Vector<Chat> users:Vector<User> = channels.ChannelParticipants`
  @TLObject(id: 0x9ab0feaf)
  public struct ChannelParticipants: Equatable, Sendable {
    public var count: Int32
    public var participants: [TL.ChannelParticipantType]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }

  /// TL: `channels.channelParticipantsNotModified#f0173fe9 = channels.ChannelParticipants`
  @TLObject(id: 0xf0173fe9)
  public struct ChannelParticipantsNotModified: Equatable, Sendable {
  }
}
