// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `ChannelLocation` (2 constructors).
  @TLType
  public indirect enum ChannelLocationType: Equatable, Sendable {
    /// `channelLocationEmpty#bfb5ad8b = ChannelLocation`
    case channelLocationEmpty(TL.ChannelLocationEmpty)
    /// `channelLocation#209b82db geo_point:GeoPoint address:string = ChannelLocation`
    case channelLocation(TL.ChannelLocation)
  }

  /// TL: `channelLocationEmpty#bfb5ad8b = ChannelLocation`
  @TLObject(id: 0xbfb5ad8b)
  public struct ChannelLocationEmpty: Equatable, Sendable {
  }

  /// TL: `channelLocation#209b82db geo_point:GeoPoint address:string = ChannelLocation`
  @TLObject(id: 0x209b82db)
  public struct ChannelLocation: Equatable, Sendable {
    public var geoPoint: TL.GeoPointType
    public var address: String
  }
}
