// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `chatOnlines#f041e250 onlines:int = ChatOnlines`
  @TLObject(id: 0xf041e250)
  public struct ChatOnlines: Equatable, Sendable {
    public var onlines: Int32
  }
}
