// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `chatInviteImporter#8c5adfd9 flags:# requested:flags.0?true via_chatlist:flags.3?true user_id:long date:int about:flags.2?string approved_by:flags.1?long = ChatInviteImporter`
  @TLObject(id: 0x8c5adfd9)
  @TLFlagsEquatable
  public struct ChatInviteImporter: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var requested: Bool = false
    @TLConditional("flags", bit: 3) public var viaChatlist: Bool = false
    public var userId: Int64
    public var date: Int32
    @TLConditional("flags", bit: 2) public var about: String? = nil
    @TLConditional("flags", bit: 1) public var approvedBy: Int64? = nil
  }
}
