// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Chatlists {

  /// The TL type `chatlists.ChatlistInvite` (2 constructors).
  @TLType
  public indirect enum ChatlistInviteType: Equatable, Sendable {
    /// `chatlists.chatlistInviteAlready#fa87f659 filter_id:int missing_peers:Vector<Peer> already_peers:Vector<Peer> chats:Vector<Chat> users:Vector<User> = chatlists.ChatlistInvite`
    case chatlistInviteAlready(TL.Chatlists.ChatlistInviteAlready)
    /// `chatlists.chatlistInvite#f10ece2f flags:# title_noanimate:flags.1?true title:TextWithEntities emoticon:flags.0?string peers:Vector<Peer> chats:Vector<Chat> users:Vector<User> = chatlists.ChatlistInvite`
    case chatlistInvite(TL.Chatlists.ChatlistInvite)
  }

  /// TL: `chatlists.chatlistInviteAlready#fa87f659 filter_id:int missing_peers:Vector<Peer> already_peers:Vector<Peer> chats:Vector<Chat> users:Vector<User> = chatlists.ChatlistInvite`
  @TLObject(id: 0xfa87f659)
  public struct ChatlistInviteAlready: Equatable, Sendable {
    public var filterId: Int32
    public var missingPeers: [TL.PeerType]
    public var alreadyPeers: [TL.PeerType]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }

  /// TL: `chatlists.chatlistInvite#f10ece2f flags:# title_noanimate:flags.1?true title:TextWithEntities emoticon:flags.0?string peers:Vector<Peer> chats:Vector<Chat> users:Vector<User> = chatlists.ChatlistInvite`
  @TLObject(id: 0xf10ece2f)
  @TLFlagsEquatable
  public struct ChatlistInvite: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var titleNoanimate: Bool = false
    public var title: TL.TextWithEntities
    @TLConditional("flags", bit: 0) public var emoticon: String? = nil
    public var peers: [TL.PeerType]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
