// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `ChatInvite` (3 constructors).
  @TLType
  public indirect enum ChatInviteType: Equatable, Sendable {
    /// `chatInviteAlready#5a686d7c chat:Chat = ChatInvite`
    case chatInviteAlready(TL.ChatInviteAlready)
    /// `chatInvite#5c9d3702 flags:# channel:flags.0?true broadcast:flags.1?true public:flags.2?true megagroup:flags.3?true request_needed:flags.6?true verified:flags.7?true scam:flags.8?true fake:flags.9?true can_refulfill_subscription:flags.11?true title:string about:flags.5?string photo:Photo participants_count:int participants:flags.4?Vector<User> color:int subscription_pricing:flags.10?StarsSubscriptionPricing subscription_form_id:flags.12?long bot_verification:flags.13?BotVerification = ChatInvite`
    case chatInvite(TL.ChatInvite)
    /// `chatInvitePeek#61695cb0 chat:Chat expires:int = ChatInvite`
    case chatInvitePeek(TL.ChatInvitePeek)
  }

  /// TL: `chatInviteAlready#5a686d7c chat:Chat = ChatInvite`
  @TLObject(id: 0x5a686d7c)
  public struct ChatInviteAlready: Equatable, Sendable {
    public var chat: TL.ChatType
  }

  /// TL: `chatInvite#5c9d3702 flags:# channel:flags.0?true broadcast:flags.1?true public:flags.2?true megagroup:flags.3?true request_needed:flags.6?true verified:flags.7?true scam:flags.8?true fake:flags.9?true can_refulfill_subscription:flags.11?true title:string about:flags.5?string photo:Photo participants_count:int participants:flags.4?Vector<User> color:int subscription_pricing:flags.10?StarsSubscriptionPricing subscription_form_id:flags.12?long bot_verification:flags.13?BotVerification = ChatInvite`
  @TLObject(id: 0x5c9d3702)
  @TLFlagsEquatable
  public struct ChatInvite: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var channel: Bool = false
    @TLConditional("flags", bit: 1) public var broadcast: Bool = false
    @TLConditional("flags", bit: 2) public var `public`: Bool = false
    @TLConditional("flags", bit: 3) public var megagroup: Bool = false
    @TLConditional("flags", bit: 6) public var requestNeeded: Bool = false
    @TLConditional("flags", bit: 7) public var verified: Bool = false
    @TLConditional("flags", bit: 8) public var scam: Bool = false
    @TLConditional("flags", bit: 9) public var fake: Bool = false
    @TLConditional("flags", bit: 11) public var canRefulfillSubscription: Bool = false
    public var title: String
    @TLConditional("flags", bit: 5) public var about: String? = nil
    public var photo: TL.PhotoType
    public var participantsCount: Int32
    @TLConditional("flags", bit: 4) public var participants: [TL.UserType]? = nil
    public var color: Int32
    @TLConditional("flags", bit: 10) public var subscriptionPricing: TL.StarsSubscriptionPricing? = nil
    @TLConditional("flags", bit: 12) public var subscriptionFormId: Int64? = nil
    @TLConditional("flags", bit: 13) public var botVerification: TL.BotVerification? = nil
  }

  /// TL: `chatInvitePeek#61695cb0 chat:Chat expires:int = ChatInvite`
  @TLObject(id: 0x61695cb0)
  public struct ChatInvitePeek: Equatable, Sendable {
    public var chat: TL.ChatType
    public var expires: Int32
  }
}
