// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Communities {

  /// TL: `communities.peerLinkRequests#2244afad flags:# total_count:int requests:Vector<CommunityPeerRequest> next_offset:flags.0?string chats:Vector<Chat> users:Vector<User> = communities.PeerLinkRequests`
  @TLObject(id: 0x2244afad)
  @TLFlagsEquatable
  public struct PeerLinkRequests: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var totalCount: Int32
    public var requests: [TL.CommunityPeerRequest]
    @TLConditional("flags", bit: 0) public var nextOffset: String? = nil
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
