// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `communityPeer#76141ebd flags:# can_view_history:flags.2?true visible:flags.0?Bool peer:Peer = CommunityPeer`
  @TLObject(id: 0x76141ebd)
  @TLFlagsEquatable
  public struct CommunityPeer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var canViewHistory: Bool = false
    @TLConditional("flags", bit: 0) public var visible: Bool? = nil
    public var peer: TL.PeerType
  }
}
