// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.found#b3134d9d my_results:Vector<Peer> results:Vector<Peer> chats:Vector<Chat> users:Vector<User> = contacts.Found`
  @TLObject(id: 0xb3134d9d)
  public struct Found: Equatable, Sendable {
    public var myResults: [TL.PeerType]
    public var results: [TL.PeerType]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
