// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `contactBirthday#1d998733 contact_id:long birthday:Birthday = ContactBirthday`
  @TLObject(id: 0x1d998733)
  public struct ContactBirthday: Equatable, Sendable {
    public var contactId: Int64
    public var birthday: TL.Birthday
  }
}
