// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// The TL type `contacts.TopPeers` (3 constructors).
  @TLType
  public indirect enum TopPeersType: Equatable, Sendable {
    /// `contacts.topPeersNotModified#de266ef5 = contacts.TopPeers`
    case topPeersNotModified(TL.Contacts.TopPeersNotModified)
    /// `contacts.topPeers#70b772a8 categories:Vector<TopPeerCategoryPeers> chats:Vector<Chat> users:Vector<User> = contacts.TopPeers`
    case topPeers(TL.Contacts.TopPeers)
    /// `contacts.topPeersDisabled#b52c939d = contacts.TopPeers`
    case topPeersDisabled(TL.Contacts.TopPeersDisabled)
  }

  /// TL: `contacts.topPeersNotModified#de266ef5 = contacts.TopPeers`
  @TLObject(id: 0xde266ef5)
  public struct TopPeersNotModified: Equatable, Sendable {
  }

  /// TL: `contacts.topPeers#70b772a8 categories:Vector<TopPeerCategoryPeers> chats:Vector<Chat> users:Vector<User> = contacts.TopPeers`
  @TLObject(id: 0x70b772a8)
  public struct TopPeers: Equatable, Sendable {
    public var categories: [TL.TopPeerCategoryPeers]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }

  /// TL: `contacts.topPeersDisabled#b52c939d = contacts.TopPeers`
  @TLObject(id: 0xb52c939d)
  public struct TopPeersDisabled: Equatable, Sendable {
  }
}
