// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `contactStatus#16d9703b user_id:long status:UserStatus = ContactStatus`
  @TLObject(id: 0x16d9703b)
  public struct ContactStatus: Equatable, Sendable {
    public var userId: Int64
    public var status: TL.UserStatusType
  }
}
