// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `emojiLanguage#b3fb5361 lang_code:string = EmojiLanguage`
  @TLObject(id: 0xb3fb5361)
  public struct EmojiLanguage: Equatable, Sendable {
    public var langCode: String
  }
}
