// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `emojiKeywordsDifference#5cc761bd lang_code:string from_version:int version:int keywords:Vector<EmojiKeyword> = EmojiKeywordsDifference`
  @TLObject(id: 0x5cc761bd)
  public struct EmojiKeywordsDifference: Equatable, Sendable {
    public var langCode: String
    public var fromVersion: Int32
    public var version: Int32
    public var keywords: [TL.EmojiKeywordType]
  }
}
