// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Ephemeral {

  /// The TL type `ephemeral.WelcomeMessages` (2 constructors).
  @TLType
  public indirect enum WelcomeMessagesType: Equatable, Sendable {
    /// `ephemeral.welcomeMessagesNotModified#59ffdb31 = ephemeral.WelcomeMessages`
    case welcomeMessagesNotModified(TL.Ephemeral.WelcomeMessagesNotModified)
    /// `ephemeral.welcomeMessages#104fc872 hash:long messages:Vector<EphemeralMessage> = ephemeral.WelcomeMessages`
    case welcomeMessages(TL.Ephemeral.WelcomeMessages)
  }

  /// TL: `ephemeral.welcomeMessagesNotModified#59ffdb31 = ephemeral.WelcomeMessages`
  @TLObject(id: 0x59ffdb31)
  public struct WelcomeMessagesNotModified: Equatable, Sendable {
  }

  /// TL: `ephemeral.welcomeMessages#104fc872 hash:long messages:Vector<EphemeralMessage> = ephemeral.WelcomeMessages`
  @TLObject(id: 0x104fc872)
  public struct WelcomeMessages: Equatable, Sendable {
    public var hash: Int64
    public var messages: [TL.EphemeralMessage]
  }
}
