// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `exportedChatlistInvite#0c5181ac flags:# title:string url:string peers:Vector<Peer> = ExportedChatlistInvite`
  @TLObject(id: 0x0c5181ac)
  @TLFlagsEquatable
  public struct ExportedChatlistInvite: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var title: String
    public var url: String
    public var peers: [TL.PeerType]
  }
}
