// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `exportedMessageLink#5dab1af4 link:string html:string = ExportedMessageLink`
  @TLObject(id: 0x5dab1af4)
  public struct ExportedMessageLink: Equatable, Sendable {
    public var link: String
    public var html: String
  }
}
