// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Fragment {

  /// TL: `fragment.collectibleInfo#6ebdff91 purchase_date:int currency:string amount:long crypto_currency:string crypto_amount:long url:string = fragment.CollectibleInfo`
  @TLObject(id: 0x6ebdff91)
  public struct CollectibleInfo: Equatable, Sendable {
    public var purchaseDate: Int32
    public var currency: String
    public var amount: Int64
    public var cryptoCurrency: String
    public var cryptoAmount: Int64
    public var url: String
  }
}
