// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `groupCallDonor#ee430c85 flags:# top:flags.0?true my:flags.1?true peer_id:flags.3?Peer stars:long = GroupCallDonor`
  @TLObject(id: 0xee430c85)
  @TLFlagsEquatable
  public struct GroupCallDonor: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var top: Bool = false
    @TLConditional("flags", bit: 1) public var my: Bool = false
    @TLConditional("flags", bit: 3) public var peerId: TL.PeerType? = nil
    public var stars: Int64
  }
}
