// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// The TL type `help.CountriesList` (2 constructors).
  @TLType
  public indirect enum CountriesListType: Equatable, Sendable {
    /// `help.countriesListNotModified#93cc1f32 = help.CountriesList`
    case countriesListNotModified(TL.Help.CountriesListNotModified)
    /// `help.countriesList#87d0759e countries:Vector<help.Country> hash:int = help.CountriesList`
    case countriesList(TL.Help.CountriesList)
  }

  /// TL: `help.countriesListNotModified#93cc1f32 = help.CountriesList`
  @TLObject(id: 0x93cc1f32)
  public struct CountriesListNotModified: Equatable, Sendable {
  }

  /// TL: `help.countriesList#87d0759e countries:Vector<help.Country> hash:int = help.CountriesList`
  @TLObject(id: 0x87d0759e)
  public struct CountriesList: Equatable, Sendable {
    public var countries: [TL.Help.Country]
    public var hash: Int32
  }
}
