// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// The TL type `help.DeepLinkInfo` (2 constructors).
  @TLType
  public indirect enum DeepLinkInfoType: Equatable, Sendable {
    /// `help.deepLinkInfoEmpty#66afa166 = help.DeepLinkInfo`
    case deepLinkInfoEmpty(TL.Help.DeepLinkInfoEmpty)
    /// `help.deepLinkInfo#6a4ee832 flags:# update_app:flags.0?true message:string entities:flags.1?Vector<MessageEntity> = help.DeepLinkInfo`
    case deepLinkInfo(TL.Help.DeepLinkInfo)
  }

  /// TL: `help.deepLinkInfoEmpty#66afa166 = help.DeepLinkInfo`
  @TLObject(id: 0x66afa166)
  public struct DeepLinkInfoEmpty: Equatable, Sendable {
  }

  /// TL: `help.deepLinkInfo#6a4ee832 flags:# update_app:flags.0?true message:string entities:flags.1?Vector<MessageEntity> = help.DeepLinkInfo`
  @TLObject(id: 0x6a4ee832)
  @TLFlagsEquatable
  public struct DeepLinkInfo: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var updateApp: Bool = false
    public var message: String
    @TLConditional("flags", bit: 1) public var entities: [TL.MessageEntityType]? = nil
  }
}
