// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// The TL type `help.PeerColorSet` (2 constructors).
  @TLType
  public indirect enum PeerColorSetType: Equatable, Sendable {
    /// `help.peerColorSet#26219a58 colors:Vector<int> = help.PeerColorSet`
    case peerColorSet(TL.Help.PeerColorSet)
    /// `help.peerColorProfileSet#767d61eb palette_colors:Vector<int> bg_colors:Vector<int> story_colors:Vector<int> = help.PeerColorSet`
    case peerColorProfileSet(TL.Help.PeerColorProfileSet)
  }

  /// TL: `help.peerColorSet#26219a58 colors:Vector<int> = help.PeerColorSet`
  @TLObject(id: 0x26219a58)
  public struct PeerColorSet: Equatable, Sendable {
    public var colors: [Int32]
  }

  /// TL: `help.peerColorProfileSet#767d61eb palette_colors:Vector<int> bg_colors:Vector<int> story_colors:Vector<int> = help.PeerColorSet`
  @TLObject(id: 0x767d61eb)
  public struct PeerColorProfileSet: Equatable, Sendable {
    public var paletteColors: [Int32]
    public var bgColors: [Int32]
    public var storyColors: [Int32]
  }
}
