// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.peerColorOption#adec6ebe flags:# hidden:flags.0?true color_id:int colors:flags.1?help.PeerColorSet dark_colors:flags.2?help.PeerColorSet channel_min_level:flags.3?int group_min_level:flags.4?int = help.PeerColorOption`
  @TLObject(id: 0xadec6ebe)
  @TLFlagsEquatable
  public struct PeerColorOption: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var hidden: Bool = false
    public var colorId: Int32
    @TLConditional("flags", bit: 1) public var colors: TL.Help.PeerColorSetType? = nil
    @TLConditional("flags", bit: 2) public var darkColors: TL.Help.PeerColorSetType? = nil
    @TLConditional("flags", bit: 3) public var channelMinLevel: Int32? = nil
    @TLConditional("flags", bit: 4) public var groupMinLevel: Int32? = nil
  }
}
