// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.country#c3878e23 flags:# hidden:flags.0?true iso2:string default_name:string name:flags.1?string country_codes:Vector<help.CountryCode> = help.Country`
  @TLObject(id: 0xc3878e23)
  @TLFlagsEquatable
  public struct Country: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var hidden: Bool = false
    public var iso2: String
    public var defaultName: String
    @TLConditional("flags", bit: 1) public var name: String? = nil
    public var countryCodes: [TL.Help.CountryCode]
  }
}
