// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// TL: `help.inviteText#18cb9f78 message:string = help.InviteText`
  @TLObject(id: 0x18cb9f78)
  public struct InviteText: Equatable, Sendable {
    public var message: String
  }
}
