// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Help {

  /// The TL type `help.TermsOfServiceUpdate` (2 constructors).
  @TLType
  public indirect enum TermsOfServiceUpdateType: Equatable, Sendable {
    /// `help.termsOfServiceUpdateEmpty#e3309f7f expires:int = help.TermsOfServiceUpdate`
    case termsOfServiceUpdateEmpty(TL.Help.TermsOfServiceUpdateEmpty)
    /// `help.termsOfServiceUpdate#28ecf961 expires:int terms_of_service:help.TermsOfService = help.TermsOfServiceUpdate`
    case termsOfServiceUpdate(TL.Help.TermsOfServiceUpdate)
  }

  /// TL: `help.termsOfServiceUpdateEmpty#e3309f7f expires:int = help.TermsOfServiceUpdate`
  @TLObject(id: 0xe3309f7f)
  public struct TermsOfServiceUpdateEmpty: Equatable, Sendable {
    public var expires: Int32
  }

  /// TL: `help.termsOfServiceUpdate#28ecf961 expires:int terms_of_service:help.TermsOfService = help.TermsOfServiceUpdate`
  @TLObject(id: 0x28ecf961)
  public struct TermsOfServiceUpdate: Equatable, Sendable {
    public var expires: Int32
    public var termsOfService: TL.Help.TermsOfService
  }
}
