// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `highScore#73a379eb pos:int user_id:long score:int = HighScore`
  @TLObject(id: 0x73a379eb)
  public struct HighScore: Equatable, Sendable {
    public var pos: Int32
    public var userId: Int64
    public var score: Int32
  }
}
