// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InlineButtonType` (12 constructors).
  @TLType
  public indirect enum InlineButtonTypeType: Equatable, Sendable {
    /// `inlineButtonTypeUrl#eca4f8d4 url:string = InlineButtonType`
    case inlineButtonTypeUrl(TL.InlineButtonTypeUrl)
    /// `inlineButtonTypeUrlAuth#bfd02da2 flags:# fwd_text:flags.0?string url:string button_id:int = InlineButtonType`
    case inlineButtonTypeUrlAuth(TL.InlineButtonTypeUrlAuth)
    /// `inputInlineButtonTypeUrlAuth#9961bcb4 flags:# request_write_access:flags.0?true fwd_text:flags.1?string url:string bot:flags.2?InputUser = InlineButtonType`
    case inputInlineButtonTypeUrlAuth(TL.InputInlineButtonTypeUrlAuth)
    /// `inlineButtonTypeWebView#3bcab5b4 url:string = InlineButtonType`
    case inlineButtonTypeWebView(TL.InlineButtonTypeWebView)
    /// `inlineButtonTypeCallback#2955bc38 flags:# requires_password:flags.0?true data:bytes = InlineButtonType`
    case inlineButtonTypeCallback(TL.InlineButtonTypeCallback)
    /// `inlineButtonTypeGame#5cd3709d = InlineButtonType`
    case inlineButtonTypeGame(TL.InlineButtonTypeGame)
    /// `inlineButtonTypeBuy#48bad7a5 = InlineButtonType`
    case inlineButtonTypeBuy(TL.InlineButtonTypeBuy)
    /// `inlineButtonTypeSwitchInline#93773ff5 flags:# same_peer:flags.0?true query:string peer_types:flags.1?Vector<InlineQueryPeerType> = InlineButtonType`
    case inlineButtonTypeSwitchInline(TL.InlineButtonTypeSwitchInline)
    /// `inlineButtonTypeUserProfile#3fa33fcf user_id:long = InlineButtonType`
    case inlineButtonTypeUserProfile(TL.InlineButtonTypeUserProfile)
    /// `inputInlineButtonTypeUserProfile#53f3ce5a user_id:InputUser = InlineButtonType`
    case inputInlineButtonTypeUserProfile(TL.InputInlineButtonTypeUserProfile)
    /// `inlineButtonTypeCopy#b41d3272 copy_text:string = InlineButtonType`
    case inlineButtonTypeCopy(TL.InlineButtonTypeCopy)
    /// `inlineButtonTypeDisabled#a438619d = InlineButtonType`
    case inlineButtonTypeDisabled(TL.InlineButtonTypeDisabled)
  }

  /// TL: `inlineButtonTypeUrl#eca4f8d4 url:string = InlineButtonType`
  @TLObject(id: 0xeca4f8d4)
  public struct InlineButtonTypeUrl: Equatable, Sendable {
    public var url: String
  }

  /// TL: `inlineButtonTypeUrlAuth#bfd02da2 flags:# fwd_text:flags.0?string url:string button_id:int = InlineButtonType`
  @TLObject(id: 0xbfd02da2)
  @TLFlagsEquatable
  public struct InlineButtonTypeUrlAuth: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var fwdText: String? = nil
    public var url: String
    public var buttonId: Int32
  }

  /// TL: `inputInlineButtonTypeUrlAuth#9961bcb4 flags:# request_write_access:flags.0?true fwd_text:flags.1?string url:string bot:flags.2?InputUser = InlineButtonType`
  @TLObject(id: 0x9961bcb4)
  @TLFlagsEquatable
  public struct InputInlineButtonTypeUrlAuth: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var requestWriteAccess: Bool = false
    @TLConditional("flags", bit: 1) public var fwdText: String? = nil
    public var url: String
    @TLConditional("flags", bit: 2) public var bot: TL.InputUserType? = nil
  }

  /// TL: `inlineButtonTypeWebView#3bcab5b4 url:string = InlineButtonType`
  @TLObject(id: 0x3bcab5b4)
  public struct InlineButtonTypeWebView: Equatable, Sendable {
    public var url: String
  }

  /// TL: `inlineButtonTypeCallback#2955bc38 flags:# requires_password:flags.0?true data:bytes = InlineButtonType`
  @TLObject(id: 0x2955bc38)
  @TLFlagsEquatable
  public struct InlineButtonTypeCallback: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var requiresPassword: Bool = false
    public var data: Data
  }

  /// TL: `inlineButtonTypeGame#5cd3709d = InlineButtonType`
  @TLObject(id: 0x5cd3709d)
  public struct InlineButtonTypeGame: Equatable, Sendable {
  }

  /// TL: `inlineButtonTypeBuy#48bad7a5 = InlineButtonType`
  @TLObject(id: 0x48bad7a5)
  public struct InlineButtonTypeBuy: Equatable, Sendable {
  }

  /// TL: `inlineButtonTypeSwitchInline#93773ff5 flags:# same_peer:flags.0?true query:string peer_types:flags.1?Vector<InlineQueryPeerType> = InlineButtonType`
  @TLObject(id: 0x93773ff5)
  @TLFlagsEquatable
  public struct InlineButtonTypeSwitchInline: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var samePeer: Bool = false
    public var query: String
    @TLConditional("flags", bit: 1) public var peerTypes: [TL.InlineQueryPeerTypeType]? = nil
  }

  /// TL: `inlineButtonTypeUserProfile#3fa33fcf user_id:long = InlineButtonType`
  @TLObject(id: 0x3fa33fcf)
  public struct InlineButtonTypeUserProfile: Equatable, Sendable {
    public var userId: Int64
  }

  /// TL: `inputInlineButtonTypeUserProfile#53f3ce5a user_id:InputUser = InlineButtonType`
  @TLObject(id: 0x53f3ce5a)
  public struct InputInlineButtonTypeUserProfile: Equatable, Sendable {
    public var userId: TL.InputUserType
  }

  /// TL: `inlineButtonTypeCopy#b41d3272 copy_text:string = InlineButtonType`
  @TLObject(id: 0xb41d3272)
  public struct InlineButtonTypeCopy: Equatable, Sendable {
    public var copyText: String
  }

  /// TL: `inlineButtonTypeDisabled#a438619d = InlineButtonType`
  @TLObject(id: 0xa438619d)
  public struct InlineButtonTypeDisabled: Equatable, Sendable {
  }
}
