// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputInvoice` (15 constructors).
  @TLType
  public indirect enum InputInvoiceType: Equatable, Sendable {
    /// `inputInvoiceMessage#c5b56859 peer:InputPeer msg_id:int = InputInvoice`
    case inputInvoiceMessage(TL.InputInvoiceMessage)
    /// `inputInvoiceSlug#c326caef slug:string = InputInvoice`
    case inputInvoiceSlug(TL.InputInvoiceSlug)
    /// `inputInvoicePremiumGiftCode#98986c0d purpose:InputStorePaymentPurpose option:PremiumGiftCodeOption = InputInvoice`
    case inputInvoicePremiumGiftCode(TL.InputInvoicePremiumGiftCode)
    /// `inputInvoiceStars#65f00ce3 purpose:InputStorePaymentPurpose = InputInvoice`
    case inputInvoiceStars(TL.InputInvoiceStars)
    /// `inputInvoiceChatInviteSubscription#34e793f1 hash:string = InputInvoice`
    case inputInvoiceChatInviteSubscription(TL.InputInvoiceChatInviteSubscription)
    /// `inputInvoiceStarGift#e8625e92 flags:# hide_name:flags.0?true include_upgrade:flags.2?true peer:InputPeer gift_id:long message:flags.1?TextWithEntities = InputInvoice`
    case inputInvoiceStarGift(TL.InputInvoiceStarGift)
    /// `inputInvoiceStarGiftUpgrade#4d818d5d flags:# keep_original_details:flags.0?true stargift:InputSavedStarGift = InputInvoice`
    case inputInvoiceStarGiftUpgrade(TL.InputInvoiceStarGiftUpgrade)
    /// `inputInvoiceStarGiftTransfer#4a5f5bd9 stargift:InputSavedStarGift to_id:InputPeer = InputInvoice`
    case inputInvoiceStarGiftTransfer(TL.InputInvoiceStarGiftTransfer)
    /// `inputInvoicePremiumGiftStars#dabab2ef flags:# user_id:InputUser months:int message:flags.0?TextWithEntities = InputInvoice`
    case inputInvoicePremiumGiftStars(TL.InputInvoicePremiumGiftStars)
    /// `inputInvoiceBusinessBotTransferStars#f4997e42 bot:InputUser stars:long = InputInvoice`
    case inputInvoiceBusinessBotTransferStars(TL.InputInvoiceBusinessBotTransferStars)
    /// `inputInvoiceStarGiftResale#e9b0c658 flags:# ton:flags.0?true show_name:flags.2?true slug:string to_id:InputPeer message:flags.1?TextWithEntities = InputInvoice`
    case inputInvoiceStarGiftResale(TL.InputInvoiceStarGiftResale)
    /// `inputInvoiceStarGiftPrepaidUpgrade#9a0b48b8 peer:InputPeer hash:string = InputInvoice`
    case inputInvoiceStarGiftPrepaidUpgrade(TL.InputInvoiceStarGiftPrepaidUpgrade)
    /// `inputInvoicePremiumAuthCode#3e77f614 purpose:InputStorePaymentPurpose = InputInvoice`
    case inputInvoicePremiumAuthCode(TL.InputInvoicePremiumAuthCode)
    /// `inputInvoiceStarGiftDropOriginalDetails#0923d8d1 stargift:InputSavedStarGift = InputInvoice`
    case inputInvoiceStarGiftDropOriginalDetails(TL.InputInvoiceStarGiftDropOriginalDetails)
    /// `inputInvoiceStarGiftAuctionBid#1ecafa10 flags:# hide_name:flags.0?true update_bid:flags.2?true peer:flags.3?InputPeer gift_id:long bid_amount:long message:flags.1?TextWithEntities = InputInvoice`
    case inputInvoiceStarGiftAuctionBid(TL.InputInvoiceStarGiftAuctionBid)
  }

  /// TL: `inputInvoiceMessage#c5b56859 peer:InputPeer msg_id:int = InputInvoice`
  @TLObject(id: 0xc5b56859)
  public struct InputInvoiceMessage: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }

  /// TL: `inputInvoiceSlug#c326caef slug:string = InputInvoice`
  @TLObject(id: 0xc326caef)
  public struct InputInvoiceSlug: Equatable, Sendable {
    public var slug: String
  }

  /// TL: `inputInvoicePremiumGiftCode#98986c0d purpose:InputStorePaymentPurpose option:PremiumGiftCodeOption = InputInvoice`
  @TLObject(id: 0x98986c0d)
  public struct InputInvoicePremiumGiftCode: Equatable, Sendable {
    public var purpose: TL.InputStorePaymentPurposeType
    public var option: TL.PremiumGiftCodeOption
  }

  /// TL: `inputInvoiceStars#65f00ce3 purpose:InputStorePaymentPurpose = InputInvoice`
  @TLObject(id: 0x65f00ce3)
  public struct InputInvoiceStars: Equatable, Sendable {
    public var purpose: TL.InputStorePaymentPurposeType
  }

  /// TL: `inputInvoiceChatInviteSubscription#34e793f1 hash:string = InputInvoice`
  @TLObject(id: 0x34e793f1)
  public struct InputInvoiceChatInviteSubscription: Equatable, Sendable {
    public var hash: String
  }

  /// TL: `inputInvoiceStarGift#e8625e92 flags:# hide_name:flags.0?true include_upgrade:flags.2?true peer:InputPeer gift_id:long message:flags.1?TextWithEntities = InputInvoice`
  @TLObject(id: 0xe8625e92)
  @TLFlagsEquatable
  public struct InputInvoiceStarGift: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var hideName: Bool = false
    @TLConditional("flags", bit: 2) public var includeUpgrade: Bool = false
    public var peer: TL.InputPeerType
    public var giftId: Int64
    @TLConditional("flags", bit: 1) public var message: TL.TextWithEntities? = nil
  }

  /// TL: `inputInvoiceStarGiftUpgrade#4d818d5d flags:# keep_original_details:flags.0?true stargift:InputSavedStarGift = InputInvoice`
  @TLObject(id: 0x4d818d5d)
  @TLFlagsEquatable
  public struct InputInvoiceStarGiftUpgrade: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var keepOriginalDetails: Bool = false
    public var stargift: TL.InputSavedStarGiftType
  }

  /// TL: `inputInvoiceStarGiftTransfer#4a5f5bd9 stargift:InputSavedStarGift to_id:InputPeer = InputInvoice`
  @TLObject(id: 0x4a5f5bd9)
  public struct InputInvoiceStarGiftTransfer: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
    public var toId: TL.InputPeerType
  }

  /// TL: `inputInvoicePremiumGiftStars#dabab2ef flags:# user_id:InputUser months:int message:flags.0?TextWithEntities = InputInvoice`
  @TLObject(id: 0xdabab2ef)
  @TLFlagsEquatable
  public struct InputInvoicePremiumGiftStars: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var userId: TL.InputUserType
    public var months: Int32
    @TLConditional("flags", bit: 0) public var message: TL.TextWithEntities? = nil
  }

  /// TL: `inputInvoiceBusinessBotTransferStars#f4997e42 bot:InputUser stars:long = InputInvoice`
  @TLObject(id: 0xf4997e42)
  public struct InputInvoiceBusinessBotTransferStars: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var stars: Int64
  }

  /// TL: `inputInvoiceStarGiftResale#e9b0c658 flags:# ton:flags.0?true show_name:flags.2?true slug:string to_id:InputPeer message:flags.1?TextWithEntities = InputInvoice`
  @TLObject(id: 0xe9b0c658)
  @TLFlagsEquatable
  public struct InputInvoiceStarGiftResale: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var ton: Bool = false
    @TLConditional("flags", bit: 2) public var showName: Bool = false
    public var slug: String
    public var toId: TL.InputPeerType
    @TLConditional("flags", bit: 1) public var message: TL.TextWithEntities? = nil
  }

  /// TL: `inputInvoiceStarGiftPrepaidUpgrade#9a0b48b8 peer:InputPeer hash:string = InputInvoice`
  @TLObject(id: 0x9a0b48b8)
  public struct InputInvoiceStarGiftPrepaidUpgrade: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var hash: String
  }

  /// TL: `inputInvoicePremiumAuthCode#3e77f614 purpose:InputStorePaymentPurpose = InputInvoice`
  @TLObject(id: 0x3e77f614)
  public struct InputInvoicePremiumAuthCode: Equatable, Sendable {
    public var purpose: TL.InputStorePaymentPurposeType
  }

  /// TL: `inputInvoiceStarGiftDropOriginalDetails#0923d8d1 stargift:InputSavedStarGift = InputInvoice`
  @TLObject(id: 0x0923d8d1)
  public struct InputInvoiceStarGiftDropOriginalDetails: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
  }

  /// TL: `inputInvoiceStarGiftAuctionBid#1ecafa10 flags:# hide_name:flags.0?true update_bid:flags.2?true peer:flags.3?InputPeer gift_id:long bid_amount:long message:flags.1?TextWithEntities = InputInvoice`
  @TLObject(id: 0x1ecafa10)
  @TLFlagsEquatable
  public struct InputInvoiceStarGiftAuctionBid: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var hideName: Bool = false
    @TLConditional("flags", bit: 2) public var updateBid: Bool = false
    @TLConditional("flags", bit: 3) public var peer: TL.InputPeerType? = nil
    public var giftId: Int64
    public var bidAmount: Int64
    @TLConditional("flags", bit: 1) public var message: TL.TextWithEntities? = nil
  }
}
