// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `inputSingleMedia#1cc6e91f flags:# media:InputMedia random_id:long message:string entities:flags.0?Vector<MessageEntity> = InputSingleMedia`
  @TLObject(id: 0x1cc6e91f)
  @TLFlagsEquatable
  public struct InputSingleMedia: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var media: TL.InputMediaType
    public var randomId: Int64
    public var message: String
    @TLConditional("flags", bit: 0) public var entities: [TL.MessageEntityType]? = nil
  }
}
