// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputChatTheme` (3 constructors).
  @TLType
  public indirect enum InputChatThemeType: Equatable, Sendable {
    /// `inputChatThemeEmpty#83268483 = InputChatTheme`
    case inputChatThemeEmpty(TL.InputChatThemeEmpty)
    /// `inputChatTheme#c93de95c emoticon:string = InputChatTheme`
    case inputChatTheme(TL.InputChatTheme)
    /// `inputChatThemeUniqueGift#87e5dfe4 slug:string = InputChatTheme`
    case inputChatThemeUniqueGift(TL.InputChatThemeUniqueGift)
  }

  /// TL: `inputChatThemeEmpty#83268483 = InputChatTheme`
  @TLObject(id: 0x83268483)
  public struct InputChatThemeEmpty: Equatable, Sendable {
  }

  /// TL: `inputChatTheme#c93de95c emoticon:string = InputChatTheme`
  @TLObject(id: 0xc93de95c)
  public struct InputChatTheme: Equatable, Sendable {
    public var emoticon: String
  }

  /// TL: `inputChatThemeUniqueGift#87e5dfe4 slug:string = InputChatTheme`
  @TLObject(id: 0x87e5dfe4)
  public struct InputChatThemeUniqueGift: Equatable, Sendable {
    public var slug: String
  }
}
