// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `inputFolderPeer#fbd2c296 peer:InputPeer folder_id:int = InputFolderPeer`
  @TLObject(id: 0xfbd2c296)
  public struct InputFolderPeer: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var folderId: Int32
  }
}
