// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputPaymentCredentials` (4 constructors).
  @TLType
  public indirect enum InputPaymentCredentialsType: Equatable, Sendable {
    /// `inputPaymentCredentialsSaved#c10eb2cf id:string tmp_password:bytes = InputPaymentCredentials`
    case inputPaymentCredentialsSaved(TL.InputPaymentCredentialsSaved)
    /// `inputPaymentCredentials#3417d728 flags:# save:flags.0?true data:DataJSON = InputPaymentCredentials`
    case inputPaymentCredentials(TL.InputPaymentCredentials)
    /// `inputPaymentCredentialsApplePay#0aa1c39f payment_data:DataJSON = InputPaymentCredentials`
    case inputPaymentCredentialsApplePay(TL.InputPaymentCredentialsApplePay)
    /// `inputPaymentCredentialsGooglePay#8ac32801 payment_token:DataJSON = InputPaymentCredentials`
    case inputPaymentCredentialsGooglePay(TL.InputPaymentCredentialsGooglePay)
  }

  /// TL: `inputPaymentCredentialsSaved#c10eb2cf id:string tmp_password:bytes = InputPaymentCredentials`
  @TLObject(id: 0xc10eb2cf)
  public struct InputPaymentCredentialsSaved: Equatable, Sendable {
    public var id: String
    public var tmpPassword: Data
  }

  /// TL: `inputPaymentCredentials#3417d728 flags:# save:flags.0?true data:DataJSON = InputPaymentCredentials`
  @TLObject(id: 0x3417d728)
  @TLFlagsEquatable
  public struct InputPaymentCredentials: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var save: Bool = false
    public var data: TL.DataJSON
  }

  /// TL: `inputPaymentCredentialsApplePay#0aa1c39f payment_data:DataJSON = InputPaymentCredentials`
  @TLObject(id: 0x0aa1c39f)
  public struct InputPaymentCredentialsApplePay: Equatable, Sendable {
    public var paymentData: TL.DataJSON
  }

  /// TL: `inputPaymentCredentialsGooglePay#8ac32801 payment_token:DataJSON = InputPaymentCredentials`
  @TLObject(id: 0x8ac32801)
  public struct InputPaymentCredentialsGooglePay: Equatable, Sendable {
    public var paymentToken: TL.DataJSON
  }
}
