// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `inputBusinessBotRecipients#c4e5921e flags:# existing_chats:flags.0?true new_chats:flags.1?true contacts:flags.2?true non_contacts:flags.3?true exclude_selected:flags.5?true users:flags.4?Vector<InputUser> exclude_users:flags.6?Vector<InputUser> = InputBusinessBotRecipients`
  @TLObject(id: 0xc4e5921e)
  @TLFlagsEquatable
  public struct InputBusinessBotRecipients: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var existingChats: Bool = false
    @TLConditional("flags", bit: 1) public var newChats: Bool = false
    @TLConditional("flags", bit: 2) public var contacts: Bool = false
    @TLConditional("flags", bit: 3) public var nonContacts: Bool = false
    @TLConditional("flags", bit: 5) public var excludeSelected: Bool = false
    @TLConditional("flags", bit: 4) public var users: [TL.InputUserType]? = nil
    @TLConditional("flags", bit: 6) public var excludeUsers: [TL.InputUserType]? = nil
  }
}
