// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputEncryptedFile` (4 constructors).
  @TLType
  public indirect enum InputEncryptedFileType: Equatable, Sendable {
    /// `inputEncryptedFileEmpty#1837c364 = InputEncryptedFile`
    case inputEncryptedFileEmpty(TL.InputEncryptedFileEmpty)
    /// `inputEncryptedFileUploaded#64bd0306 id:long parts:int md5_checksum:string key_fingerprint:int = InputEncryptedFile`
    case inputEncryptedFileUploaded(TL.InputEncryptedFileUploaded)
    /// `inputEncryptedFile#5a17b5e5 id:long access_hash:long = InputEncryptedFile`
    case inputEncryptedFile(TL.InputEncryptedFile)
    /// `inputEncryptedFileBigUploaded#2dc173c8 id:long parts:int key_fingerprint:int = InputEncryptedFile`
    case inputEncryptedFileBigUploaded(TL.InputEncryptedFileBigUploaded)
  }

  /// TL: `inputEncryptedFileEmpty#1837c364 = InputEncryptedFile`
  @TLObject(id: 0x1837c364)
  public struct InputEncryptedFileEmpty: Equatable, Sendable {
  }

  /// TL: `inputEncryptedFileUploaded#64bd0306 id:long parts:int md5_checksum:string key_fingerprint:int = InputEncryptedFile`
  @TLObject(id: 0x64bd0306)
  public struct InputEncryptedFileUploaded: Equatable, Sendable {
    public var id: Int64
    public var parts: Int32
    public var md5Checksum: String
    public var keyFingerprint: Int32
  }

  /// TL: `inputEncryptedFile#5a17b5e5 id:long access_hash:long = InputEncryptedFile`
  @TLObject(id: 0x5a17b5e5)
  public struct InputEncryptedFile: Equatable, Sendable {
    public var id: Int64
    public var accessHash: Int64
  }

  /// TL: `inputEncryptedFileBigUploaded#2dc173c8 id:long parts:int key_fingerprint:int = InputEncryptedFile`
  @TLObject(id: 0x2dc173c8)
  public struct InputEncryptedFileBigUploaded: Equatable, Sendable {
    public var id: Int64
    public var parts: Int32
    public var keyFingerprint: Int32
  }
}
