// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputStorePaymentPurpose` (8 constructors).
  @TLType
  public indirect enum InputStorePaymentPurposeType: Equatable, Sendable {
    /// `inputStorePaymentPremiumSubscription#a6751e66 flags:# restore:flags.0?true upgrade:flags.1?true = InputStorePaymentPurpose`
    case inputStorePaymentPremiumSubscription(TL.InputStorePaymentPremiumSubscription)
    /// `inputStorePaymentGiftPremium#616f7fe8 user_id:InputUser currency:string amount:long = InputStorePaymentPurpose`
    case inputStorePaymentGiftPremium(TL.InputStorePaymentGiftPremium)
    /// `inputStorePaymentPremiumGiftCode#fb790393 flags:# users:Vector<InputUser> boost_peer:flags.0?InputPeer currency:string amount:long message:flags.1?TextWithEntities = InputStorePaymentPurpose`
    case inputStorePaymentPremiumGiftCode(TL.InputStorePaymentPremiumGiftCode)
    /// `inputStorePaymentPremiumGiveaway#160544ca flags:# only_new_subscribers:flags.0?true winners_are_visible:flags.3?true boost_peer:InputPeer additional_peers:flags.1?Vector<InputPeer> countries_iso2:flags.2?Vector<string> prize_description:flags.4?string random_id:long until_date:int currency:string amount:long = InputStorePaymentPurpose`
    case inputStorePaymentPremiumGiveaway(TL.InputStorePaymentPremiumGiveaway)
    /// `inputStorePaymentStarsTopup#f9a2a6cb flags:# stars:long currency:string amount:long spend_purpose_peer:flags.0?InputPeer = InputStorePaymentPurpose`
    case inputStorePaymentStarsTopup(TL.InputStorePaymentStarsTopup)
    /// `inputStorePaymentStarsGift#1d741ef7 user_id:InputUser stars:long currency:string amount:long = InputStorePaymentPurpose`
    case inputStorePaymentStarsGift(TL.InputStorePaymentStarsGift)
    /// `inputStorePaymentStarsGiveaway#751f08fa flags:# only_new_subscribers:flags.0?true winners_are_visible:flags.3?true stars:long boost_peer:InputPeer additional_peers:flags.1?Vector<InputPeer> countries_iso2:flags.2?Vector<string> prize_description:flags.4?string random_id:long until_date:int currency:string amount:long users:int = InputStorePaymentPurpose`
    case inputStorePaymentStarsGiveaway(TL.InputStorePaymentStarsGiveaway)
    /// `inputStorePaymentAuthCode#3fc18057 flags:# restore:flags.0?true phone_number:string phone_code_hash:string premium_days:int currency:string amount:long = InputStorePaymentPurpose`
    case inputStorePaymentAuthCode(TL.InputStorePaymentAuthCode)
  }

  /// TL: `inputStorePaymentPremiumSubscription#a6751e66 flags:# restore:flags.0?true upgrade:flags.1?true = InputStorePaymentPurpose`
  @TLObject(id: 0xa6751e66)
  @TLFlagsEquatable
  public struct InputStorePaymentPremiumSubscription: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var restore: Bool = false
    @TLConditional("flags", bit: 1) public var upgrade: Bool = false
  }

  /// TL: `inputStorePaymentGiftPremium#616f7fe8 user_id:InputUser currency:string amount:long = InputStorePaymentPurpose`
  @TLObject(id: 0x616f7fe8)
  public struct InputStorePaymentGiftPremium: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var currency: String
    public var amount: Int64
  }

  /// TL: `inputStorePaymentPremiumGiftCode#fb790393 flags:# users:Vector<InputUser> boost_peer:flags.0?InputPeer currency:string amount:long message:flags.1?TextWithEntities = InputStorePaymentPurpose`
  @TLObject(id: 0xfb790393)
  @TLFlagsEquatable
  public struct InputStorePaymentPremiumGiftCode: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var users: [TL.InputUserType]
    @TLConditional("flags", bit: 0) public var boostPeer: TL.InputPeerType? = nil
    public var currency: String
    public var amount: Int64
    @TLConditional("flags", bit: 1) public var message: TL.TextWithEntities? = nil
  }

  /// TL: `inputStorePaymentPremiumGiveaway#160544ca flags:# only_new_subscribers:flags.0?true winners_are_visible:flags.3?true boost_peer:InputPeer additional_peers:flags.1?Vector<InputPeer> countries_iso2:flags.2?Vector<string> prize_description:flags.4?string random_id:long until_date:int currency:string amount:long = InputStorePaymentPurpose`
  @TLObject(id: 0x160544ca)
  @TLFlagsEquatable
  public struct InputStorePaymentPremiumGiveaway: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var onlyNewSubscribers: Bool = false
    @TLConditional("flags", bit: 3) public var winnersAreVisible: Bool = false
    public var boostPeer: TL.InputPeerType
    @TLConditional("flags", bit: 1) public var additionalPeers: [TL.InputPeerType]? = nil
    @TLConditional("flags", bit: 2) public var countriesIso2: [String]? = nil
    @TLConditional("flags", bit: 4) public var prizeDescription: String? = nil
    public var randomId: Int64
    public var untilDate: Int32
    public var currency: String
    public var amount: Int64
  }

  /// TL: `inputStorePaymentStarsTopup#f9a2a6cb flags:# stars:long currency:string amount:long spend_purpose_peer:flags.0?InputPeer = InputStorePaymentPurpose`
  @TLObject(id: 0xf9a2a6cb)
  @TLFlagsEquatable
  public struct InputStorePaymentStarsTopup: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var stars: Int64
    public var currency: String
    public var amount: Int64
    @TLConditional("flags", bit: 0) public var spendPurposePeer: TL.InputPeerType? = nil
  }

  /// TL: `inputStorePaymentStarsGift#1d741ef7 user_id:InputUser stars:long currency:string amount:long = InputStorePaymentPurpose`
  @TLObject(id: 0x1d741ef7)
  public struct InputStorePaymentStarsGift: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var stars: Int64
    public var currency: String
    public var amount: Int64
  }

  /// TL: `inputStorePaymentStarsGiveaway#751f08fa flags:# only_new_subscribers:flags.0?true winners_are_visible:flags.3?true stars:long boost_peer:InputPeer additional_peers:flags.1?Vector<InputPeer> countries_iso2:flags.2?Vector<string> prize_description:flags.4?string random_id:long until_date:int currency:string amount:long users:int = InputStorePaymentPurpose`
  @TLObject(id: 0x751f08fa)
  @TLFlagsEquatable
  public struct InputStorePaymentStarsGiveaway: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var onlyNewSubscribers: Bool = false
    @TLConditional("flags", bit: 3) public var winnersAreVisible: Bool = false
    public var stars: Int64
    public var boostPeer: TL.InputPeerType
    @TLConditional("flags", bit: 1) public var additionalPeers: [TL.InputPeerType]? = nil
    @TLConditional("flags", bit: 2) public var countriesIso2: [String]? = nil
    @TLConditional("flags", bit: 4) public var prizeDescription: String? = nil
    public var randomId: Int64
    public var untilDate: Int32
    public var currency: String
    public var amount: Int64
    public var users: Int32
  }

  /// TL: `inputStorePaymentAuthCode#3fc18057 flags:# restore:flags.0?true phone_number:string phone_code_hash:string premium_days:int currency:string amount:long = InputStorePaymentPurpose`
  @TLObject(id: 0x3fc18057)
  @TLFlagsEquatable
  public struct InputStorePaymentAuthCode: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var restore: Bool = false
    public var phoneNumber: String
    public var phoneCodeHash: String
    public var premiumDays: Int32
    public var currency: String
    public var amount: Int64
  }
}
