// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputCollectible` (2 constructors).
  @TLType
  public indirect enum InputCollectibleType: Equatable, Sendable {
    /// `inputCollectibleUsername#e39460a9 username:string = InputCollectible`
    case inputCollectibleUsername(TL.InputCollectibleUsername)
    /// `inputCollectiblePhone#a2e214a4 phone:string = InputCollectible`
    case inputCollectiblePhone(TL.InputCollectiblePhone)
  }

  /// TL: `inputCollectibleUsername#e39460a9 username:string = InputCollectible`
  @TLObject(id: 0xe39460a9)
  public struct InputCollectibleUsername: Equatable, Sendable {
    public var username: String
  }

  /// TL: `inputCollectiblePhone#a2e214a4 phone:string = InputCollectible`
  @TLObject(id: 0xa2e214a4)
  public struct InputCollectiblePhone: Equatable, Sendable {
    public var phone: String
  }
}
