// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `inputPeerNotifySettings#cacb6ae2 flags:# show_previews:flags.0?Bool silent:flags.1?Bool mute_until:flags.2?int sound:flags.3?NotificationSound stories_muted:flags.6?Bool stories_hide_sender:flags.7?Bool stories_sound:flags.8?NotificationSound = InputPeerNotifySettings`
  @TLObject(id: 0xcacb6ae2)
  @TLFlagsEquatable
  public struct InputPeerNotifySettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var showPreviews: Bool? = nil
    @TLConditional("flags", bit: 1) public var silent: Bool? = nil
    @TLConditional("flags", bit: 2) public var muteUntil: Int32? = nil
    @TLConditional("flags", bit: 3) public var sound: TL.NotificationSoundType? = nil
    @TLConditional("flags", bit: 6) public var storiesMuted: Bool? = nil
    @TLConditional("flags", bit: 7) public var storiesHideSender: Bool? = nil
    @TLConditional("flags", bit: 8) public var storiesSound: TL.NotificationSoundType? = nil
  }
}
