// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `InputSavedStarGift` (3 constructors).
  @TLType
  public indirect enum InputSavedStarGiftType: Equatable, Sendable {
    /// `inputSavedStarGiftUser#69279795 msg_id:int = InputSavedStarGift`
    case inputSavedStarGiftUser(TL.InputSavedStarGiftUser)
    /// `inputSavedStarGiftChat#f101aa7f peer:InputPeer saved_id:long = InputSavedStarGift`
    case inputSavedStarGiftChat(TL.InputSavedStarGiftChat)
    /// `inputSavedStarGiftSlug#2085c238 slug:string = InputSavedStarGift`
    case inputSavedStarGiftSlug(TL.InputSavedStarGiftSlug)
  }

  /// TL: `inputSavedStarGiftUser#69279795 msg_id:int = InputSavedStarGift`
  @TLObject(id: 0x69279795)
  public struct InputSavedStarGiftUser: Equatable, Sendable {
    public var msgId: Int32
  }

  /// TL: `inputSavedStarGiftChat#f101aa7f peer:InputPeer saved_id:long = InputSavedStarGift`
  @TLObject(id: 0xf101aa7f)
  public struct InputSavedStarGiftChat: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var savedId: Int64
  }

  /// TL: `inputSavedStarGiftSlug#2085c238 slug:string = InputSavedStarGift`
  @TLObject(id: 0x2085c238)
  public struct InputSavedStarGiftSlug: Equatable, Sendable {
    public var slug: String
  }
}
