// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `keyboardButton#2f67a72f flags:# style:flags.10?KeyboardButtonStyle text:string type:ButtonType = KeyboardButton`
  @TLObject(id: 0x2f67a72f)
  @TLFlagsEquatable
  public struct KeyboardButton: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 10) public var style: TL.KeyboardButtonStyle? = nil
    public var text: String
    public var type: TL.ButtonTypeType
  }
}
