// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.translatedRichMessage#4203998f result:Vector<RichMessage> = messages.TranslatedRichMessage`
  @TLObject(id: 0x4203998f)
  public struct TranslatedRichMessage: Equatable, Sendable {
    public var result: [TL.RichMessage]
  }
}
