// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.votesList#4899484e flags:# count:int votes:Vector<MessagePeerVote> chats:Vector<Chat> users:Vector<User> next_offset:flags.0?string = messages.VotesList`
  @TLObject(id: 0x4899484e)
  @TLFlagsEquatable
  public struct VotesList: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var count: Int32
    public var votes: [TL.MessagePeerVoteType]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
    @TLConditional("flags", bit: 0) public var nextOffset: String? = nil
  }
}
