// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.preparedInlineMessage#ff57708d query_id:long result:BotInlineResult peer_types:Vector<InlineQueryPeerType> cache_time:int users:Vector<User> = messages.PreparedInlineMessage`
  @TLObject(id: 0xff57708d)
  public struct PreparedInlineMessage: Equatable, Sendable {
    public var queryId: Int64
    public var result: TL.BotInlineResultType
    public var peerTypes: [TL.InlineQueryPeerTypeType]
    public var cacheTime: Int32
    public var users: [TL.UserType]
  }
}
