// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// The TL type `messages.AvailableReactions` (2 constructors).
  @TLType
  public indirect enum AvailableReactionsType: Equatable, Sendable {
    /// `messages.availableReactionsNotModified#9f071957 = messages.AvailableReactions`
    case availableReactionsNotModified(TL.Messages.AvailableReactionsNotModified)
    /// `messages.availableReactions#768e3aad hash:int reactions:Vector<AvailableReaction> = messages.AvailableReactions`
    case availableReactions(TL.Messages.AvailableReactions)
  }

  /// TL: `messages.availableReactionsNotModified#9f071957 = messages.AvailableReactions`
  @TLObject(id: 0x9f071957)
  public struct AvailableReactionsNotModified: Equatable, Sendable {
  }

  /// TL: `messages.availableReactions#768e3aad hash:int reactions:Vector<AvailableReaction> = messages.AvailableReactions`
  @TLObject(id: 0x768e3aad)
  public struct AvailableReactions: Equatable, Sendable {
    public var hash: Int32
    public var reactions: [TL.AvailableReaction]
  }
}
