// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.chatAdminsWithInvites#b69b72d7 admins:Vector<ChatAdminWithInvites> users:Vector<User> = messages.ChatAdminsWithInvites`
  @TLObject(id: 0xb69b72d7)
  public struct ChatAdminsWithInvites: Equatable, Sendable {
    public var admins: [TL.ChatAdminWithInvites]
    public var users: [TL.UserType]
  }
}
