// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// The TL type `messages.ExportedChatInvite` (2 constructors).
  @TLType
  public indirect enum ExportedChatInviteType: Equatable, Sendable {
    /// `messages.exportedChatInvite#1871be50 invite:ExportedChatInvite users:Vector<User> = messages.ExportedChatInvite`
    case exportedChatInvite(TL.Messages.ExportedChatInvite)
    /// `messages.exportedChatInviteReplaced#222600ef invite:ExportedChatInvite new_invite:ExportedChatInvite users:Vector<User> = messages.ExportedChatInvite`
    case exportedChatInviteReplaced(TL.Messages.ExportedChatInviteReplaced)
  }

  /// TL: `messages.exportedChatInvite#1871be50 invite:ExportedChatInvite users:Vector<User> = messages.ExportedChatInvite`
  @TLObject(id: 0x1871be50)
  public struct ExportedChatInvite: Equatable, Sendable {
    public var invite: TL.ExportedChatInviteType
    public var users: [TL.UserType]
  }

  /// TL: `messages.exportedChatInviteReplaced#222600ef invite:ExportedChatInvite new_invite:ExportedChatInvite users:Vector<User> = messages.ExportedChatInvite`
  @TLObject(id: 0x222600ef)
  public struct ExportedChatInviteReplaced: Equatable, Sendable {
    public var invite: TL.ExportedChatInviteType
    public var newInvite: TL.ExportedChatInviteType
    public var users: [TL.UserType]
  }
}
