// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.webPage#fd5e12bd webpage:WebPage chats:Vector<Chat> users:Vector<User> = messages.WebPage`
  @TLObject(id: 0xfd5e12bd)
  public struct WebPage: Equatable, Sendable {
    public var webpage: TL.WebPageType
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
