// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `messageReportOption#7903e3d9 text:string option:bytes = MessageReportOption`
  @TLObject(id: 0x7903e3d9)
  public struct MessageReportOption: Equatable, Sendable {
    public var text: String
    public var option: Data
  }
}
