// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.messageEditData#26b5dde6 flags:# caption:flags.0?true = messages.MessageEditData`
  @TLObject(id: 0x26b5dde6)
  @TLFlagsEquatable
  public struct MessageEditData: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var caption: Bool = false
  }
}
