// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.affectedFoundMessages#ef8d3e6c pts:int pts_count:int offset:int messages:Vector<int> = messages.AffectedFoundMessages`
  @TLObject(id: 0xef8d3e6c)
  public struct AffectedFoundMessages: Equatable, Sendable {
    public var pts: Int32
    public var ptsCount: Int32
    public var offset: Int32
    public var messages: [Int32]
  }
}
