// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// The TL type `messages.Stickers` (2 constructors).
  @TLType
  public indirect enum StickersType: Equatable, Sendable {
    /// `messages.stickersNotModified#f1749a22 = messages.Stickers`
    case stickersNotModified(TL.Messages.StickersNotModified)
    /// `messages.stickers#30a6ec7e hash:long stickers:Vector<Document> = messages.Stickers`
    case stickers(TL.Messages.Stickers)
  }

  /// TL: `messages.stickersNotModified#f1749a22 = messages.Stickers`
  @TLObject(id: 0xf1749a22)
  public struct StickersNotModified: Equatable, Sendable {
  }

  /// TL: `messages.stickers#30a6ec7e hash:long stickers:Vector<Document> = messages.Stickers`
  @TLObject(id: 0x30a6ec7e)
  public struct Stickers: Equatable, Sendable {
    public var hash: Int64
    public var stickers: [TL.DocumentType]
  }
}
