// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.highScores#9a3bfd99 scores:Vector<HighScore> users:Vector<User> = messages.HighScores`
  @TLObject(id: 0x9a3bfd99)
  public struct HighScores: Equatable, Sendable {
    public var scores: [TL.HighScore]
    public var users: [TL.UserType]
  }
}
