// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.affectedHistory#b45c69d1 pts:int pts_count:int offset:int = messages.AffectedHistory`
  @TLObject(id: 0xb45c69d1)
  public struct AffectedHistory: Equatable, Sendable {
    public var pts: Int32
    public var ptsCount: Int32
    public var offset: Int32
  }
}
