// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.webPagePreview#8c9a88ac media:MessageMedia chats:Vector<Chat> users:Vector<User> = messages.WebPagePreview`
  @TLObject(id: 0x8c9a88ac)
  public struct WebPagePreview: Equatable, Sendable {
    public var media: TL.MessageMediaType
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
