// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.myStickers#faff629d count:int sets:Vector<StickerSetCovered> = messages.MyStickers`
  @TLObject(id: 0xfaff629d)
  public struct MyStickers: Equatable, Sendable {
    public var count: Int32
    public var sets: [TL.StickerSetCoveredType]
  }
}
