// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// The TL type `messages.DhConfig` (2 constructors).
  @TLType
  public indirect enum DhConfigType: Equatable, Sendable {
    /// `messages.dhConfigNotModified#c0e24635 random:bytes = messages.DhConfig`
    case dhConfigNotModified(TL.Messages.DhConfigNotModified)
    /// `messages.dhConfig#2c221edd g:int p:bytes version:int random:bytes = messages.DhConfig`
    case dhConfig(TL.Messages.DhConfig)
  }

  /// TL: `messages.dhConfigNotModified#c0e24635 random:bytes = messages.DhConfig`
  @TLObject(id: 0xc0e24635)
  public struct DhConfigNotModified: Equatable, Sendable {
    public var random: Data
  }

  /// TL: `messages.dhConfig#2c221edd g:int p:bytes version:int random:bytes = messages.DhConfig`
  @TLObject(id: 0x2c221edd)
  public struct DhConfig: Equatable, Sendable {
    public var g: Int32
    public var p: Data
    public var version: Int32
    public var random: Data
  }
}
