// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.messageViews#b6c4f543 views:Vector<MessageViews> chats:Vector<Chat> users:Vector<User> = messages.MessageViews`
  @TLObject(id: 0xb6c4f543)
  public struct MessageViews: Equatable, Sendable {
    public var views: [TL.MessageViews]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
