// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `myBoost#c448415c flags:# slot:int peer:flags.0?Peer date:int expires:int cooldown_until_date:flags.1?int = MyBoost`
  @TLObject(id: 0xc448415c)
  @TLFlagsEquatable
  public struct MyBoost: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var slot: Int32
    @TLConditional("flags", bit: 0) public var peer: TL.PeerType? = nil
    public var date: Int32
    public var expires: Int32
    @TLConditional("flags", bit: 1) public var cooldownUntilDate: Int32? = nil
  }
}
