// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `PageListOrderedItem` (2 constructors).
  @TLType
  public indirect enum PageListOrderedItemType: Equatable, Sendable {
    /// `pageListOrderedItemText#15031189 flags:# checkbox:flags.0?true checked:flags.1?true num:flags.2?string text:RichText value:flags.3?int type:flags.4?string = PageListOrderedItem`
    case pageListOrderedItemText(TL.PageListOrderedItemText)
    /// `pageListOrderedItemBlocks#8ff2d5f0 flags:# checkbox:flags.0?true checked:flags.1?true num:flags.2?string blocks:Vector<PageBlock> value:flags.3?int type:flags.4?string = PageListOrderedItem`
    case pageListOrderedItemBlocks(TL.PageListOrderedItemBlocks)
  }

  /// TL: `pageListOrderedItemText#15031189 flags:# checkbox:flags.0?true checked:flags.1?true num:flags.2?string text:RichText value:flags.3?int type:flags.4?string = PageListOrderedItem`
  @TLObject(id: 0x15031189)
  @TLFlagsEquatable
  public struct PageListOrderedItemText: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var checkbox: Bool = false
    @TLConditional("flags", bit: 1) public var checked: Bool = false
    @TLConditional("flags", bit: 2) public var num: String? = nil
    public var text: TL.RichTextType
    @TLConditional("flags", bit: 3) public var value: Int32? = nil
    @TLConditional("flags", bit: 4) public var type: String? = nil
  }

  /// TL: `pageListOrderedItemBlocks#8ff2d5f0 flags:# checkbox:flags.0?true checked:flags.1?true num:flags.2?string blocks:Vector<PageBlock> value:flags.3?int type:flags.4?string = PageListOrderedItem`
  @TLObject(id: 0x8ff2d5f0)
  @TLFlagsEquatable
  public struct PageListOrderedItemBlocks: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var checkbox: Bool = false
    @TLConditional("flags", bit: 1) public var checked: Bool = false
    @TLConditional("flags", bit: 2) public var num: String? = nil
    public var blocks: [TL.PageBlockType]
    @TLConditional("flags", bit: 3) public var value: Int32? = nil
    @TLConditional("flags", bit: 4) public var type: String? = nil
  }
}
