// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.starGiftAuctionState#6b39f4ec gift:StarGift state:StarGiftAuctionState user_state:StarGiftAuctionUserState timeout:int users:Vector<User> chats:Vector<Chat> = payments.StarGiftAuctionState`
  @TLObject(id: 0x6b39f4ec)
  public struct StarGiftAuctionState: Equatable, Sendable {
    public var gift: TL.StarGiftType
    public var state: TL.StarGiftAuctionStateType
    public var userState: TL.StarGiftAuctionUserState
    public var timeout: Int32
    public var users: [TL.UserType]
    public var chats: [TL.ChatType]
  }
}
