// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// The TL type `payments.PaymentForm` (3 constructors).
  @TLType
  public indirect enum PaymentFormType: Equatable, Sendable {
    /// `payments.paymentForm#a0058751 flags:# can_save_credentials:flags.2?true password_missing:flags.3?true form_id:long bot_id:long title:string description:string photo:flags.5?WebDocument invoice:Invoice provider_id:long url:string native_provider:flags.4?string native_params:flags.4?DataJSON additional_methods:flags.6?Vector<PaymentFormMethod> saved_info:flags.0?PaymentRequestedInfo saved_credentials:flags.1?Vector<PaymentSavedCredentials> users:Vector<User> = payments.PaymentForm`
    case paymentForm(TL.Payments.PaymentForm)
    /// `payments.paymentFormStars#7bf6b15c flags:# form_id:long bot_id:long title:string description:string photo:flags.5?WebDocument invoice:Invoice users:Vector<User> = payments.PaymentForm`
    case paymentFormStars(TL.Payments.PaymentFormStars)
    /// `payments.paymentFormStarGift#b425cfe1 form_id:long invoice:Invoice = payments.PaymentForm`
    case paymentFormStarGift(TL.Payments.PaymentFormStarGift)
  }

  /// TL: `payments.paymentForm#a0058751 flags:# can_save_credentials:flags.2?true password_missing:flags.3?true form_id:long bot_id:long title:string description:string photo:flags.5?WebDocument invoice:Invoice provider_id:long url:string native_provider:flags.4?string native_params:flags.4?DataJSON additional_methods:flags.6?Vector<PaymentFormMethod> saved_info:flags.0?PaymentRequestedInfo saved_credentials:flags.1?Vector<PaymentSavedCredentials> users:Vector<User> = payments.PaymentForm`
  @TLObject(id: 0xa0058751)
  @TLFlagsEquatable
  public struct PaymentForm: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var canSaveCredentials: Bool = false
    @TLConditional("flags", bit: 3) public var passwordMissing: Bool = false
    public var formId: Int64
    public var botId: Int64
    public var title: String
    public var description: String
    @TLConditional("flags", bit: 5) public var photo: TL.WebDocumentType? = nil
    public var invoice: TL.Invoice
    public var providerId: Int64
    public var url: String
    @TLConditional("flags", bit: 4) public var nativeProvider: String? = nil
    @TLConditional("flags", bit: 4) public var nativeParams: TL.DataJSON? = nil
    @TLConditional("flags", bit: 6) public var additionalMethods: [TL.PaymentFormMethod]? = nil
    @TLConditional("flags", bit: 0) public var savedInfo: TL.PaymentRequestedInfo? = nil
    @TLConditional("flags", bit: 1) public var savedCredentials: [TL.PaymentSavedCredentialsCard]? = nil
    public var users: [TL.UserType]
  }

  /// TL: `payments.paymentFormStars#7bf6b15c flags:# form_id:long bot_id:long title:string description:string photo:flags.5?WebDocument invoice:Invoice users:Vector<User> = payments.PaymentForm`
  @TLObject(id: 0x7bf6b15c)
  @TLFlagsEquatable
  public struct PaymentFormStars: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var formId: Int64
    public var botId: Int64
    public var title: String
    public var description: String
    @TLConditional("flags", bit: 5) public var photo: TL.WebDocumentType? = nil
    public var invoice: TL.Invoice
    public var users: [TL.UserType]
  }

  /// TL: `payments.paymentFormStarGift#b425cfe1 form_id:long invoice:Invoice = payments.PaymentForm`
  @TLObject(id: 0xb425cfe1)
  public struct PaymentFormStarGift: Equatable, Sendable {
    public var formId: Int64
    public var invoice: TL.Invoice
  }
}
