// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.checkedGiftCode#eb983f8f flags:# via_giveaway:flags.2?true from_id:flags.4?Peer giveaway_msg_id:flags.3?int to_id:flags.0?long date:int days:int used_date:flags.1?int chats:Vector<Chat> users:Vector<User> = payments.CheckedGiftCode`
  @TLObject(id: 0xeb983f8f)
  @TLFlagsEquatable
  public struct CheckedGiftCode: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var viaGiveaway: Bool = false
    @TLConditional("flags", bit: 4) public var fromId: TL.PeerType? = nil
    @TLConditional("flags", bit: 3) public var giveawayMsgId: Int32? = nil
    @TLConditional("flags", bit: 0) public var toId: Int64? = nil
    public var date: Int32
    public var days: Int32
    @TLConditional("flags", bit: 1) public var usedDate: Int32? = nil
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
