// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.starGiftUpgradePreview#3de1dfed sample_attributes:Vector<StarGiftAttribute> prices:Vector<StarGiftUpgradePrice> next_prices:Vector<StarGiftUpgradePrice> = payments.StarGiftUpgradePreview`
  @TLObject(id: 0x3de1dfed)
  public struct StarGiftUpgradePreview: Equatable, Sendable {
    public var sampleAttributes: [TL.StarGiftAttributeType]
    public var prices: [TL.StarGiftUpgradePrice]
    public var nextPrices: [TL.StarGiftUpgradePrice]
  }
}
