// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// The TL type `payments.PaymentReceipt` (2 constructors).
  @TLType
  public indirect enum PaymentReceiptType: Equatable, Sendable {
    /// `payments.paymentReceipt#70c4fe03 flags:# date:int bot_id:long provider_id:long title:string description:string photo:flags.2?WebDocument invoice:Invoice info:flags.0?PaymentRequestedInfo shipping:flags.1?ShippingOption tip_amount:flags.3?long currency:string total_amount:long credentials_title:string users:Vector<User> = payments.PaymentReceipt`
    case paymentReceipt(TL.Payments.PaymentReceipt)
    /// `payments.paymentReceiptStars#dabbf83a flags:# date:int bot_id:long title:string description:string photo:flags.2?WebDocument invoice:Invoice currency:string total_amount:long transaction_id:string users:Vector<User> = payments.PaymentReceipt`
    case paymentReceiptStars(TL.Payments.PaymentReceiptStars)
  }

  /// TL: `payments.paymentReceipt#70c4fe03 flags:# date:int bot_id:long provider_id:long title:string description:string photo:flags.2?WebDocument invoice:Invoice info:flags.0?PaymentRequestedInfo shipping:flags.1?ShippingOption tip_amount:flags.3?long currency:string total_amount:long credentials_title:string users:Vector<User> = payments.PaymentReceipt`
  @TLObject(id: 0x70c4fe03)
  @TLFlagsEquatable
  public struct PaymentReceipt: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var date: Int32
    public var botId: Int64
    public var providerId: Int64
    public var title: String
    public var description: String
    @TLConditional("flags", bit: 2) public var photo: TL.WebDocumentType? = nil
    public var invoice: TL.Invoice
    @TLConditional("flags", bit: 0) public var info: TL.PaymentRequestedInfo? = nil
    @TLConditional("flags", bit: 1) public var shipping: TL.ShippingOption? = nil
    @TLConditional("flags", bit: 3) public var tipAmount: Int64? = nil
    public var currency: String
    public var totalAmount: Int64
    public var credentialsTitle: String
    public var users: [TL.UserType]
  }

  /// TL: `payments.paymentReceiptStars#dabbf83a flags:# date:int bot_id:long title:string description:string photo:flags.2?WebDocument invoice:Invoice currency:string total_amount:long transaction_id:string users:Vector<User> = payments.PaymentReceipt`
  @TLObject(id: 0xdabbf83a)
  @TLFlagsEquatable
  public struct PaymentReceiptStars: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var date: Int32
    public var botId: Int64
    public var title: String
    public var description: String
    @TLConditional("flags", bit: 2) public var photo: TL.WebDocumentType? = nil
    public var invoice: TL.Invoice
    public var currency: String
    public var totalAmount: Int64
    public var transactionId: String
    public var users: [TL.UserType]
  }
}
