// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.connectedStarRefBots#98d5ea1d count:int connected_bots:Vector<ConnectedBotStarRef> users:Vector<User> = payments.ConnectedStarRefBots`
  @TLObject(id: 0x98d5ea1d)
  public struct ConnectedStarRefBots: Equatable, Sendable {
    public var count: Int32
    public var connectedBots: [TL.ConnectedBotStarRef]
    public var users: [TL.UserType]
  }
}
