// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.resaleStarGifts#947a12df flags:# count:int gifts:Vector<StarGift> next_offset:flags.0?string attributes:flags.1?Vector<StarGiftAttribute> attributes_hash:flags.1?long chats:Vector<Chat> counters:flags.2?Vector<StarGiftAttributeCounter> users:Vector<User> = payments.ResaleStarGifts`
  @TLObject(id: 0x947a12df)
  @TLFlagsEquatable
  public struct ResaleStarGifts: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var count: Int32
    public var gifts: [TL.StarGiftType]
    @TLConditional("flags", bit: 0) public var nextOffset: String? = nil
    @TLConditional("flags", bit: 1) public var attributes: [TL.StarGiftAttributeType]? = nil
    @TLConditional("flags", bit: 1) public var attributesHash: Int64? = nil
    public var chats: [TL.ChatType]
    @TLConditional("flags", bit: 2) public var counters: [TL.StarGiftAttributeCounter]? = nil
    public var users: [TL.UserType]
  }
}
