// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.uniqueStarGiftValueInfo#512fe446 flags:# last_sale_on_fragment:flags.1?true value_is_average:flags.6?true currency:string value:long initial_sale_date:int initial_sale_stars:long initial_sale_price:long last_sale_date:flags.0?int last_sale_price:flags.0?long floor_price:flags.2?long average_price:flags.3?long listed_count:flags.4?int fragment_listed_count:flags.5?int fragment_listed_url:flags.5?string = payments.UniqueStarGiftValueInfo`
  @TLObject(id: 0x512fe446)
  @TLFlagsEquatable
  public struct UniqueStarGiftValueInfo: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var lastSaleOnFragment: Bool = false
    @TLConditional("flags", bit: 6) public var valueIsAverage: Bool = false
    public var currency: String
    public var value: Int64
    public var initialSaleDate: Int32
    public var initialSaleStars: Int64
    public var initialSalePrice: Int64
    @TLConditional("flags", bit: 0) public var lastSaleDate: Int32? = nil
    @TLConditional("flags", bit: 0) public var lastSalePrice: Int64? = nil
    @TLConditional("flags", bit: 2) public var floorPrice: Int64? = nil
    @TLConditional("flags", bit: 3) public var averagePrice: Int64? = nil
    @TLConditional("flags", bit: 4) public var listedCount: Int32? = nil
    @TLConditional("flags", bit: 5) public var fragmentListedCount: Int32? = nil
    @TLConditional("flags", bit: 5) public var fragmentListedUrl: String? = nil
  }
}
