// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.uniqueStarGift#416c56e8 gift:StarGift chats:Vector<Chat> users:Vector<User> = payments.UniqueStarGift`
  @TLObject(id: 0x416c56e8)
  public struct UniqueStarGift: Equatable, Sendable {
    public var gift: TL.StarGiftType
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
