// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.groupCallStars#9d1dbd26 total_stars:long top_donors:Vector<GroupCallDonor> chats:Vector<Chat> users:Vector<User> = phone.GroupCallStars`
  @TLObject(id: 0x9d1dbd26)
  public struct GroupCallStars: Equatable, Sendable {
    public var totalStars: Int64
    public var topDonors: [TL.GroupCallDonor]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
