// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `pollAnswerVoters#3645230a flags:# chosen:flags.0?true correct:flags.1?true option:bytes voters:flags.2?int recent_voters:flags.2?Vector<Peer> = PollAnswerVoters`
  @TLObject(id: 0x3645230a)
  @TLFlagsEquatable
  public struct PollAnswerVoters: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var chosen: Bool = false
    @TLConditional("flags", bit: 1) public var correct: Bool = false
    public var option: Data
    @TLConditional("flags", bit: 2) public var voters: Int32? = nil
    @TLConditional("flags", bit: 2) public var recentVoters: [TL.PeerType]? = nil
  }
}
