// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `pollResults#ba7bb15e flags:# min:flags.0?true has_unread_votes:flags.6?true can_view_stats:flags.7?true results:flags.1?Vector<PollAnswerVoters> total_voters:flags.2?int recent_voters:flags.3?Vector<Peer> solution:flags.4?string solution_entities:flags.4?Vector<MessageEntity> solution_media:flags.5?MessageMedia = PollResults`
  @TLObject(id: 0xba7bb15e)
  @TLFlagsEquatable
  public struct PollResults: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var min: Bool = false
    @TLConditional("flags", bit: 6) public var hasUnreadVotes: Bool = false
    @TLConditional("flags", bit: 7) public var canViewStats: Bool = false
    @TLConditional("flags", bit: 1) public var results: [TL.PollAnswerVoters]? = nil
    @TLConditional("flags", bit: 2) public var totalVoters: Int32? = nil
    @TLConditional("flags", bit: 3) public var recentVoters: [TL.PeerType]? = nil
    @TLConditional("flags", bit: 4) public var solution: String? = nil
    @TLConditional("flags", bit: 4) public var solutionEntities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 5) public var solutionMedia: TL.MessageMediaType? = nil
  }
}
