// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Premium {

  /// TL: `premium.myBoosts#9ae228e2 my_boosts:Vector<MyBoost> chats:Vector<Chat> users:Vector<User> = premium.MyBoosts`
  @TLObject(id: 0x9ae228e2)
  public struct MyBoosts: Equatable, Sendable {
    public var myBoosts: [TL.MyBoost]
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
