// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Premium {

  /// TL: `premium.boostsStatus#4959427a flags:# my_boost:flags.2?true level:int current_level_boosts:int boosts:int gift_boosts:flags.4?int next_level_boosts:flags.0?int premium_audience:flags.1?StatsPercentValue boost_url:string prepaid_giveaways:flags.3?Vector<PrepaidGiveaway> my_boost_slots:flags.2?Vector<int> = premium.BoostsStatus`
  @TLObject(id: 0x4959427a)
  @TLFlagsEquatable
  public struct BoostsStatus: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var myBoost: Bool = false
    public var level: Int32
    public var currentLevelBoosts: Int32
    public var boosts: Int32
    @TLConditional("flags", bit: 4) public var giftBoosts: Int32? = nil
    @TLConditional("flags", bit: 0) public var nextLevelBoosts: Int32? = nil
    @TLConditional("flags", bit: 1) public var premiumAudience: TL.StatsPercentValue? = nil
    public var boostUrl: String
    @TLConditional("flags", bit: 3) public var prepaidGiveaways: [TL.PrepaidGiveawayType]? = nil
    @TLConditional("flags", bit: 2) public var myBoostSlots: [Int32]? = nil
  }
}
