// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `ProfileTab` (8 constructors).
  @TLType
  public indirect enum ProfileTabType: Equatable, Sendable {
    /// `profileTabPosts#b98cd696 = ProfileTab`
    case profileTabPosts(TL.ProfileTabPosts)
    /// `profileTabGifts#4d4bd46a = ProfileTab`
    case profileTabGifts(TL.ProfileTabGifts)
    /// `profileTabMedia#72c64955 = ProfileTab`
    case profileTabMedia(TL.ProfileTabMedia)
    /// `profileTabFiles#ab339c00 = ProfileTab`
    case profileTabFiles(TL.ProfileTabFiles)
    /// `profileTabMusic#9f27d26e = ProfileTab`
    case profileTabMusic(TL.ProfileTabMusic)
    /// `profileTabVoice#e477092e = ProfileTab`
    case profileTabVoice(TL.ProfileTabVoice)
    /// `profileTabLinks#d3656499 = ProfileTab`
    case profileTabLinks(TL.ProfileTabLinks)
    /// `profileTabGifs#a2c0f695 = ProfileTab`
    case profileTabGifs(TL.ProfileTabGifs)
  }

  /// TL: `profileTabPosts#b98cd696 = ProfileTab`
  @TLObject(id: 0xb98cd696)
  public struct ProfileTabPosts: Equatable, Sendable {
  }

  /// TL: `profileTabGifts#4d4bd46a = ProfileTab`
  @TLObject(id: 0x4d4bd46a)
  public struct ProfileTabGifts: Equatable, Sendable {
  }

  /// TL: `profileTabMedia#72c64955 = ProfileTab`
  @TLObject(id: 0x72c64955)
  public struct ProfileTabMedia: Equatable, Sendable {
  }

  /// TL: `profileTabFiles#ab339c00 = ProfileTab`
  @TLObject(id: 0xab339c00)
  public struct ProfileTabFiles: Equatable, Sendable {
  }

  /// TL: `profileTabMusic#9f27d26e = ProfileTab`
  @TLObject(id: 0x9f27d26e)
  public struct ProfileTabMusic: Equatable, Sendable {
  }

  /// TL: `profileTabVoice#e477092e = ProfileTab`
  @TLObject(id: 0xe477092e)
  public struct ProfileTabVoice: Equatable, Sendable {
  }

  /// TL: `profileTabLinks#d3656499 = ProfileTab`
  @TLObject(id: 0xd3656499)
  public struct ProfileTabLinks: Equatable, Sendable {
  }

  /// TL: `profileTabGifs#a2c0f695 = ProfileTab`
  @TLObject(id: 0xa2c0f695)
  public struct ProfileTabGifs: Equatable, Sendable {
  }
}
