// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `receivedNotifyMessage#a384b779 id:int flags:int = ReceivedNotifyMessage`
  @TLObject(id: 0xa384b779)
  public struct ReceivedNotifyMessage: Equatable, Sendable {
    public var id: Int32
    public var flags: Int32
  }
}
