// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `RichText` (31 constructors).
  @TLType
  public indirect enum RichTextType: Equatable, Sendable {
    /// `textEmpty#dc3d824f = RichText`
    case textEmpty(TL.TextEmpty)
    /// `textPlain#744694e0 text:string = RichText`
    case textPlain(TL.TextPlain)
    /// `textBold#6724abc4 text:RichText = RichText`
    case textBold(TL.TextBold)
    /// `textItalic#d912a59c text:RichText = RichText`
    case textItalic(TL.TextItalic)
    /// `textUnderline#c12622c4 text:RichText = RichText`
    case textUnderline(TL.TextUnderline)
    /// `textStrike#9bf8bb95 text:RichText = RichText`
    case textStrike(TL.TextStrike)
    /// `textFixed#6c3f19b9 text:RichText = RichText`
    case textFixed(TL.TextFixed)
    /// `textUrl#3c2884c1 text:RichText url:string webpage_id:long = RichText`
    case textUrl(TL.TextUrl)
    /// `textEmail#de5a0dd6 text:RichText email:string = RichText`
    case textEmail(TL.TextEmail)
    /// `textConcat#7e6260d7 texts:Vector<RichText> = RichText`
    case textConcat(TL.TextConcat)
    /// `textSubscript#ed6a8504 text:RichText = RichText`
    case textSubscript(TL.TextSubscript)
    /// `textSuperscript#c7fb5e01 text:RichText = RichText`
    case textSuperscript(TL.TextSuperscript)
    /// `textMarked#034b8621 text:RichText = RichText`
    case textMarked(TL.TextMarked)
    /// `textPhone#1ccb966a text:RichText phone:string = RichText`
    case textPhone(TL.TextPhone)
    /// `textImage#081ccf4f document_id:long w:int h:int = RichText`
    case textImage(TL.TextImage)
    /// `textAnchor#35553762 text:RichText name:string = RichText`
    case textAnchor(TL.TextAnchor)
    /// `textMath#9d2eac97 source:string = RichText`
    case textMath(TL.TextMath)
    /// `textCustomEmoji#a26156c0 document_id:long alt:string = RichText`
    case textCustomEmoji(TL.TextCustomEmoji)
    /// `textSpoiler#4c2a5d62 text:RichText = RichText`
    case textSpoiler(TL.TextSpoiler)
    /// `textMention#cd24cf44 text:RichText = RichText`
    case textMention(TL.TextMention)
    /// `textHashtag#519524ea text:RichText = RichText`
    case textHashtag(TL.TextHashtag)
    /// `textBotCommand#02ff29d3 text:RichText = RichText`
    case textBotCommand(TL.TextBotCommand)
    /// `textCashtag#7b9e1801 text:RichText = RichText`
    case textCashtag(TL.TextCashtag)
    /// `textAutoUrl#ac6a83aa text:RichText = RichText`
    case textAutoUrl(TL.TextAutoUrl)
    /// `textAutoEmail#c556a45d text:RichText = RichText`
    case textAutoEmail(TL.TextAutoEmail)
    /// `textAutoPhone#24c26789 text:RichText = RichText`
    case textAutoPhone(TL.TextAutoPhone)
    /// `textBankCard#b956812d text:RichText = RichText`
    case textBankCard(TL.TextBankCard)
    /// `textMentionName#01a9fbfc text:RichText user_id:long = RichText`
    case textMentionName(TL.TextMentionName)
    /// `textDate#a5b45e2b flags:# relative:flags.0?true short_time:flags.1?true long_time:flags.2?true short_date:flags.3?true long_date:flags.4?true day_of_week:flags.5?true text:RichText date:int = RichText`
    case textDate(TL.TextDate)
    /// `textDiff#9686cb50 text:RichText old_text:RichText = RichText`
    case textDiff(TL.TextDiff)
    /// `textButton#afc79cd6 flags:# text:RichText type:InlineButtonType style:flags.0?RichButtonStyle = RichText`
    case textButton(TL.TextButton)
  }

  /// TL: `textEmpty#dc3d824f = RichText`
  @TLObject(id: 0xdc3d824f)
  public struct TextEmpty: Equatable, Sendable {
  }

  /// TL: `textPlain#744694e0 text:string = RichText`
  @TLObject(id: 0x744694e0)
  public struct TextPlain: Equatable, Sendable {
    public var text: String
  }

  /// TL: `textBold#6724abc4 text:RichText = RichText`
  @TLObject(id: 0x6724abc4)
  public struct TextBold: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textItalic#d912a59c text:RichText = RichText`
  @TLObject(id: 0xd912a59c)
  public struct TextItalic: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textUnderline#c12622c4 text:RichText = RichText`
  @TLObject(id: 0xc12622c4)
  public struct TextUnderline: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textStrike#9bf8bb95 text:RichText = RichText`
  @TLObject(id: 0x9bf8bb95)
  public struct TextStrike: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textFixed#6c3f19b9 text:RichText = RichText`
  @TLObject(id: 0x6c3f19b9)
  public struct TextFixed: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textUrl#3c2884c1 text:RichText url:string webpage_id:long = RichText`
  @TLObject(id: 0x3c2884c1)
  public struct TextUrl: Equatable, Sendable {
    public var text: TL.RichTextType
    public var url: String
    public var webpageId: Int64
  }

  /// TL: `textEmail#de5a0dd6 text:RichText email:string = RichText`
  @TLObject(id: 0xde5a0dd6)
  public struct TextEmail: Equatable, Sendable {
    public var text: TL.RichTextType
    public var email: String
  }

  /// TL: `textConcat#7e6260d7 texts:Vector<RichText> = RichText`
  @TLObject(id: 0x7e6260d7)
  public struct TextConcat: Equatable, Sendable {
    public var texts: [TL.RichTextType]
  }

  /// TL: `textSubscript#ed6a8504 text:RichText = RichText`
  @TLObject(id: 0xed6a8504)
  public struct TextSubscript: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textSuperscript#c7fb5e01 text:RichText = RichText`
  @TLObject(id: 0xc7fb5e01)
  public struct TextSuperscript: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textMarked#034b8621 text:RichText = RichText`
  @TLObject(id: 0x034b8621)
  public struct TextMarked: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textPhone#1ccb966a text:RichText phone:string = RichText`
  @TLObject(id: 0x1ccb966a)
  public struct TextPhone: Equatable, Sendable {
    public var text: TL.RichTextType
    public var phone: String
  }

  /// TL: `textImage#081ccf4f document_id:long w:int h:int = RichText`
  @TLObject(id: 0x081ccf4f)
  public struct TextImage: Equatable, Sendable {
    public var documentId: Int64
    public var w: Int32
    public var h: Int32
  }

  /// TL: `textAnchor#35553762 text:RichText name:string = RichText`
  @TLObject(id: 0x35553762)
  public struct TextAnchor: Equatable, Sendable {
    public var text: TL.RichTextType
    public var name: String
  }

  /// TL: `textMath#9d2eac97 source:string = RichText`
  @TLObject(id: 0x9d2eac97)
  public struct TextMath: Equatable, Sendable {
    public var source: String
  }

  /// TL: `textCustomEmoji#a26156c0 document_id:long alt:string = RichText`
  @TLObject(id: 0xa26156c0)
  public struct TextCustomEmoji: Equatable, Sendable {
    public var documentId: Int64
    public var alt: String
  }

  /// TL: `textSpoiler#4c2a5d62 text:RichText = RichText`
  @TLObject(id: 0x4c2a5d62)
  public struct TextSpoiler: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textMention#cd24cf44 text:RichText = RichText`
  @TLObject(id: 0xcd24cf44)
  public struct TextMention: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textHashtag#519524ea text:RichText = RichText`
  @TLObject(id: 0x519524ea)
  public struct TextHashtag: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textBotCommand#02ff29d3 text:RichText = RichText`
  @TLObject(id: 0x02ff29d3)
  public struct TextBotCommand: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textCashtag#7b9e1801 text:RichText = RichText`
  @TLObject(id: 0x7b9e1801)
  public struct TextCashtag: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textAutoUrl#ac6a83aa text:RichText = RichText`
  @TLObject(id: 0xac6a83aa)
  public struct TextAutoUrl: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textAutoEmail#c556a45d text:RichText = RichText`
  @TLObject(id: 0xc556a45d)
  public struct TextAutoEmail: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textAutoPhone#24c26789 text:RichText = RichText`
  @TLObject(id: 0x24c26789)
  public struct TextAutoPhone: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textBankCard#b956812d text:RichText = RichText`
  @TLObject(id: 0xb956812d)
  public struct TextBankCard: Equatable, Sendable {
    public var text: TL.RichTextType
  }

  /// TL: `textMentionName#01a9fbfc text:RichText user_id:long = RichText`
  @TLObject(id: 0x01a9fbfc)
  public struct TextMentionName: Equatable, Sendable {
    public var text: TL.RichTextType
    public var userId: Int64
  }

  /// TL: `textDate#a5b45e2b flags:# relative:flags.0?true short_time:flags.1?true long_time:flags.2?true short_date:flags.3?true long_date:flags.4?true day_of_week:flags.5?true text:RichText date:int = RichText`
  @TLObject(id: 0xa5b45e2b)
  @TLFlagsEquatable
  public struct TextDate: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var relative: Bool = false
    @TLConditional("flags", bit: 1) public var shortTime: Bool = false
    @TLConditional("flags", bit: 2) public var longTime: Bool = false
    @TLConditional("flags", bit: 3) public var shortDate: Bool = false
    @TLConditional("flags", bit: 4) public var longDate: Bool = false
    @TLConditional("flags", bit: 5) public var dayOfWeek: Bool = false
    public var text: TL.RichTextType
    public var date: Int32
  }

  /// TL: `textDiff#9686cb50 text:RichText old_text:RichText = RichText`
  @TLObject(id: 0x9686cb50)
  public struct TextDiff: Equatable, Sendable {
    public var text: TL.RichTextType
    public var oldText: TL.RichTextType
  }

  /// TL: `textButton#afc79cd6 flags:# text:RichText type:InlineButtonType style:flags.0?RichButtonStyle = RichText`
  @TLObject(id: 0xafc79cd6)
  @TLFlagsEquatable
  public struct TextButton: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var text: TL.RichTextType
    public var type: TL.InlineButtonTypeType
    @TLConditional("flags", bit: 0) public var style: TL.RichButtonStyle? = nil
  }
}
