// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `richButtonStyle#03c610bd flags:# bg_primary:flags.0?true bg_danger:flags.1?true bg_success:flags.2?true link:flags.3?true = RichButtonStyle`
  @TLObject(id: 0x03c610bd)
  @TLFlagsEquatable
  public struct RichButtonStyle: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var bgPrimary: Bool = false
    @TLConditional("flags", bit: 1) public var bgDanger: Bool = false
    @TLConditional("flags", bit: 2) public var bgSuccess: Bool = false
    @TLConditional("flags", bit: 3) public var link: Bool = false
  }
}
