// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `searchResultPosition#7f648b67 msg_id:int date:int offset:int = SearchResultsPosition`
  @TLObject(id: 0x7f648b67)
  public struct SearchResultPosition: Equatable, Sendable {
    public var msgId: Int32
    public var date: Int32
    public var offset: Int32
  }
}
