// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `searchResultsCalendarPeriod#c9b0539f date:int min_msg_id:int max_msg_id:int count:int = SearchResultsCalendarPeriod`
  @TLObject(id: 0xc9b0539f)
  public struct SearchResultsCalendarPeriod: Equatable, Sendable {
    public var date: Int32
    public var minMsgId: Int32
    public var maxMsgId: Int32
    public var count: Int32
  }
}
