// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `SecureValueError` (9 constructors).
  @TLType
  public indirect enum SecureValueErrorType: Equatable, Sendable {
    /// `secureValueErrorData#e8a40bd9 type:SecureValueType data_hash:bytes field:string text:string = SecureValueError`
    case secureValueErrorData(TL.SecureValueErrorData)
    /// `secureValueErrorFrontSide#00be3dfa type:SecureValueType file_hash:bytes text:string = SecureValueError`
    case secureValueErrorFrontSide(TL.SecureValueErrorFrontSide)
    /// `secureValueErrorReverseSide#868a2aa5 type:SecureValueType file_hash:bytes text:string = SecureValueError`
    case secureValueErrorReverseSide(TL.SecureValueErrorReverseSide)
    /// `secureValueErrorSelfie#e537ced6 type:SecureValueType file_hash:bytes text:string = SecureValueError`
    case secureValueErrorSelfie(TL.SecureValueErrorSelfie)
    /// `secureValueErrorFile#7a700873 type:SecureValueType file_hash:bytes text:string = SecureValueError`
    case secureValueErrorFile(TL.SecureValueErrorFile)
    /// `secureValueErrorFiles#666220e9 type:SecureValueType file_hash:Vector<bytes> text:string = SecureValueError`
    case secureValueErrorFiles(TL.SecureValueErrorFiles)
    /// `secureValueError#869d758f type:SecureValueType hash:bytes text:string = SecureValueError`
    case secureValueError(TL.SecureValueError)
    /// `secureValueErrorTranslationFile#a1144770 type:SecureValueType file_hash:bytes text:string = SecureValueError`
    case secureValueErrorTranslationFile(TL.SecureValueErrorTranslationFile)
    /// `secureValueErrorTranslationFiles#34636dd8 type:SecureValueType file_hash:Vector<bytes> text:string = SecureValueError`
    case secureValueErrorTranslationFiles(TL.SecureValueErrorTranslationFiles)
  }

  /// TL: `secureValueErrorData#e8a40bd9 type:SecureValueType data_hash:bytes field:string text:string = SecureValueError`
  @TLObject(id: 0xe8a40bd9)
  public struct SecureValueErrorData: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var dataHash: Data
    public var field: String
    public var text: String
  }

  /// TL: `secureValueErrorFrontSide#00be3dfa type:SecureValueType file_hash:bytes text:string = SecureValueError`
  @TLObject(id: 0x00be3dfa)
  public struct SecureValueErrorFrontSide: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: Data
    public var text: String
  }

  /// TL: `secureValueErrorReverseSide#868a2aa5 type:SecureValueType file_hash:bytes text:string = SecureValueError`
  @TLObject(id: 0x868a2aa5)
  public struct SecureValueErrorReverseSide: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: Data
    public var text: String
  }

  /// TL: `secureValueErrorSelfie#e537ced6 type:SecureValueType file_hash:bytes text:string = SecureValueError`
  @TLObject(id: 0xe537ced6)
  public struct SecureValueErrorSelfie: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: Data
    public var text: String
  }

  /// TL: `secureValueErrorFile#7a700873 type:SecureValueType file_hash:bytes text:string = SecureValueError`
  @TLObject(id: 0x7a700873)
  public struct SecureValueErrorFile: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: Data
    public var text: String
  }

  /// TL: `secureValueErrorFiles#666220e9 type:SecureValueType file_hash:Vector<bytes> text:string = SecureValueError`
  @TLObject(id: 0x666220e9)
  public struct SecureValueErrorFiles: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: [Data]
    public var text: String
  }

  /// TL: `secureValueError#869d758f type:SecureValueType hash:bytes text:string = SecureValueError`
  @TLObject(id: 0x869d758f)
  public struct SecureValueError: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var hash: Data
    public var text: String
  }

  /// TL: `secureValueErrorTranslationFile#a1144770 type:SecureValueType file_hash:bytes text:string = SecureValueError`
  @TLObject(id: 0xa1144770)
  public struct SecureValueErrorTranslationFile: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: Data
    public var text: String
  }

  /// TL: `secureValueErrorTranslationFiles#34636dd8 type:SecureValueType file_hash:Vector<bytes> text:string = SecureValueError`
  @TLObject(id: 0x34636dd8)
  public struct SecureValueErrorTranslationFiles: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var fileHash: [Data]
    public var text: String
  }
}
