// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `secureSecretSettings#1527bcac secure_algo:SecurePasswordKdfAlgo secure_secret:bytes secure_secret_id:long = SecureSecretSettings`
  @TLObject(id: 0x1527bcac)
  public struct SecureSecretSettings: Equatable, Sendable {
    public var secureAlgo: TL.SecurePasswordKdfAlgoType
    public var secureSecret: Data
    public var secureSecretId: Int64
  }
}
