// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `secureValueHash#ed1ecdb0 type:SecureValueType hash:bytes = SecureValueHash`
  @TLObject(id: 0xed1ecdb0)
  public struct SecureValueHash: Equatable, Sendable {
    public var type: TL.SecureValueTypeType
    public var hash: Data
  }
}
