// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `starsRating#1b0e4f07 flags:# level:int current_level_stars:long stars:long next_level_stars:flags.0?long = StarsRating`
  @TLObject(id: 0x1b0e4f07)
  @TLFlagsEquatable
  public struct StarsRating: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var level: Int32
    public var currentLevelStars: Int64
    public var stars: Int64
    @TLConditional("flags", bit: 0) public var nextLevelStars: Int64? = nil
  }
}
