// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `starGiftUpgradePrice#99ea331d date:int upgrade_stars:long = StarGiftUpgradePrice`
  @TLObject(id: 0x99ea331d)
  public struct StarGiftUpgradePrice: Equatable, Sendable {
    public var date: Int32
    public var upgradeStars: Int64
  }
}
