// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `starsTransaction#13659eb0 flags:# refund:flags.3?true pending:flags.4?true failed:flags.6?true gift:flags.10?true reaction:flags.11?true stargift_upgrade:flags.18?true business_transfer:flags.21?true stargift_resale:flags.22?true posts_search:flags.24?true stargift_prepaid_upgrade:flags.25?true stargift_drop_original_details:flags.26?true phonegroup_message:flags.27?true stargift_auction_bid:flags.28?true offer:flags.29?true id:string amount:StarsAmount date:int peer:StarsTransactionPeer title:flags.0?string description:flags.1?string photo:flags.2?WebDocument transaction_date:flags.5?int transaction_url:flags.5?string bot_payload:flags.7?bytes msg_id:flags.8?int extended_media:flags.9?Vector<MessageMedia> subscription_period:flags.12?int giveaway_post_id:flags.13?int stargift:flags.14?StarGift floodskip_number:flags.15?int starref_commission_permille:flags.16?int starref_peer:flags.17?Peer starref_amount:flags.17?StarsAmount paid_messages:flags.19?int premium_gift_months:flags.20?int ads_proceeds_from_date:flags.23?int ads_proceeds_to_date:flags.23?int = StarsTransaction`
  @TLObject(id: 0x13659eb0)
  @TLFlagsEquatable
  public struct StarsTransaction: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 3) public var refund: Bool = false
    @TLConditional("flags", bit: 4) public var pending: Bool = false
    @TLConditional("flags", bit: 6) public var failed: Bool = false
    @TLConditional("flags", bit: 10) public var gift: Bool = false
    @TLConditional("flags", bit: 11) public var reaction: Bool = false
    @TLConditional("flags", bit: 18) public var stargiftUpgrade: Bool = false
    @TLConditional("flags", bit: 21) public var businessTransfer: Bool = false
    @TLConditional("flags", bit: 22) public var stargiftResale: Bool = false
    @TLConditional("flags", bit: 24) public var postsSearch: Bool = false
    @TLConditional("flags", bit: 25) public var stargiftPrepaidUpgrade: Bool = false
    @TLConditional("flags", bit: 26) public var stargiftDropOriginalDetails: Bool = false
    @TLConditional("flags", bit: 27) public var phonegroupMessage: Bool = false
    @TLConditional("flags", bit: 28) public var stargiftAuctionBid: Bool = false
    @TLConditional("flags", bit: 29) public var offer: Bool = false
    public var id: String
    public var amount: TL.StarsAmountType
    public var date: Int32
    public var peer: TL.StarsTransactionPeerType
    @TLConditional("flags", bit: 0) public var title: String? = nil
    @TLConditional("flags", bit: 1) public var description: String? = nil
    @TLConditional("flags", bit: 2) public var photo: TL.WebDocumentType? = nil
    @TLConditional("flags", bit: 5) public var transactionDate: Int32? = nil
    @TLConditional("flags", bit: 5) public var transactionUrl: String? = nil
    @TLConditional("flags", bit: 7) public var botPayload: Data? = nil
    @TLConditional("flags", bit: 8) public var msgId: Int32? = nil
    @TLConditional("flags", bit: 9) public var extendedMedia: [TL.MessageMediaType]? = nil
    @TLConditional("flags", bit: 12) public var subscriptionPeriod: Int32? = nil
    @TLConditional("flags", bit: 13) public var giveawayPostId: Int32? = nil
    @TLConditional("flags", bit: 14) public var stargift: TL.StarGiftType? = nil
    @TLConditional("flags", bit: 15) public var floodskipNumber: Int32? = nil
    @TLConditional("flags", bit: 16) public var starrefCommissionPermille: Int32? = nil
    @TLConditional("flags", bit: 17) public var starrefPeer: TL.PeerType? = nil
    @TLConditional("flags", bit: 17) public var starrefAmount: TL.StarsAmountType? = nil
    @TLConditional("flags", bit: 19) public var paidMessages: Int32? = nil
    @TLConditional("flags", bit: 20) public var premiumGiftMonths: Int32? = nil
    @TLConditional("flags", bit: 23) public var adsProceedsFromDate: Int32? = nil
    @TLConditional("flags", bit: 23) public var adsProceedsToDate: Int32? = nil
  }
}
