// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `statsGroupTopInviter#535f779d user_id:long invitations:int = StatsGroupTopInviter`
  @TLObject(id: 0x535f779d)
  public struct StatsGroupTopInviter: Equatable, Sendable {
    public var userId: Int64
    public var invitations: Int32
  }
}
