// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `statsPercentValue#cbce2fe0 part:double total:double = StatsPercentValue`
  @TLObject(id: 0xcbce2fe0)
  public struct StatsPercentValue: Equatable, Sendable {
    public var part: Double
    public var total: Double
  }
}
