// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `statsURL#47a971e0 url:string = StatsURL`
  @TLObject(id: 0x47a971e0)
  public struct StatsURL: Equatable, Sendable {
    public var url: String
  }
}
