// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stats {

  /// TL: `stats.publicForwards#93037e20 flags:# count:int forwards:Vector<PublicForward> next_offset:flags.0?string chats:Vector<Chat> users:Vector<User> = stats.PublicForwards`
  @TLObject(id: 0x93037e20)
  @TLFlagsEquatable
  public struct PublicForwards: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var count: Int32
    public var forwards: [TL.PublicForwardType]
    @TLConditional("flags", bit: 0) public var nextOffset: String? = nil
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
