// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `statsGroupTopPoster#9d04af9b user_id:long messages:int avg_chars:int = StatsGroupTopPoster`
  @TLObject(id: 0x9d04af9b)
  public struct StatsGroupTopPoster: Equatable, Sendable {
    public var userId: Int64
    public var messages: Int32
    public var avgChars: Int32
  }
}
