// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stickers {

  /// TL: `stickers.suggestedShortName#85fea03f short_name:string = stickers.SuggestedShortName`
  @TLObject(id: 0x85fea03f)
  public struct SuggestedShortName: Equatable, Sendable {
    public var shortName: String
  }
}
