// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.canSendStoryCount#c387c04e count_remains:int = stories.CanSendStoryCount`
  @TLObject(id: 0xc387c04e)
  public struct CanSendStoryCount: Equatable, Sendable {
    public var countRemains: Int32
  }
}
