// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `storyAlbum#9325705a flags:# album_id:int title:string icon_photo:flags.0?Photo icon_video:flags.1?Document = StoryAlbum`
  @TLObject(id: 0x9325705a)
  @TLFlagsEquatable
  public struct StoryAlbum: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var albumId: Int32
    public var title: String
    @TLConditional("flags", bit: 0) public var iconPhoto: TL.PhotoType? = nil
    @TLConditional("flags", bit: 1) public var iconVideo: TL.DocumentType? = nil
  }
}
