// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `StoryReaction` (3 constructors).
  @TLType
  public indirect enum StoryReactionType: Equatable, Sendable {
    /// `storyReaction#6090d6d5 peer_id:Peer date:int reaction:Reaction = StoryReaction`
    case storyReaction(TL.StoryReaction)
    /// `storyReactionPublicForward#bbab2643 message:Message = StoryReaction`
    case storyReactionPublicForward(TL.StoryReactionPublicForward)
    /// `storyReactionPublicRepost#cfcd0f13 peer_id:Peer story:StoryItem = StoryReaction`
    case storyReactionPublicRepost(TL.StoryReactionPublicRepost)
  }

  /// TL: `storyReaction#6090d6d5 peer_id:Peer date:int reaction:Reaction = StoryReaction`
  @TLObject(id: 0x6090d6d5)
  public struct StoryReaction: Equatable, Sendable {
    public var peerId: TL.PeerType
    public var date: Int32
    public var reaction: TL.ReactionType
  }

  /// TL: `storyReactionPublicForward#bbab2643 message:Message = StoryReaction`
  @TLObject(id: 0xbbab2643)
  public struct StoryReactionPublicForward: Equatable, Sendable {
    public var message: TL.MessageType
  }

  /// TL: `storyReactionPublicRepost#cfcd0f13 peer_id:Peer story:StoryItem = StoryReaction`
  @TLObject(id: 0xcfcd0f13)
  public struct StoryReactionPublicRepost: Equatable, Sendable {
    public var peerId: TL.PeerType
    public var story: TL.StoryItemType
  }
}
