// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Stories {

  /// TL: `stories.foundStories#e2de7737 flags:# count:int stories:Vector<FoundStory> next_offset:flags.0?string chats:Vector<Chat> users:Vector<User> = stories.FoundStories`
  @TLObject(id: 0xe2de7737)
  @TLFlagsEquatable
  public struct FoundStories: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var count: Int32
    public var stories: [TL.FoundStory]
    @TLConditional("flags", bit: 0) public var nextOffset: String? = nil
    public var chats: [TL.ChatType]
    public var users: [TL.UserType]
  }
}
