// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `StoryView` (3 constructors).
  @TLType
  public indirect enum StoryViewType: Equatable, Sendable {
    /// `storyView#b0bdeac5 flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true user_id:long date:int reaction:flags.2?Reaction = StoryView`
    case storyView(TL.StoryView)
    /// `storyViewPublicForward#9083670b flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true message:Message = StoryView`
    case storyViewPublicForward(TL.StoryViewPublicForward)
    /// `storyViewPublicRepost#bd74cf49 flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true peer_id:Peer story:StoryItem = StoryView`
    case storyViewPublicRepost(TL.StoryViewPublicRepost)
  }

  /// TL: `storyView#b0bdeac5 flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true user_id:long date:int reaction:flags.2?Reaction = StoryView`
  @TLObject(id: 0xb0bdeac5)
  @TLFlagsEquatable
  public struct StoryView: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var blocked: Bool = false
    @TLConditional("flags", bit: 1) public var blockedMyStoriesFrom: Bool = false
    public var userId: Int64
    public var date: Int32
    @TLConditional("flags", bit: 2) public var reaction: TL.ReactionType? = nil
  }

  /// TL: `storyViewPublicForward#9083670b flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true message:Message = StoryView`
  @TLObject(id: 0x9083670b)
  @TLFlagsEquatable
  public struct StoryViewPublicForward: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var blocked: Bool = false
    @TLConditional("flags", bit: 1) public var blockedMyStoriesFrom: Bool = false
    public var message: TL.MessageType
  }

  /// TL: `storyViewPublicRepost#bd74cf49 flags:# blocked:flags.0?true blocked_my_stories_from:flags.1?true peer_id:Peer story:StoryItem = StoryView`
  @TLObject(id: 0xbd74cf49)
  @TLFlagsEquatable
  public struct StoryViewPublicRepost: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var blocked: Bool = false
    @TLConditional("flags", bit: 1) public var blockedMyStoriesFrom: Bool = false
    public var peerId: TL.PeerType
    public var story: TL.StoryItemType
  }
}
