// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `TopPeerCategory` (10 constructors).
  @TLType
  public indirect enum TopPeerCategoryType: Equatable, Sendable {
    /// `topPeerCategoryBotsPM#ab661b5b = TopPeerCategory`
    case topPeerCategoryBotsPM(TL.TopPeerCategoryBotsPM)
    /// `topPeerCategoryBotsInline#148677e2 = TopPeerCategory`
    case topPeerCategoryBotsInline(TL.TopPeerCategoryBotsInline)
    /// `topPeerCategoryCorrespondents#0637b7ed = TopPeerCategory`
    case topPeerCategoryCorrespondents(TL.TopPeerCategoryCorrespondents)
    /// `topPeerCategoryGroups#bd17a14a = TopPeerCategory`
    case topPeerCategoryGroups(TL.TopPeerCategoryGroups)
    /// `topPeerCategoryChannels#161d9628 = TopPeerCategory`
    case topPeerCategoryChannels(TL.TopPeerCategoryChannels)
    /// `topPeerCategoryPhoneCalls#1e76a78c = TopPeerCategory`
    case topPeerCategoryPhoneCalls(TL.TopPeerCategoryPhoneCalls)
    /// `topPeerCategoryForwardUsers#a8406ca9 = TopPeerCategory`
    case topPeerCategoryForwardUsers(TL.TopPeerCategoryForwardUsers)
    /// `topPeerCategoryForwardChats#fbeec0f0 = TopPeerCategory`
    case topPeerCategoryForwardChats(TL.TopPeerCategoryForwardChats)
    /// `topPeerCategoryBotsApp#fd9e7bec = TopPeerCategory`
    case topPeerCategoryBotsApp(TL.TopPeerCategoryBotsApp)
    /// `topPeerCategoryBotsGuestChat#6c24f3dd = TopPeerCategory`
    case topPeerCategoryBotsGuestChat(TL.TopPeerCategoryBotsGuestChat)
  }

  /// TL: `topPeerCategoryBotsPM#ab661b5b = TopPeerCategory`
  @TLObject(id: 0xab661b5b)
  public struct TopPeerCategoryBotsPM: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryBotsInline#148677e2 = TopPeerCategory`
  @TLObject(id: 0x148677e2)
  public struct TopPeerCategoryBotsInline: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryCorrespondents#0637b7ed = TopPeerCategory`
  @TLObject(id: 0x0637b7ed)
  public struct TopPeerCategoryCorrespondents: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryGroups#bd17a14a = TopPeerCategory`
  @TLObject(id: 0xbd17a14a)
  public struct TopPeerCategoryGroups: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryChannels#161d9628 = TopPeerCategory`
  @TLObject(id: 0x161d9628)
  public struct TopPeerCategoryChannels: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryPhoneCalls#1e76a78c = TopPeerCategory`
  @TLObject(id: 0x1e76a78c)
  public struct TopPeerCategoryPhoneCalls: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryForwardUsers#a8406ca9 = TopPeerCategory`
  @TLObject(id: 0xa8406ca9)
  public struct TopPeerCategoryForwardUsers: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryForwardChats#fbeec0f0 = TopPeerCategory`
  @TLObject(id: 0xfbeec0f0)
  public struct TopPeerCategoryForwardChats: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryBotsApp#fd9e7bec = TopPeerCategory`
  @TLObject(id: 0xfd9e7bec)
  public struct TopPeerCategoryBotsApp: Equatable, Sendable {
  }

  /// TL: `topPeerCategoryBotsGuestChat#6c24f3dd = TopPeerCategory`
  @TLObject(id: 0x6c24f3dd)
  public struct TopPeerCategoryBotsGuestChat: Equatable, Sendable {
  }
}
