// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `topPeerCategoryPeers#fb834291 category:TopPeerCategory count:int peers:Vector<TopPeer> = TopPeerCategoryPeers`
  @TLObject(id: 0xfb834291)
  public struct TopPeerCategoryPeers: Equatable, Sendable {
    public var category: TL.TopPeerCategoryType
    public var count: Int32
    public var peers: [TL.TopPeer]
  }
}
