// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Updates {

  /// TL: `updates.state#a56c2a3e pts:int qts:int date:int seq:int unread_count:int = updates.State`
  @TLObject(id: 0xa56c2a3e)
  public struct State: Equatable, Sendable {
    public var pts: Int32
    public var qts: Int32
    public var date: Int32
    public var seq: Int32
    public var unreadCount: Int32
  }
}
