// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `UrlAuthResult` (3 constructors).
  @TLType
  public indirect enum UrlAuthResultType: Equatable, Sendable {
    /// `urlAuthResultRequest#3cd623ec flags:# request_write_access:flags.0?true request_phone_number:flags.1?true match_codes_first:flags.5?true is_app:flags.6?true bot:User domain:string browser:flags.2?string platform:flags.2?string ip:flags.2?string region:flags.2?string match_codes:flags.3?Vector<string> user_id_hint:flags.4?long verified_app_name:flags.7?string = UrlAuthResult`
    case urlAuthResultRequest(TL.UrlAuthResultRequest)
    /// `urlAuthResultAccepted#623a8fa0 flags:# url:flags.0?string = UrlAuthResult`
    case urlAuthResultAccepted(TL.UrlAuthResultAccepted)
    /// `urlAuthResultDefault#a9d6db1f = UrlAuthResult`
    case urlAuthResultDefault(TL.UrlAuthResultDefault)
  }

  /// TL: `urlAuthResultRequest#3cd623ec flags:# request_write_access:flags.0?true request_phone_number:flags.1?true match_codes_first:flags.5?true is_app:flags.6?true bot:User domain:string browser:flags.2?string platform:flags.2?string ip:flags.2?string region:flags.2?string match_codes:flags.3?Vector<string> user_id_hint:flags.4?long verified_app_name:flags.7?string = UrlAuthResult`
  @TLObject(id: 0x3cd623ec)
  @TLFlagsEquatable
  public struct UrlAuthResultRequest: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var requestWriteAccess: Bool = false
    @TLConditional("flags", bit: 1) public var requestPhoneNumber: Bool = false
    @TLConditional("flags", bit: 5) public var matchCodesFirst: Bool = false
    @TLConditional("flags", bit: 6) public var isApp: Bool = false
    public var bot: TL.UserType
    public var domain: String
    @TLConditional("flags", bit: 2) public var browser: String? = nil
    @TLConditional("flags", bit: 2) public var platform: String? = nil
    @TLConditional("flags", bit: 2) public var ip: String? = nil
    @TLConditional("flags", bit: 2) public var region: String? = nil
    @TLConditional("flags", bit: 3) public var matchCodes: [String]? = nil
    @TLConditional("flags", bit: 4) public var userIdHint: Int64? = nil
    @TLConditional("flags", bit: 7) public var verifiedAppName: String? = nil
  }

  /// TL: `urlAuthResultAccepted#623a8fa0 flags:# url:flags.0?string = UrlAuthResult`
  @TLObject(id: 0x623a8fa0)
  @TLFlagsEquatable
  public struct UrlAuthResultAccepted: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var url: String? = nil
  }

  /// TL: `urlAuthResultDefault#a9d6db1f = UrlAuthResult`
  @TLObject(id: 0xa9d6db1f)
  public struct UrlAuthResultDefault: Equatable, Sendable {
  }
}
