// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Users {

  /// The TL type `users.Users` (2 constructors).
  @TLType
  public indirect enum UsersType: Equatable, Sendable {
    /// `users.users#62d706b8 users:Vector<User> = users.Users`
    case users(TL.Users.Users)
    /// `users.usersSlice#315a4974 count:int users:Vector<User> = users.Users`
    case usersSlice(TL.Users.UsersSlice)
  }

  /// TL: `users.users#62d706b8 users:Vector<User> = users.Users`
  @TLObject(id: 0x62d706b8)
  public struct Users: Equatable, Sendable {
    public var users: [TL.UserType]
  }

  /// TL: `users.usersSlice#315a4974 count:int users:Vector<User> = users.Users`
  @TLObject(id: 0x315a4974)
  public struct UsersSlice: Equatable, Sendable {
    public var count: Int32
    public var users: [TL.UserType]
  }
}
