// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Smsjobs {

  /// TL: `smsjobs.updateSettings#093fa0bf flags:# allow_international:flags.0?true = Bool`
  @TLObject(id: 0x093fa0bf, returning: Bool.self)
  @TLFlagsEquatable
  public struct UpdateSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var allowInternational: Bool = false
  }
}
