// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsCommunities
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `communities.*` methods.
  public var communities: CommunitiesMethods {
    CommunitiesMethods(client: self)
  }
  /// The `communities.*` methods of a `TLClient`.
  public struct CommunitiesMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `communities.create#a63859ec flags:# hidden:flags.1?true title:string about:flags.0?string peer:InputPeer = Updates`
    public func create(hidden: Bool = false, title: String, about: String? = nil, peer: TL.InputPeerType) async throws -> TL.UpdatesType {
      try await client.invoke(TL.Communities.Create(hidden: hidden, title: title, about: about, peer: peer))
    }
    /// TL: `communities.togglePeerLink#736dcfea flags:# visible:flags.0?true hidden:flags.1?true deleted:flags.2?true community:InputChannel peer:InputPeer = Bool`
    public func togglePeerLink(visible: Bool = false, hidden: Bool = false, deleted: Bool = false, community: TL.InputChannelType, peer: TL.InputPeerType) async throws -> Bool {
      try await client.invoke(TL.Communities.TogglePeerLink(visible: visible, hidden: hidden, deleted: deleted, community: community, peer: peer))
    }
    /// TL: `communities.getJoinedCommunities#a663e830 = messages.Chats`
    public func getJoinedCommunities() async throws -> TL.Messages.ChatsType {
      try await client.invoke(TL.Communities.GetJoinedCommunities())
    }
    /// TL: `communities.toggleCommunityCollapsedInDialogs#d766e3ea flags:# collapsed:flags.0?true community:InputChannel = Updates`
    public func toggleCommunityCollapsedInDialogs(collapsed: Bool = false, community: TL.InputChannelType) async throws -> TL.UpdatesType {
      try await client.invoke(TL.Communities.ToggleCommunityCollapsedInDialogs(collapsed: collapsed, community: community))
    }
    /// TL: `communities.getPeerLinkRequests#93773344 community:InputChannel offset:string limit:int = communities.PeerLinkRequests`
    public func getPeerLinkRequests(community: TL.InputChannelType, offset: String, limit: Int32) async throws -> TL.Communities.PeerLinkRequests {
      try await client.invoke(TL.Communities.GetPeerLinkRequests(community: community, offset: offset, limit: limit))
    }
    /// TL: `communities.togglePeerLinkRequestApproval#8c8219a8 flags:# reject:flags.0?true community:InputChannel peer:InputPeer = Bool`
    public func togglePeerLinkRequestApproval(reject: Bool = false, community: TL.InputChannelType, peer: TL.InputPeerType) async throws -> Bool {
      try await client.invoke(TL.Communities.TogglePeerLinkRequestApproval(reject: reject, community: community, peer: peer))
    }
    /// TL: `communities.toggleAllPeerLinkRequestApproval#bfe3dd3d flags:# reject:flags.0?true community:InputChannel = Bool`
    public func toggleAllPeerLinkRequestApproval(reject: Bool = false, community: TL.InputChannelType) async throws -> Bool {
      try await client.invoke(TL.Communities.ToggleAllPeerLinkRequestApproval(reject: reject, community: community))
    }
    /// TL: `communities.toggleParticipantBanned#9967ad0f flags:# unban:flags.0?true community:InputChannel participant:InputPeer = Bool`
    public func toggleParticipantBanned(unban: Bool = false, community: TL.InputChannelType, participant: TL.InputPeerType) async throws -> Bool {
      try await client.invoke(TL.Communities.ToggleParticipantBanned(unban: unban, community: community, participant: participant))
    }
    /// TL: `communities.getParticipantJoinedChats#f87eabab community:InputChannel participant:InputPeer = communities.ParticipantJoinedChats`
    public func getParticipantJoinedChats(community: TL.InputChannelType, participant: TL.InputPeerType) async throws -> TL.Communities.ParticipantJoinedChats {
      try await client.invoke(TL.Communities.GetParticipantJoinedChats(community: community, participant: participant))
    }
  }
}
