// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.deleteContacts#096a0e00 id:Vector<InputUser> = Updates`
  @TLObject(id: 0x096a0e00, returning: TL.UpdatesType.self)
  public struct DeleteContacts: Equatable, Sendable {
    public var id: [TL.InputUserType]
  }
}
