// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.setBlocked#94c65c76 flags:# my_stories_from:flags.0?true id:Vector<InputPeer> limit:int = Bool`
  @TLObject(id: 0x94c65c76, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetBlocked: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var myStoriesFrom: Bool = false
    public var id: [TL.InputPeerType]
    public var limit: Int32
  }
}
