// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.getStatuses#c4a353ee = Vector<ContactStatus>`
  @TLObject(id: 0xc4a353ee, returning: [TL.ContactStatus].self)
  public struct GetStatuses: Equatable, Sendable {
  }
}
