// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.importContactToken#13005788 token:string = User`
  @TLObject(id: 0x13005788, returning: TL.UserType.self)
  public struct ImportContactToken: Equatable, Sendable {
    public var token: String
  }
}
