// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.resolvePhone#8af94344 phone:string = contacts.ResolvedPeer`
  @TLObject(id: 0x8af94344, returning: TL.Contacts.ResolvedPeer.self)
  public struct ResolvePhone: Equatable, Sendable {
    public var phone: String
  }
}
