// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.getBirthdays#daeda864 = contacts.ContactBirthdays`
  @TLObject(id: 0xdaeda864, returning: TL.Contacts.ContactBirthdays.self)
  public struct GetBirthdays: Equatable, Sendable {
  }
}
