// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.resetTopPeerRating#1ae373ac category:TopPeerCategory peer:InputPeer = Bool`
  @TLObject(id: 0x1ae373ac, returning: Bool.self)
  public struct ResetTopPeerRating: Equatable, Sendable {
    public var category: TL.TopPeerCategoryType
    public var peer: TL.InputPeerType
  }
}
