// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Contacts {

  /// TL: `contacts.updateContactNote#139f63fb id:InputUser note:TextWithEntities = Bool`
  @TLObject(id: 0x139f63fb, returning: Bool.self)
  public struct UpdateContactNote: Equatable, Sendable {
    public var id: TL.InputUserType
    public var note: TL.TextWithEntities
  }
}
