// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.toggleParticipantsHidden#6a6e7854 channel:InputChannel enabled:Bool = Updates`
  @TLObject(id: 0x6a6e7854, returning: TL.UpdatesType.self)
  public struct ToggleParticipantsHidden: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var enabled: Bool
  }
}
