// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.editBanned#96e6cd81 channel:InputChannel participant:InputPeer banned_rights:ChatBannedRights = Updates`
  @TLObject(id: 0x96e6cd81, returning: TL.UpdatesType.self)
  public struct EditBanned: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var participant: TL.InputPeerType
    public var bannedRights: TL.ChatBannedRights
  }
}
