// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.reportSpam#f44a8315 channel:InputChannel participant:InputPeer id:Vector<int> = Bool`
  @TLObject(id: 0xf44a8315, returning: Bool.self)
  public struct ReportSpam: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var participant: TL.InputPeerType
    public var id: [Int32]
  }
}
