// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.toggleUsername#50f24105 channel:InputChannel username:string active:Bool = Bool`
  @TLObject(id: 0x50f24105, returning: Bool.self)
  public struct ToggleUsername: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var username: String
    public var active: Bool
  }
}
