// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getFullChannel#08736a09 channel:InputChannel = messages.ChatFull`
  @TLObject(id: 0x08736a09, returning: TL.Messages.ChatFull.self)
  public struct GetFullChannel: Equatable, Sendable {
    public var channel: TL.InputChannelType
  }
}
