// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getMessages#ad8c9a23 channel:InputChannel id:Vector<InputMessage> = messages.Messages`
  @TLObject(id: 0xad8c9a23, returning: TL.Messages.MessagesType.self)
  public struct GetMessages: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var id: [TL.InputMessageType]
  }
}
