// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.editPhoto#f12e57c9 channel:InputChannel photo:InputChatPhoto = Updates`
  @TLObject(id: 0xf12e57c9, returning: TL.UpdatesType.self)
  public struct EditPhoto: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var photo: TL.InputChatPhotoType
  }
}
