// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getInactiveChannels#11e831ee = messages.InactiveChats`
  @TLObject(id: 0x11e831ee, returning: TL.Messages.InactiveChats.self)
  public struct GetInactiveChannels: Equatable, Sendable {
  }
}
