// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getGroupsForDiscussion#f5dad378 = messages.Chats`
  @TLObject(id: 0xf5dad378, returning: TL.Messages.ChatsType.self)
  public struct GetGroupsForDiscussion: Equatable, Sendable {
  }
}
