// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.setEmojiStickers#3cd930b7 channel:InputChannel stickerset:InputStickerSet = Bool`
  @TLObject(id: 0x3cd930b7, returning: Bool.self)
  public struct SetEmojiStickers: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var stickerset: TL.InputStickerSetType
  }
}
