// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.editLocation#58e63f6d channel:InputChannel geo_point:InputGeoPoint address:string = Bool`
  @TLObject(id: 0x58e63f6d, returning: Bool.self)
  public struct EditLocation: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var geoPoint: TL.InputGeoPointType
    public var address: String
  }
}
