// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.reportAntiSpamFalsePositive#a850a693 channel:InputChannel msg_id:int = Bool`
  @TLObject(id: 0xa850a693, returning: Bool.self)
  public struct ReportAntiSpamFalsePositive: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var msgId: Int32
  }
}
