// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getParticipants#77ced9d0 channel:InputChannel filter:ChannelParticipantsFilter offset:int limit:int hash:long = channels.ChannelParticipants`
  @TLObject(id: 0x77ced9d0, returning: TL.Channels.ChannelParticipantsType.self)
  public struct GetParticipants: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var filter: TL.ChannelParticipantsFilterType
    public var offset: Int32
    public var limit: Int32
    public var hash: Int64
  }
}
