// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.joinChannel#7f6a1e22 channel:InputChannel = messages.ChatInviteJoinResult`
  @TLObject(id: 0x7f6a1e22, returning: TL.Messages.ChatInviteJoinResultType.self)
  public struct JoinChannel: Equatable, Sendable {
    public var channel: TL.InputChannelType
  }
}
