// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.exportMessageLink#e63fadeb flags:# grouped:flags.0?true thread:flags.1?true channel:InputChannel id:int = ExportedMessageLink`
  @TLObject(id: 0xe63fadeb, returning: TL.ExportedMessageLink.self)
  @TLFlagsEquatable
  public struct ExportMessageLink: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var grouped: Bool = false
    @TLConditional("flags", bit: 1) public var thread: Bool = false
    public var channel: TL.InputChannelType
    public var id: Int32
  }
}
