// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.checkUsername#10e6bd2c channel:InputChannel username:string = Bool`
  @TLObject(id: 0x10e6bd2c, returning: Bool.self)
  public struct CheckUsername: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var username: String
  }
}
