// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.setMainProfileTab#3583fcb1 channel:InputChannel tab:ProfileTab = Bool`
  @TLObject(id: 0x3583fcb1, returning: Bool.self)
  public struct SetMainProfileTab: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var tab: TL.ProfileTabType
  }
}
