// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.getSendAs#e785a43f flags:# for_paid_reactions:flags.0?true for_live_stories:flags.1?true peer:InputPeer = channels.SendAsPeers`
  @TLObject(id: 0xe785a43f, returning: TL.Channels.SendAsPeers.self)
  @TLFlagsEquatable
  public struct GetSendAs: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var forPaidReactions: Bool = false
    @TLConditional("flags", bit: 1) public var forLiveStories: Bool = false
    public var peer: TL.InputPeerType
  }
}
