// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.setDiscussionGroup#40582bb2 broadcast:InputChannel group:InputChannel = Bool`
  @TLObject(id: 0x40582bb2, returning: Bool.self)
  public struct SetDiscussionGroup: Equatable, Sendable {
    public var broadcast: TL.InputChannelType
    public var group: TL.InputChannelType
  }
}
