// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Channels {

  /// TL: `channels.deleteParticipantHistory#367544db channel:InputChannel participant:InputPeer = messages.AffectedHistory`
  @TLObject(id: 0x367544db, returning: TL.Messages.AffectedHistory.self)
  public struct DeleteParticipantHistory: Equatable, Sendable {
    public var channel: TL.InputChannelType
    public var participant: TL.InputPeerType
  }
}
