// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getConnectedStarRefBot#b7d998f0 peer:InputPeer bot:InputUser = payments.ConnectedStarRefBots`
  @TLObject(id: 0xb7d998f0, returning: TL.Payments.ConnectedStarRefBots.self)
  public struct GetConnectedStarRefBot: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var bot: TL.InputUserType
  }
}
