// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getStarGiftActiveAuctions#a5d0514d hash:long = payments.StarGiftActiveAuctions`
  @TLObject(id: 0xa5d0514d, returning: TL.Payments.StarGiftActiveAuctionsType.self)
  public struct GetStarGiftActiveAuctions: Equatable, Sendable {
    public var hash: Int64
  }
}
