// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.checkGiftCode#8e51b4c1 slug:string = payments.CheckedGiftCode`
  @TLObject(id: 0x8e51b4c1, returning: TL.Payments.CheckedGiftCode.self)
  public struct CheckGiftCode: Equatable, Sendable {
    public var slug: String
  }
}
