// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.sendStarsForm#7998c914 form_id:long invoice:InputInvoice = payments.PaymentResult`
  @TLObject(id: 0x7998c914, returning: TL.Payments.PaymentResultType.self)
  public struct SendStarsForm: Equatable, Sendable {
    public var formId: Int64
    public var invoice: TL.InputInvoiceType
  }
}
