// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.updateStarGiftPrice#edbe6ccb stargift:InputSavedStarGift resell_amount:StarsAmount = Updates`
  @TLObject(id: 0xedbe6ccb, returning: TL.UpdatesType.self)
  public struct UpdateStarGiftPrice: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
    public var resellAmount: TL.StarsAmountType
  }
}
