// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.updateStarGiftCollection#4fddbee7 flags:# peer:InputPeer collection_id:int title:flags.0?string delete_stargift:flags.1?Vector<InputSavedStarGift> add_stargift:flags.2?Vector<InputSavedStarGift> order:flags.3?Vector<InputSavedStarGift> = StarGiftCollection`
  @TLObject(id: 0x4fddbee7, returning: TL.StarGiftCollection.self)
  @TLFlagsEquatable
  public struct UpdateStarGiftCollection: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var collectionId: Int32
    @TLConditional("flags", bit: 0) public var title: String? = nil
    @TLConditional("flags", bit: 1) public var deleteStargift: [TL.InputSavedStarGiftType]? = nil
    @TLConditional("flags", bit: 2) public var addStargift: [TL.InputSavedStarGiftType]? = nil
    @TLConditional("flags", bit: 3) public var order: [TL.InputSavedStarGiftType]? = nil
  }
}
