// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getResaleStarGifts#7a5fa236 flags:# sort_by_price:flags.1?true sort_by_num:flags.2?true for_craft:flags.4?true stars_only:flags.5?true attributes_hash:flags.0?long gift_id:long attributes:flags.3?Vector<StarGiftAttributeId> offset:string limit:int = payments.ResaleStarGifts`
  @TLObject(id: 0x7a5fa236, returning: TL.Payments.ResaleStarGifts.self)
  @TLFlagsEquatable
  public struct GetResaleStarGifts: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var sortByPrice: Bool = false
    @TLConditional("flags", bit: 2) public var sortByNum: Bool = false
    @TLConditional("flags", bit: 4) public var forCraft: Bool = false
    @TLConditional("flags", bit: 5) public var starsOnly: Bool = false
    @TLConditional("flags", bit: 0) public var attributesHash: Int64? = nil
    public var giftId: Int64
    @TLConditional("flags", bit: 3) public var attributes: [TL.StarGiftAttributeIdType]? = nil
    public var offset: String
    public var limit: Int32
  }
}
