// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.assignPlayMarketTransaction#dffd50d3 receipt:DataJSON purpose:InputStorePaymentPurpose = Updates`
  @TLObject(id: 0xdffd50d3, returning: TL.UpdatesType.self)
  public struct AssignPlayMarketTransaction: Equatable, Sendable {
    public var receipt: TL.DataJSON
    public var purpose: TL.InputStorePaymentPurposeType
  }
}
