// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getPaymentReceipt#2478d1cc peer:InputPeer msg_id:int = payments.PaymentReceipt`
  @TLObject(id: 0x2478d1cc, returning: TL.Payments.PaymentReceiptType.self)
  public struct GetPaymentReceipt: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }
}
