// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.applyGiftCode#f6e26854 slug:string = Updates`
  @TLObject(id: 0xf6e26854, returning: TL.UpdatesType.self)
  public struct ApplyGiftCode: Equatable, Sendable {
    public var slug: String
  }
}
