// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getStarGiftWithdrawalUrl#d06e93a8 stargift:InputSavedStarGift password:InputCheckPasswordSRP = payments.StarGiftWithdrawalUrl`
  @TLObject(id: 0xd06e93a8, returning: TL.Payments.StarGiftWithdrawalUrl.self)
  public struct GetStarGiftWithdrawalUrl: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
    public var password: TL.InputCheckPasswordSRPType
  }
}
