// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.exportInvoice#0f91b065 invoice_media:InputMedia = payments.ExportedInvoice`
  @TLObject(id: 0x0f91b065, returning: TL.Payments.ExportedInvoice.self)
  public struct ExportInvoice: Equatable, Sendable {
    public var invoiceMedia: TL.InputMediaType
  }
}
