// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getGiveawayInfo#f4239425 peer:InputPeer msg_id:int = payments.GiveawayInfo`
  @TLObject(id: 0xf4239425, returning: TL.Payments.GiveawayInfoType.self)
  public struct GetGiveawayInfo: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }
}
