// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.canPurchaseStore#4fdc5ea7 purpose:InputStorePaymentPurpose = Bool`
  @TLObject(id: 0x4fdc5ea7, returning: Bool.self)
  public struct CanPurchaseStore: Equatable, Sendable {
    public var purpose: TL.InputStorePaymentPurposeType
  }
}
