// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.botCancelStarsSubscription#6dfa0622 flags:# restore:flags.0?true user_id:InputUser charge_id:string = Bool`
  @TLObject(id: 0x6dfa0622, returning: Bool.self)
  @TLFlagsEquatable
  public struct BotCancelStarsSubscription: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var restore: Bool = false
    public var userId: TL.InputUserType
    public var chargeId: String
  }
}
