// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getStarsRevenueAdsAccountUrl#d1d7efc5 peer:InputPeer = payments.StarsRevenueAdsAccountUrl`
  @TLObject(id: 0xd1d7efc5, returning: TL.Payments.StarsRevenueAdsAccountUrl.self)
  public struct GetStarsRevenueAdsAccountUrl: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
