// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.sendStarGiftOffer#8fb86b41 flags:# peer:InputPeer slug:string price:StarsAmount duration:int random_id:long allow_paid_stars:flags.0?long = Updates`
  @TLObject(id: 0x8fb86b41, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct SendStarGiftOffer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var slug: String
    public var price: TL.StarsAmountType
    public var duration: Int32
    public var randomId: Int64
    @TLConditional("flags", bit: 0) public var allowPaidStars: Int64? = nil
  }
}
