// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getStarsGiveawayOptions#bd1efd3e = Vector<StarsGiveawayOption>`
  @TLObject(id: 0xbd1efd3e, returning: [TL.StarsGiveawayOption].self)
  public struct GetStarsGiveawayOptions: Equatable, Sendable {
  }
}
