// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.refundStarsCharge#25ae8f4a user_id:InputUser charge_id:string = Updates`
  @TLObject(id: 0x25ae8f4a, returning: TL.UpdatesType.self)
  public struct RefundStarsCharge: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var chargeId: String
  }
}
