// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.transferStarGift#7f18176a stargift:InputSavedStarGift to_id:InputPeer = Updates`
  @TLObject(id: 0x7f18176a, returning: TL.UpdatesType.self)
  public struct TransferStarGift: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
    public var toId: TL.InputPeerType
  }
}
