// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.fulfillStarsSubscription#cc5bebb3 peer:InputPeer subscription_id:string = Bool`
  @TLObject(id: 0xcc5bebb3, returning: Bool.self)
  public struct FulfillStarsSubscription: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var subscriptionId: String
  }
}
