// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.checkCanSendGift#c0c4edc9 gift_id:long = payments.CheckCanSendGiftResult`
  @TLObject(id: 0xc0c4edc9, returning: TL.Payments.CheckCanSendGiftResultType.self)
  public struct CheckCanSendGift: Equatable, Sendable {
    public var giftId: Int64
  }
}
