// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getSavedStarGifts#a319e569 flags:# exclude_unsaved:flags.0?true exclude_saved:flags.1?true exclude_unlimited:flags.2?true exclude_unique:flags.4?true sort_by_value:flags.5?true exclude_upgradable:flags.7?true exclude_unupgradable:flags.8?true peer_color_available:flags.9?true exclude_hosted:flags.10?true peer:InputPeer collection_id:flags.6?int offset:string limit:int = payments.SavedStarGifts`
  @TLObject(id: 0xa319e569, returning: TL.Payments.SavedStarGifts.self)
  @TLFlagsEquatable
  public struct GetSavedStarGifts: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var excludeUnsaved: Bool = false
    @TLConditional("flags", bit: 1) public var excludeSaved: Bool = false
    @TLConditional("flags", bit: 2) public var excludeUnlimited: Bool = false
    @TLConditional("flags", bit: 4) public var excludeUnique: Bool = false
    @TLConditional("flags", bit: 5) public var sortByValue: Bool = false
    @TLConditional("flags", bit: 7) public var excludeUpgradable: Bool = false
    @TLConditional("flags", bit: 8) public var excludeUnupgradable: Bool = false
    @TLConditional("flags", bit: 9) public var peerColorAvailable: Bool = false
    @TLConditional("flags", bit: 10) public var excludeHosted: Bool = false
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 6) public var collectionId: Int32? = nil
    public var offset: String
    public var limit: Int32
  }
}
