// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.sendPaymentForm#2d03522f flags:# form_id:long invoice:InputInvoice requested_info_id:flags.0?string shipping_option_id:flags.1?string credentials:InputPaymentCredentials tip_amount:flags.2?long = payments.PaymentResult`
  @TLObject(id: 0x2d03522f, returning: TL.Payments.PaymentResultType.self)
  @TLFlagsEquatable
  public struct SendPaymentForm: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var formId: Int64
    public var invoice: TL.InputInvoiceType
    @TLConditional("flags", bit: 0) public var requestedInfoId: String? = nil
    @TLConditional("flags", bit: 1) public var shippingOptionId: String? = nil
    public var credentials: TL.InputPaymentCredentialsType
    @TLConditional("flags", bit: 2) public var tipAmount: Int64? = nil
  }
}
