// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.convertStarGift#74bf076b stargift:InputSavedStarGift = Bool`
  @TLObject(id: 0x74bf076b, returning: Bool.self)
  public struct ConvertStarGift: Equatable, Sendable {
    public var stargift: TL.InputSavedStarGiftType
  }
}
