// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Payments {

  /// TL: `payments.getStarsTransactions#69da4557 flags:# inbound:flags.0?true outbound:flags.1?true ascending:flags.2?true ton:flags.4?true subscription_id:flags.3?string peer:InputPeer offset:string limit:int = payments.StarsStatus`
  @TLObject(id: 0x69da4557, returning: TL.Payments.StarsStatus.self)
  @TLFlagsEquatable
  public struct GetStarsTransactions: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var inbound: Bool = false
    @TLConditional("flags", bit: 1) public var outbound: Bool = false
    @TLConditional("flags", bit: 2) public var ascending: Bool = false
    @TLConditional("flags", bit: 4) public var ton: Bool = false
    @TLConditional("flags", bit: 3) public var subscriptionId: String? = nil
    public var peer: TL.InputPeerType
    public var offset: String
    public var limit: Int32
  }
}
