// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Users {

  /// TL: `users.getSavedMusicByID#7573a4e9 id:InputUser documents:Vector<InputDocument> = users.SavedMusic`
  @TLObject(id: 0x7573a4e9, returning: TL.Users.SavedMusicType.self)
  public struct GetSavedMusicByID: Equatable, Sendable {
    public var id: TL.InputUserType
    public var documents: [TL.InputDocumentType]
  }
}
