// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Users {

  /// TL: `users.setSecureValueErrors#90c894b5 id:InputUser errors:Vector<SecureValueError> = Bool`
  @TLObject(id: 0x90c894b5, returning: Bool.self)
  public struct SetSecureValueErrors: Equatable, Sendable {
    public var id: TL.InputUserType
    public var errors: [TL.SecureValueErrorType]
  }
}
