// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Folders {

  /// TL: `folders.editPeerFolders#6847d0ab folder_peers:Vector<InputFolderPeer> = Updates`
  @TLObject(id: 0x6847d0ab, returning: TL.UpdatesType.self)
  public struct EditPeerFolders: Equatable, Sendable {
    public var folderPeers: [TL.InputFolderPeer]
  }
}
