// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.deletePasskey#f5b5563f id:string = Bool`
  @TLObject(id: 0xf5b5563f, returning: Bool.self)
  public struct DeletePasskey: Equatable, Sendable {
    public var id: String
  }
}
