// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.reportProfilePhoto#fa8cc6f5 peer:InputPeer photo_id:InputPhoto reason:ReportReason message:string = Bool`
  @TLObject(id: 0xfa8cc6f5, returning: Bool.self)
  public struct ReportProfilePhoto: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var photoId: TL.InputPhotoType
    public var reason: TL.ReportReasonType
    public var message: String
  }
}
