// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.sendVerifyPhoneCode#a5a356f9 phone_number:string settings:CodeSettings = auth.SentCode`
  @TLObject(id: 0xa5a356f9, returning: TL.Auth.SentCodeType.self)
  public struct SendVerifyPhoneCode: Equatable, Sendable {
    public var phoneNumber: String
    public var settings: TL.CodeSettings
  }
}
