// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getChannelRestrictedStatusEmojis#35a9e0d5 hash:long = EmojiList`
  @TLObject(id: 0x35a9e0d5, returning: TL.EmojiListType.self)
  public struct GetChannelRestrictedStatusEmojis: Equatable, Sendable {
    public var hash: Int64
  }
}
