// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setAuthorizationTTL#bf899aa0 authorization_ttl_days:int = Bool`
  @TLObject(id: 0xbf899aa0, returning: Bool.self)
  public struct SetAuthorizationTTL: Equatable, Sendable {
    public var authorizationTtlDays: Int32
  }
}
