// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getTheme#3a5869ec format:string theme:InputTheme = Theme`
  @TLObject(id: 0x3a5869ec, returning: TL.Theme.self)
  public struct GetTheme: Equatable, Sendable {
    public var format: String
    public var theme: TL.InputThemeType
  }
}
