// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.deleteSecureValue#b880bc4b types:Vector<SecureValueType> = Bool`
  @TLObject(id: 0xb880bc4b, returning: Bool.self)
  public struct DeleteSecureValue: Equatable, Sendable {
    public var types: [TL.SecureValueTypeType]
  }
}
