// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.toggleUsername#58d6b376 username:string active:Bool = Bool`
  @TLObject(id: 0x58d6b376, returning: Bool.self)
  public struct ToggleUsername: Equatable, Sendable {
    public var username: String
    public var active: Bool
  }
}
