// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.changeAuthorizationSettings#40f48462 flags:# confirmed:flags.3?true hash:long encrypted_requests_disabled:flags.0?Bool call_requests_disabled:flags.1?Bool = Bool`
  @TLObject(id: 0x40f48462, returning: Bool.self)
  @TLFlagsEquatable
  public struct ChangeAuthorizationSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 3) public var confirmed: Bool = false
    public var hash: Int64
    @TLConditional("flags", bit: 0) public var encryptedRequestsDisabled: Bool? = nil
    @TLConditional("flags", bit: 1) public var callRequestsDisabled: Bool? = nil
  }
}
