// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.updateUsername#3e0bdd7c username:string = User`
  @TLObject(id: 0x3e0bdd7c, returning: TL.UserType.self)
  public struct UpdateUsername: Equatable, Sendable {
    public var username: String
  }
}
