// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.resetAuthorization#df77f3bc hash:long = Bool`
  @TLObject(id: 0xdf77f3bc, returning: Bool.self)
  public struct ResetAuthorization: Equatable, Sendable {
    public var hash: Int64
  }
}
