// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.deleteAccount#a2c0cf74 flags:# reason:string password:flags.0?InputCheckPasswordSRP = Bool`
  @TLObject(id: 0xa2c0cf74, returning: Bool.self)
  @TLFlagsEquatable
  public struct DeleteAccount: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var reason: String
    @TLConditional("flags", bit: 0) public var password: TL.InputCheckPasswordSRPType? = nil
  }
}
