// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.toggleSponsoredMessages#b9d9a38d enabled:Bool = Bool`
  @TLObject(id: 0xb9d9a38d, returning: Bool.self)
  public struct ToggleSponsoredMessages: Equatable, Sendable {
    public var enabled: Bool
  }
}
