// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.updateProfile#78515775 flags:# first_name:flags.0?string last_name:flags.1?string about:flags.2?string = User`
  @TLObject(id: 0x78515775, returning: TL.UserType.self)
  @TLFlagsEquatable
  public struct UpdateProfile: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var firstName: String? = nil
    @TLConditional("flags", bit: 1) public var lastName: String? = nil
    @TLConditional("flags", bit: 2) public var about: String? = nil
  }
}
