// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.installWallPaper#feed5769 wallpaper:InputWallPaper settings:WallPaperSettings = Bool`
  @TLObject(id: 0xfeed5769, returning: Bool.self)
  public struct InstallWallPaper: Equatable, Sendable {
    public var wallpaper: TL.InputWallPaperType
    public var settings: TL.WallPaperSettings
  }
}
