// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setAccountTTL#2442485e ttl:AccountDaysTTL = Bool`
  @TLObject(id: 0x2442485e, returning: Bool.self)
  public struct SetAccountTTL: Equatable, Sendable {
    public var ttl: TL.AccountDaysTTL
  }
}
