// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getAutoSaveSettings#adcbbcda = account.AutoSaveSettings`
  @TLObject(id: 0xadcbbcda, returning: TL.Account.AutoSaveSettings.self)
  public struct GetAutoSaveSettings: Equatable, Sendable {
  }
}
