// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getNotifyExceptions#53577479 flags:# compare_sound:flags.1?true compare_stories:flags.2?true peer:flags.0?InputNotifyPeer = Updates`
  @TLObject(id: 0x53577479, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct GetNotifyExceptions: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var compareSound: Bool = false
    @TLConditional("flags", bit: 2) public var compareStories: Bool = false
    @TLConditional("flags", bit: 0) public var peer: TL.InputNotifyPeerType? = nil
  }
}
