// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.invalidateSignInCodes#ca8ae8ba codes:Vector<string> = Bool`
  @TLObject(id: 0xca8ae8ba, returning: Bool.self)
  public struct InvalidateSignInCodes: Equatable, Sendable {
    public var codes: [String]
  }
}
