// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.confirmBotConnection#67ed1f68 bot_id:InputUser = Bool`
  @TLObject(id: 0x67ed1f68, returning: Bool.self)
  public struct ConfirmBotConnection: Equatable, Sendable {
    public var botId: TL.InputUserType
  }
}
