// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.updateTheme#2bf40ccc flags:# format:string theme:InputTheme slug:flags.0?string title:flags.1?string document:flags.2?InputDocument settings:flags.3?Vector<InputThemeSettings> = Theme`
  @TLObject(id: 0x2bf40ccc, returning: TL.Theme.self)
  @TLFlagsEquatable
  public struct UpdateTheme: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var format: String
    public var theme: TL.InputThemeType
    @TLConditional("flags", bit: 0) public var slug: String? = nil
    @TLConditional("flags", bit: 1) public var title: String? = nil
    @TLConditional("flags", bit: 2) public var document: TL.InputDocumentType? = nil
    @TLConditional("flags", bit: 3) public var settings: [TL.InputThemeSettings]? = nil
  }
}
