// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.saveAutoDownloadSettings#76f36233 flags:# low:flags.0?true high:flags.1?true settings:AutoDownloadSettings = Bool`
  @TLObject(id: 0x76f36233, returning: Bool.self)
  @TLFlagsEquatable
  public struct SaveAutoDownloadSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var low: Bool = false
    @TLConditional("flags", bit: 1) public var high: Bool = false
    public var settings: TL.AutoDownloadSettings
  }
}
