// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setMainProfileTab#5dee78b0 tab:ProfileTab = Bool`
  @TLObject(id: 0x5dee78b0, returning: Bool.self)
  public struct SetMainProfileTab: Equatable, Sendable {
    public var tab: TL.ProfileTabType
  }
}
