// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.updateBusinessLocation#9e6b131a flags:# geo_point:flags.1?InputGeoPoint address:flags.0?string = Bool`
  @TLObject(id: 0x9e6b131a, returning: Bool.self)
  @TLFlagsEquatable
  public struct UpdateBusinessLocation: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var geoPoint: TL.InputGeoPointType? = nil
    @TLConditional("flags", bit: 0) public var address: String? = nil
  }
}
