// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.saveMusic#b26732a9 flags:# unsave:flags.0?true id:InputDocument after_id:flags.1?InputDocument = Bool`
  @TLObject(id: 0xb26732a9, returning: Bool.self)
  @TLFlagsEquatable
  public struct SaveMusic: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var unsave: Bool = false
    public var id: TL.InputDocumentType
    @TLConditional("flags", bit: 1) public var afterId: TL.InputDocumentType? = nil
  }
}
