// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.deleteAutoSaveExceptions#53bc0020 = Bool`
  @TLObject(id: 0x53bc0020, returning: Bool.self)
  public struct DeleteAutoSaveExceptions: Equatable, Sendable {
  }
}
