// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setReactionsNotifySettings#316ce548 settings:ReactionsNotifySettings = ReactionsNotifySettings`
  @TLObject(id: 0x316ce548, returning: TL.ReactionsNotifySettings.self)
  public struct SetReactionsNotifySettings: Equatable, Sendable {
    public var settings: TL.ReactionsNotifySettings
  }
}
