// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setGlobalPrivacySettings#1edaaac2 settings:GlobalPrivacySettings = GlobalPrivacySettings`
  @TLObject(id: 0x1edaaac2, returning: TL.GlobalPrivacySettings.self)
  public struct SetGlobalPrivacySettings: Equatable, Sendable {
    public var settings: TL.GlobalPrivacySettings
  }
}
