// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.uploadRingtone#831a83a2 file:InputFile file_name:string mime_type:string = Document`
  @TLObject(id: 0x831a83a2, returning: TL.DocumentType.self)
  public struct UploadRingtone: Equatable, Sendable {
    public var file: TL.InputFileType
    public var fileName: String
    public var mimeType: String
  }
}
