// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.setContentSettings#b574b16b flags:# sensitive_enabled:flags.0?true = Bool`
  @TLObject(id: 0xb574b16b, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetContentSettings: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var sensitiveEnabled: Bool = false
  }
}
