// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getDefaultProfilePhotoEmojis#e2750328 hash:long = EmojiList`
  @TLObject(id: 0xe2750328, returning: TL.EmojiListType.self)
  public struct GetDefaultProfilePhotoEmojis: Equatable, Sendable {
    public var hash: Int64
  }
}
