// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getBusinessChatLinks#6f70dde1 = account.BusinessChatLinks`
  @TLObject(id: 0x6f70dde1, returning: TL.Account.BusinessChatLinks.self)
  public struct GetBusinessChatLinks: Equatable, Sendable {
  }
}
