// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.editBusinessChatLink#8c3410af slug:string link:InputBusinessChatLink = BusinessChatLink`
  @TLObject(id: 0x8c3410af, returning: TL.BusinessChatLink.self)
  public struct EditBusinessChatLink: Equatable, Sendable {
    public var slug: String
    public var link: TL.InputBusinessChatLink
  }
}
