// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.initTakeoutSession#8ef3eab0 flags:# contacts:flags.0?true message_users:flags.1?true message_chats:flags.2?true message_megagroups:flags.3?true message_channels:flags.4?true files:flags.5?true file_max_size:flags.5?long = account.Takeout`
  @TLObject(id: 0x8ef3eab0, returning: TL.Account.Takeout.self)
  @TLFlagsEquatable
  public struct InitTakeoutSession: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var contacts: Bool = false
    @TLConditional("flags", bit: 1) public var messageUsers: Bool = false
    @TLConditional("flags", bit: 2) public var messageChats: Bool = false
    @TLConditional("flags", bit: 3) public var messageMegagroups: Bool = false
    @TLConditional("flags", bit: 4) public var messageChannels: Bool = false
    @TLConditional("flags", bit: 5) public var files: Bool = false
    @TLConditional("flags", bit: 5) public var fileMaxSize: Int64? = nil
  }
}
