// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getAccountTTL#08fc711d = AccountDaysTTL`
  @TLObject(id: 0x08fc711d, returning: TL.AccountDaysTTL.self)
  public struct GetAccountTTL: Equatable, Sendable {
  }
}
