// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.disablePeerConnectedBot#5e437ed9 peer:InputPeer = Bool`
  @TLObject(id: 0x5e437ed9, returning: Bool.self)
  public struct DisablePeerConnectedBot: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
