// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.resetWallPapers#bb3b9804 = Bool`
  @TLObject(id: 0xbb3b9804, returning: Bool.self)
  public struct ResetWallPapers: Equatable, Sendable {
  }
}
