// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getTmpPassword#449e0b51 password:InputCheckPasswordSRP period:int = account.TmpPassword`
  @TLObject(id: 0x449e0b51, returning: TL.Account.TmpPassword.self)
  public struct GetTmpPassword: Equatable, Sendable {
    public var password: TL.InputCheckPasswordSRPType
    public var period: Int32
  }
}
