// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getAuthorizations#e320c158 = account.Authorizations`
  @TLObject(id: 0xe320c158, returning: TL.Account.Authorizations.self)
  public struct GetAuthorizations: Equatable, Sendable {
  }
}
