// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.deleteBusinessChatLink#60073674 slug:string = Bool`
  @TLObject(id: 0x60073674, returning: Bool.self)
  public struct DeleteBusinessChatLink: Equatable, Sendable {
    public var slug: String
  }
}
