// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getWallPaper#fc8ddbea wallpaper:InputWallPaper = WallPaper`
  @TLObject(id: 0xfc8ddbea, returning: TL.WallPaperType.self)
  public struct GetWallPaper: Equatable, Sendable {
    public var wallpaper: TL.InputWallPaperType
  }
}
