// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.toggleNoPaidMessagesException#fe2eda76 flags:# refund_charged:flags.0?true require_payment:flags.2?true parent_peer:flags.1?InputPeer user_id:InputUser = Bool`
  @TLObject(id: 0xfe2eda76, returning: Bool.self)
  @TLFlagsEquatable
  public struct ToggleNoPaidMessagesException: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var refundCharged: Bool = false
    @TLConditional("flags", bit: 2) public var requirePayment: Bool = false
    @TLConditional("flags", bit: 1) public var parentPeer: TL.InputPeerType? = nil
    public var userId: TL.InputUserType
  }
}
