// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Account {

  /// TL: `account.getCollectibleEmojiStatuses#2e7b4543 hash:long = account.EmojiStatuses`
  @TLObject(id: 0x2e7b4543, returning: TL.Account.EmojiStatusesType.self)
  public struct GetCollectibleEmojiStatuses: Equatable, Sendable {
    public var hash: Int64
  }
}
