// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteExportedChatInvite#d464a42b peer:InputPeer link:string = Bool`
  @TLObject(id: 0xd464a42b, returning: Bool.self)
  public struct DeleteExportedChatInvite: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var link: String
  }
}
