// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.transcribeAudio#269e9a49 peer:InputPeer msg_id:int = messages.TranscribedAudio`
  @TLObject(id: 0x269e9a49, returning: TL.Messages.TranscribedAudio.self)
  public struct TranscribeAudio: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }
}
