// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getExportedChatInvites#a2b5a3f6 flags:# revoked:flags.3?true peer:InputPeer admin_id:InputUser offset_date:flags.2?int offset_link:flags.2?string limit:int = messages.ExportedChatInvites`
  @TLObject(id: 0xa2b5a3f6, returning: TL.Messages.ExportedChatInvites.self)
  @TLFlagsEquatable
  public struct GetExportedChatInvites: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 3) public var revoked: Bool = false
    public var peer: TL.InputPeerType
    public var adminId: TL.InputUserType
    @TLConditional("flags", bit: 2) public var offsetDate: Int32? = nil
    @TLConditional("flags", bit: 2) public var offsetLink: String? = nil
    public var limit: Int32
  }
}
