// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.clickSponsoredMessage#8235057e flags:# media:flags.0?true fullscreen:flags.1?true random_id:bytes = Bool`
  @TLObject(id: 0x8235057e, returning: Bool.self)
  @TLFlagsEquatable
  public struct ClickSponsoredMessage: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var media: Bool = false
    @TLConditional("flags", bit: 1) public var fullscreen: Bool = false
    public var randomId: Data
  }
}
