// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.acceptUrlAuth#67a3f0de flags:# write_allowed:flags.0?true share_phone_number:flags.3?true peer:flags.1?InputPeer msg_id:flags.1?int button_id:flags.1?int url:flags.2?string match_code:flags.4?string = UrlAuthResult`
  @TLObject(id: 0x67a3f0de, returning: TL.UrlAuthResultType.self)
  @TLFlagsEquatable
  public struct AcceptUrlAuth: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var writeAllowed: Bool = false
    @TLConditional("flags", bit: 3) public var sharePhoneNumber: Bool = false
    @TLConditional("flags", bit: 1) public var peer: TL.InputPeerType? = nil
    @TLConditional("flags", bit: 1) public var msgId: Int32? = nil
    @TLConditional("flags", bit: 1) public var buttonId: Int32? = nil
    @TLConditional("flags", bit: 2) public var url: String? = nil
    @TLConditional("flags", bit: 4) public var matchCode: String? = nil
  }
}
