// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.reorderPinnedForumTopics#0e7841f0 flags:# force:flags.0?true peer:InputPeer order:Vector<int> = Updates`
  @TLObject(id: 0x0e7841f0, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct ReorderPinnedForumTopics: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var force: Bool = false
    public var peer: TL.InputPeerType
    public var order: [Int32]
  }
}
