// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteQuickReplyShortcut#3cc04740 shortcut_id:int = Bool`
  @TLObject(id: 0x3cc04740, returning: Bool.self)
  public struct DeleteQuickReplyShortcut: Equatable, Sendable {
    public var shortcutId: Int32
  }
}
