// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getAllDrafts#6a3f8d65 = Updates`
  @TLObject(id: 0x6a3f8d65, returning: TL.UpdatesType.self)
  public struct GetAllDrafts: Equatable, Sendable {
  }
}
