// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.editMessage#b106e66c flags:# no_webpage:flags.1?true invert_media:flags.16?true peer:InputPeer id:int message:flags.11?string media:flags.14?InputMedia reply_markup:flags.2?ReplyMarkup entities:flags.3?Vector<MessageEntity> schedule_date:flags.15?int schedule_repeat_period:flags.18?int quick_reply_shortcut_id:flags.17?int rich_message:flags.23?InputRichMessage = Updates`
  @TLObject(id: 0xb106e66c, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct EditMessage: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var noWebpage: Bool = false
    @TLConditional("flags", bit: 16) public var invertMedia: Bool = false
    public var peer: TL.InputPeerType
    public var id: Int32
    @TLConditional("flags", bit: 11) public var message: String? = nil
    @TLConditional("flags", bit: 14) public var media: TL.InputMediaType? = nil
    @TLConditional("flags", bit: 2) public var replyMarkup: TL.ReplyMarkupType? = nil
    @TLConditional("flags", bit: 3) public var entities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 15) public var scheduleDate: Int32? = nil
    @TLConditional("flags", bit: 18) public var scheduleRepeatPeriod: Int32? = nil
    @TLConditional("flags", bit: 17) public var quickReplyShortcutId: Int32? = nil
    @TLConditional("flags", bit: 23) public var richMessage: TL.InputRichMessageType? = nil
  }
}
