// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.prolongWebView#b0d81a83 flags:# silent:flags.5?true peer:InputPeer bot:InputUser query_id:long reply_to:flags.0?InputReplyTo send_as:flags.13?InputPeer = Bool`
  @TLObject(id: 0xb0d81a83, returning: Bool.self)
  @TLFlagsEquatable
  public struct ProlongWebView: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 5) public var silent: Bool = false
    public var peer: TL.InputPeerType
    public var bot: TL.InputUserType
    public var queryId: Int64
    @TLConditional("flags", bit: 0) public var replyTo: TL.InputReplyToType? = nil
    @TLConditional("flags", bit: 13) public var sendAs: TL.InputPeerType? = nil
  }
}
