// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.appendTodoList#21a61057 peer:InputPeer msg_id:int list:Vector<TodoItem> = Updates`
  @TLObject(id: 0x21a61057, returning: TL.UpdatesType.self)
  public struct AppendTodoList: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var list: [TL.TodoItem]
  }
}
