// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.hidePeerSettingsBar#4facb138 peer:InputPeer = Bool`
  @TLObject(id: 0x4facb138, returning: Bool.self)
  public struct HidePeerSettingsBar: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
