// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getPeerDialogs#e470bcfd peers:Vector<InputDialogPeer> = messages.PeerDialogs`
  @TLObject(id: 0xe470bcfd, returning: TL.Messages.PeerDialogs.self)
  public struct GetPeerDialogs: Equatable, Sendable {
    public var peers: [TL.InputDialogPeerType]
  }
}
