// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getMessageReactionsList#461b3f48 flags:# peer:InputPeer id:int reaction:flags.0?Reaction offset:flags.1?string limit:int = messages.MessageReactionsList`
  @TLObject(id: 0x461b3f48, returning: TL.Messages.MessageReactionsList.self)
  @TLFlagsEquatable
  public struct GetMessageReactionsList: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var id: Int32
    @TLConditional("flags", bit: 0) public var reaction: TL.ReactionType? = nil
    @TLConditional("flags", bit: 1) public var offset: String? = nil
    public var limit: Int32
  }
}
