// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.sendQuickReplyMessages#6c750de1 peer:InputPeer shortcut_id:int id:Vector<int> random_id:Vector<long> = Updates`
  @TLObject(id: 0x6c750de1, returning: TL.UpdatesType.self)
  public struct SendQuickReplyMessages: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var shortcutId: Int32
    public var id: [Int32]
    public var randomId: [Int64]
  }
}
