// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.setChatTheme#081202c9 peer:InputPeer theme:InputChatTheme = Updates`
  @TLObject(id: 0x081202c9, returning: TL.UpdatesType.self)
  public struct SetChatTheme: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var theme: TL.InputChatThemeType
  }
}
