// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.togglePaidReactionPrivacy#435885b5 peer:InputPeer msg_id:int private:PaidReactionPrivacy = Bool`
  @TLObject(id: 0x435885b5, returning: Bool.self)
  public struct TogglePaidReactionPrivacy: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var `private`: TL.PaidReactionPrivacyType
  }
}
