// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getSavedDialogs#1e91fc99 flags:# exclude_pinned:flags.0?true parent_peer:flags.1?InputPeer offset_date:int offset_id:int offset_peer:InputPeer limit:int hash:long = messages.SavedDialogs`
  @TLObject(id: 0x1e91fc99, returning: TL.Messages.SavedDialogsType.self)
  @TLFlagsEquatable
  public struct GetSavedDialogs: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var excludePinned: Bool = false
    @TLConditional("flags", bit: 1) public var parentPeer: TL.InputPeerType? = nil
    public var offsetDate: Int32
    public var offsetId: Int32
    public var offsetPeer: TL.InputPeerType
    public var limit: Int32
    public var hash: Int64
  }
}
