// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.checkHistoryImportPeer#5dc60f03 peer:InputPeer = messages.CheckedHistoryImportPeer`
  @TLObject(id: 0x5dc60f03, returning: TL.Messages.CheckedHistoryImportPeer.self)
  public struct CheckHistoryImportPeer: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
