// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getUnreadPollVotes#43286cf2 flags:# peer:InputPeer top_msg_id:flags.0?int offset_id:int add_offset:int limit:int max_id:int min_id:int = messages.Messages`
  @TLObject(id: 0x43286cf2, returning: TL.Messages.MessagesType.self)
  @TLFlagsEquatable
  public struct GetUnreadPollVotes: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 0) public var topMsgId: Int32? = nil
    public var offsetId: Int32
    public var addOffset: Int32
    public var limit: Int32
    public var maxId: Int32
    public var minId: Int32
  }
}
