// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.composeMessageWithAI#daecc589 flags:# proofread:flags.0?true emojify:flags.3?true text:TextWithEntities translate_to_lang:flags.1?string tone:flags.2?InputAiComposeTone = messages.ComposedMessageWithAI`
  @TLObject(id: 0xdaecc589, returning: TL.Messages.ComposedMessageWithAI.self)
  @TLFlagsEquatable
  public struct ComposeMessageWithAI: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var proofread: Bool = false
    @TLConditional("flags", bit: 3) public var emojify: Bool = false
    public var text: TL.TextWithEntities
    @TLConditional("flags", bit: 1) public var translateToLang: String? = nil
    @TLConditional("flags", bit: 2) public var tone: TL.InputAiComposeToneType? = nil
  }
}
