// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.editChatAbout#def60797 peer:InputPeer about:string = Bool`
  @TLObject(id: 0xdef60797, returning: Bool.self)
  public struct EditChatAbout: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var about: String
  }
}
