// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteParticipantReaction#e3b7f82c peer:InputPeer msg_id:int participant:InputPeer = Updates`
  @TLObject(id: 0xe3b7f82c, returning: TL.UpdatesType.self)
  public struct DeleteParticipantReaction: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var participant: TL.InputPeerType
  }
}
