// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.editExportedChatInvite#bdca2f75 flags:# revoked:flags.2?true peer:InputPeer link:string expire_date:flags.0?int usage_limit:flags.1?int request_needed:flags.3?Bool title:flags.4?string = messages.ExportedChatInvite`
  @TLObject(id: 0xbdca2f75, returning: TL.Messages.ExportedChatInviteType.self)
  @TLFlagsEquatable
  public struct EditExportedChatInvite: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var revoked: Bool = false
    public var peer: TL.InputPeerType
    public var link: String
    @TLConditional("flags", bit: 0) public var expireDate: Int32? = nil
    @TLConditional("flags", bit: 1) public var usageLimit: Int32? = nil
    @TLConditional("flags", bit: 3) public var requestNeeded: Bool? = nil
    @TLConditional("flags", bit: 4) public var title: String? = nil
  }
}
