// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.readEncryptedHistory#7f4b690a peer:InputEncryptedChat max_date:int = Bool`
  @TLObject(id: 0x7f4b690a, returning: Bool.self)
  public struct ReadEncryptedHistory: Equatable, Sendable {
    public var peer: TL.InputEncryptedChat
    public var maxDate: Int32
  }
}
