// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getStickerSet#c8a0ec74 stickerset:InputStickerSet hash:int = messages.StickerSet`
  @TLObject(id: 0xc8a0ec74, returning: TL.Messages.StickerSetType.self)
  public struct GetStickerSet: Equatable, Sendable {
    public var stickerset: TL.InputStickerSetType
    public var hash: Int32
  }
}
