// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.readDiscussion#f731a9f4 peer:InputPeer msg_id:int read_max_id:int = Bool`
  @TLObject(id: 0xf731a9f4, returning: Bool.self)
  public struct ReadDiscussion: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var readMaxId: Int32
  }
}
