// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.addPollAnswer#19bc4b6d peer:InputPeer msg_id:int answer:PollAnswer = Updates`
  @TLObject(id: 0x19bc4b6d, returning: TL.UpdatesType.self)
  public struct AddPollAnswer: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var answer: TL.PollAnswerType
  }
}
