// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.toggleStickerSets#b5052fea flags:# uninstall:flags.0?true archive:flags.1?true unarchive:flags.2?true stickersets:Vector<InputStickerSet> = Bool`
  @TLObject(id: 0xb5052fea, returning: Bool.self)
  @TLFlagsEquatable
  public struct ToggleStickerSets: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var uninstall: Bool = false
    @TLConditional("flags", bit: 1) public var archive: Bool = false
    @TLConditional("flags", bit: 2) public var unarchive: Bool = false
    public var stickersets: [TL.InputStickerSetType]
  }
}
