// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.reportMusicListen#ddbcd819 id:InputDocument listened_duration:int = Bool`
  @TLObject(id: 0xddbcd819, returning: Bool.self)
  public struct ReportMusicListen: Equatable, Sendable {
    public var id: TL.InputDocumentType
    public var listenedDuration: Int32
  }
}
