// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getSavedHistory#998ab009 flags:# parent_peer:flags.0?InputPeer peer:InputPeer offset_id:int offset_date:int add_offset:int limit:int max_id:int min_id:int hash:long = messages.Messages`
  @TLObject(id: 0x998ab009, returning: TL.Messages.MessagesType.self)
  @TLFlagsEquatable
  public struct GetSavedHistory: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var parentPeer: TL.InputPeerType? = nil
    public var peer: TL.InputPeerType
    public var offsetId: Int32
    public var offsetDate: Int32
    public var addOffset: Int32
    public var limit: Int32
    public var maxId: Int32
    public var minId: Int32
    public var hash: Int64
  }
}
