// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getChats#49e9528f id:Vector<long> = messages.Chats`
  @TLObject(id: 0x49e9528f, returning: TL.Messages.ChatsType.self)
  public struct GetChats: Equatable, Sendable {
    public var id: [Int64]
  }
}
