// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.sendVote#10ea6184 peer:InputPeer msg_id:int options:Vector<bytes> = Updates`
  @TLObject(id: 0x10ea6184, returning: TL.UpdatesType.self)
  public struct SendVote: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var options: [Data]
  }
}
