// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.receivedQueue#55a5bb66 max_qts:int = Vector<long>`
  @TLObject(id: 0x55a5bb66, returning: [Int64].self)
  public struct ReceivedQueue: Equatable, Sendable {
    public var maxQts: Int32
  }
}
