// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getSavedGifs#5cf09635 hash:long = messages.SavedGifs`
  @TLObject(id: 0x5cf09635, returning: TL.Messages.SavedGifsType.self)
  public struct GetSavedGifs: Equatable, Sendable {
    public var hash: Int64
  }
}
