// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.viewSponsoredMessage#269e3643 random_id:bytes = Bool`
  @TLObject(id: 0x269e3643, returning: Bool.self)
  public struct ViewSponsoredMessage: Equatable, Sendable {
    public var randomId: Data
  }
}
