// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getSearchResultsPositions#9c7f2f10 flags:# peer:InputPeer saved_peer_id:flags.2?InputPeer filter:MessagesFilter offset_id:int limit:int = messages.SearchResultsPositions`
  @TLObject(id: 0x9c7f2f10, returning: TL.Messages.SearchResultsPositions.self)
  @TLFlagsEquatable
  public struct GetSearchResultsPositions: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 2) public var savedPeerId: TL.InputPeerType? = nil
    public var filter: TL.MessagesFilterType
    public var offsetId: Int32
    public var limit: Int32
  }
}
