// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getEmojiGameInfo#fb7e8ca7 = messages.EmojiGameInfo`
  @TLObject(id: 0xfb7e8ca7, returning: TL.Messages.EmojiGameInfoType.self)
  public struct GetEmojiGameInfo: Equatable, Sendable {
  }
}
