// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getEmojiKeywordsLanguages#4e9963b2 lang_codes:Vector<string> = Vector<EmojiLanguage>`
  @TLObject(id: 0x4e9963b2, returning: [TL.EmojiLanguage].self)
  public struct GetEmojiKeywordsLanguages: Equatable, Sendable {
    public var langCodes: [String]
  }
}
