// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.setBotCallbackAnswer#d58f130a flags:# alert:flags.1?true query_id:long message:flags.0?string url:flags.2?string cache_time:int = Bool`
  @TLObject(id: 0xd58f130a, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetBotCallbackAnswer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var alert: Bool = false
    public var queryId: Int64
    @TLConditional("flags", bit: 0) public var message: String? = nil
    @TLConditional("flags", bit: 2) public var url: String? = nil
    public var cacheTime: Int32
  }
}
