// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.startBot#e6df7378 bot:InputUser peer:InputPeer random_id:long start_param:string = Updates`
  @TLObject(id: 0xe6df7378, returning: TL.UpdatesType.self)
  public struct StartBot: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var peer: TL.InputPeerType
    public var randomId: Int64
    public var startParam: String
  }
}
