// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.setDefaultHistoryTTL#9eb51445 period:int = Bool`
  @TLObject(id: 0x9eb51445, returning: Bool.self)
  public struct SetDefaultHistoryTTL: Equatable, Sendable {
    public var period: Int32
  }
}
