// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getMessageReadParticipants#31c1c44f peer:InputPeer msg_id:int = Vector<ReadParticipantDate>`
  @TLObject(id: 0x31c1c44f, returning: [TL.ReadParticipantDate].self)
  public struct GetMessageReadParticipants: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }
}
