// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getQuickReplyMessages#94a495c3 flags:# shortcut_id:int id:flags.0?Vector<int> hash:long = messages.Messages`
  @TLObject(id: 0x94a495c3, returning: TL.Messages.MessagesType.self)
  @TLFlagsEquatable
  public struct GetQuickReplyMessages: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var shortcutId: Int32
    @TLConditional("flags", bit: 0) public var id: [Int32]? = nil
    public var hash: Int64
  }
}
