// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getPersonalChannelHistory#55fb0996 user_id:InputUser limit:int max_id:int min_id:int hash:long = messages.Messages`
  @TLObject(id: 0x55fb0996, returning: TL.Messages.MessagesType.self)
  public struct GetPersonalChannelHistory: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var limit: Int32
    public var maxId: Int32
    public var minId: Int32
    public var hash: Int64
  }
}
