// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.searchStickers#29b1c66a flags:# emojis:flags.0?true q:string emoticon:string lang_code:Vector<string> offset:int limit:int hash:long = messages.FoundStickers`
  @TLObject(id: 0x29b1c66a, returning: TL.Messages.FoundStickersType.self)
  @TLFlagsEquatable
  public struct SearchStickers: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var emojis: Bool = false
    public var q: String
    public var emoticon: String
    public var langCode: [String]
    public var offset: Int32
    public var limit: Int32
    public var hash: Int64
  }
}
