// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.readHistory#0e306d3a peer:InputPeer max_id:int = messages.AffectedMessages`
  @TLObject(id: 0x0e306d3a, returning: TL.Messages.AffectedMessages.self)
  public struct ReadHistory: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var maxId: Int32
  }
}
