// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.editChatCreator#f743b857 peer:InputPeer user_id:InputUser password:InputCheckPasswordSRP = Updates`
  @TLObject(id: 0xf743b857, returning: TL.UpdatesType.self)
  public struct EditChatCreator: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var userId: TL.InputUserType
    public var password: TL.InputCheckPasswordSRPType
  }
}
