// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteFactCheck#d1da940c peer:InputPeer msg_id:int = Updates`
  @TLObject(id: 0xd1da940c, returning: TL.UpdatesType.self)
  public struct DeleteFactCheck: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
  }
}
