// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getMyStickers#d0b5e1fc offset_id:long limit:int = messages.MyStickers`
  @TLObject(id: 0xd0b5e1fc, returning: TL.Messages.MyStickers.self)
  public struct GetMyStickers: Equatable, Sendable {
    public var offsetId: Int64
    public var limit: Int32
  }
}
