// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteSavedHistory#4dc5085f flags:# parent_peer:flags.0?InputPeer peer:InputPeer max_id:int min_date:flags.2?int max_date:flags.3?int = messages.AffectedHistory`
  @TLObject(id: 0x4dc5085f, returning: TL.Messages.AffectedHistory.self)
  @TLFlagsEquatable
  public struct DeleteSavedHistory: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var parentPeer: TL.InputPeerType? = nil
    public var peer: TL.InputPeerType
    public var maxId: Int32
    @TLConditional("flags", bit: 2) public var minDate: Int32? = nil
    @TLConditional("flags", bit: 3) public var maxDate: Int32? = nil
  }
}
