// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteChat#5bd0ee50 chat_id:long = Bool`
  @TLObject(id: 0x5bd0ee50, returning: Bool.self)
  public struct DeleteChat: Equatable, Sendable {
    public var chatId: Int64
  }
}
