// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getDocumentByHash#b1f2061f sha256:bytes size:long mime_type:string = Document`
  @TLObject(id: 0xb1f2061f, returning: TL.DocumentType.self)
  public struct GetDocumentByHash: Equatable, Sendable {
    public var sha256: Data
    public var size: Int64
    public var mimeType: String
  }
}
