// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.setBotShippingResults#e5f672fa flags:# query_id:long error:flags.0?string shipping_options:flags.1?Vector<ShippingOption> = Bool`
  @TLObject(id: 0xe5f672fa, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetBotShippingResults: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var queryId: Int64
    @TLConditional("flags", bit: 0) public var error: String? = nil
    @TLConditional("flags", bit: 1) public var shippingOptions: [TL.ShippingOption]? = nil
  }
}
