// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.savePreparedInlineMessage#f21f7f2f flags:# result:InputBotInlineResult user_id:InputUser peer_types:flags.0?Vector<InlineQueryPeerType> = messages.BotPreparedInlineMessage`
  @TLObject(id: 0xf21f7f2f, returning: TL.Messages.BotPreparedInlineMessage.self)
  @TLFlagsEquatable
  public struct SavePreparedInlineMessage: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var result: TL.InputBotInlineResultType
    public var userId: TL.InputUserType
    @TLConditional("flags", bit: 0) public var peerTypes: [TL.InlineQueryPeerTypeType]? = nil
  }
}
