// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getEmojiStickerGroups#1dd840f5 hash:int = messages.EmojiGroups`
  @TLObject(id: 0x1dd840f5, returning: TL.Messages.EmojiGroupsType.self)
  public struct GetEmojiStickerGroups: Equatable, Sendable {
    public var hash: Int32
  }
}
