// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getFeaturedEmojiStickers#0ecf6736 hash:long = messages.FeaturedStickers`
  @TLObject(id: 0x0ecf6736, returning: TL.Messages.FeaturedStickersType.self)
  public struct GetFeaturedEmojiStickers: Equatable, Sendable {
    public var hash: Int64
  }
}
