// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.sendWebViewResultMessage#0a4314f5 bot_query_id:string result:InputBotInlineResult = WebViewMessageSent`
  @TLObject(id: 0x0a4314f5, returning: TL.WebViewMessageSent.self)
  public struct SendWebViewResultMessage: Equatable, Sendable {
    public var botQueryId: String
    public var result: TL.InputBotInlineResultType
  }
}
