// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.startHistoryImport#b43df344 peer:InputPeer import_id:long = Bool`
  @TLObject(id: 0xb43df344, returning: Bool.self)
  public struct StartHistoryImport: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var importId: Int64
  }
}
