// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getStickers#d5a5d3a1 emoticon:string hash:long = messages.Stickers`
  @TLObject(id: 0xd5a5d3a1, returning: TL.Messages.StickersType.self)
  public struct GetStickers: Equatable, Sendable {
    public var emoticon: String
    public var hash: Int64
  }
}
