// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.setEncryptedTyping#791451ed peer:InputEncryptedChat typing:Bool = Bool`
  @TLObject(id: 0x791451ed, returning: Bool.self)
  public struct SetEncryptedTyping: Equatable, Sendable {
    public var peer: TL.InputEncryptedChat
    public var typing: Bool
  }
}
