// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.importChatInvite#de91436e hash:string = messages.ChatInviteJoinResult`
  @TLObject(id: 0xde91436e, returning: TL.Messages.ChatInviteJoinResultType.self)
  public struct ImportChatInvite: Equatable, Sendable {
    public var hash: String
  }
}
