// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.receivedMessages#05a954c0 max_id:int = Vector<ReceivedNotifyMessage>`
  @TLObject(id: 0x05a954c0, returning: [TL.ReceivedNotifyMessage].self)
  public struct ReceivedMessages: Equatable, Sendable {
    public var maxId: Int32
  }
}
