// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getAttachMenuBot#77216192 bot:InputUser = AttachMenuBotsBot`
  @TLObject(id: 0x77216192, returning: TL.AttachMenuBotsBot.self)
  public struct GetAttachMenuBot: Equatable, Sendable {
    public var bot: TL.InputUserType
  }
}
