// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.requestAppWebView#53618bce flags:# write_allowed:flags.0?true compact:flags.7?true fullscreen:flags.8?true peer:InputPeer app:InputBotApp start_param:flags.1?string theme_params:flags.2?DataJSON platform:string = WebViewResult`
  @TLObject(id: 0x53618bce, returning: TL.WebViewResultUrl.self)
  @TLFlagsEquatable
  public struct RequestAppWebView: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var writeAllowed: Bool = false
    @TLConditional("flags", bit: 7) public var compact: Bool = false
    @TLConditional("flags", bit: 8) public var fullscreen: Bool = false
    public var peer: TL.InputPeerType
    public var app: TL.InputBotAppType
    @TLConditional("flags", bit: 1) public var startParam: String? = nil
    @TLConditional("flags", bit: 2) public var themeParams: TL.DataJSON? = nil
    public var platform: String
  }
}
