// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.requestChatJoinWebView#ba9ee679 flags:# query_id:long theme_params:flags.0?DataJSON platform:string = WebViewResult`
  @TLObject(id: 0xba9ee679, returning: TL.WebViewResultUrl.self)
  @TLFlagsEquatable
  public struct RequestChatJoinWebView: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var queryId: Int64
    @TLConditional("flags", bit: 0) public var themeParams: TL.DataJSON? = nil
    public var platform: String
  }
}
