// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.saveDraft#ad0fa15c flags:# no_webpage:flags.1?true invert_media:flags.6?true reply_to:flags.4?InputReplyTo peer:InputPeer message:string entities:flags.3?Vector<MessageEntity> media:flags.5?InputMedia effect:flags.7?long suggested_post:flags.8?SuggestedPost rich_message:flags.9?InputRichMessage = Bool`
  @TLObject(id: 0xad0fa15c, returning: Bool.self)
  @TLFlagsEquatable
  public struct SaveDraft: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var noWebpage: Bool = false
    @TLConditional("flags", bit: 6) public var invertMedia: Bool = false
    @TLConditional("flags", bit: 4) public var replyTo: TL.InputReplyToType? = nil
    public var peer: TL.InputPeerType
    public var message: String
    @TLConditional("flags", bit: 3) public var entities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 5) public var media: TL.InputMediaType? = nil
    @TLConditional("flags", bit: 7) public var effect: Int64? = nil
    @TLConditional("flags", bit: 8) public var suggestedPost: TL.SuggestedPost? = nil
    @TLConditional("flags", bit: 9) public var richMessage: TL.InputRichMessageType? = nil
  }
}
