// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.editChatParticipantRank#a00f32b0 peer:InputPeer participant:InputPeer rank:string = Updates`
  @TLObject(id: 0xa00f32b0, returning: TL.UpdatesType.self)
  public struct EditChatParticipantRank: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var participant: TL.InputPeerType
    public var rank: String
  }
}
