// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.readFeaturedStickers#5b118126 id:Vector<long> = Bool`
  @TLObject(id: 0x5b118126, returning: Bool.self)
  public struct ReadFeaturedStickers: Equatable, Sendable {
    public var id: [Int64]
  }
}
