// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.sendMultiMedia#1bf89d74 flags:# silent:flags.5?true background:flags.6?true clear_draft:flags.7?true noforwards:flags.14?true update_stickersets_order:flags.15?true invert_media:flags.16?true allow_paid_floodskip:flags.19?true peer:InputPeer reply_to:flags.0?InputReplyTo multi_media:Vector<InputSingleMedia> schedule_date:flags.10?int send_as:flags.13?InputPeer quick_reply_shortcut:flags.17?InputQuickReplyShortcut effect:flags.18?long allow_paid_stars:flags.21?long = Updates`
  @TLObject(id: 0x1bf89d74, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct SendMultiMedia: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 5) public var silent: Bool = false
    @TLConditional("flags", bit: 6) public var background: Bool = false
    @TLConditional("flags", bit: 7) public var clearDraft: Bool = false
    @TLConditional("flags", bit: 14) public var noforwards: Bool = false
    @TLConditional("flags", bit: 15) public var updateStickersetsOrder: Bool = false
    @TLConditional("flags", bit: 16) public var invertMedia: Bool = false
    @TLConditional("flags", bit: 19) public var allowPaidFloodskip: Bool = false
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 0) public var replyTo: TL.InputReplyToType? = nil
    public var multiMedia: [TL.InputSingleMedia]
    @TLConditional("flags", bit: 10) public var scheduleDate: Int32? = nil
    @TLConditional("flags", bit: 13) public var sendAs: TL.InputPeerType? = nil
    @TLConditional("flags", bit: 17) public var quickReplyShortcut: TL.InputQuickReplyShortcutType? = nil
    @TLConditional("flags", bit: 18) public var effect: Int64? = nil
    @TLConditional("flags", bit: 21) public var allowPaidStars: Int64? = nil
  }
}
