// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getMessagesViews#5784d3e1 peer:InputPeer id:Vector<int> increment:Bool = messages.MessageViews`
  @TLObject(id: 0x5784d3e1, returning: TL.Messages.MessageViews.self)
  public struct GetMessagesViews: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var id: [Int32]
    public var increment: Bool
  }
}
