// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.readSavedHistory#ba4a3b5b parent_peer:InputPeer peer:InputPeer max_id:int = Bool`
  @TLObject(id: 0xba4a3b5b, returning: Bool.self)
  public struct ReadSavedHistory: Equatable, Sendable {
    public var parentPeer: TL.InputPeerType
    public var peer: TL.InputPeerType
    public var maxId: Int32
  }
}
