// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.sendBotRequestedPeer#6c5cf2a7 flags:# peer:InputPeer msg_id:flags.0?int webapp_req_id:flags.1?string button_id:int requested_peers:Vector<InputPeer> = Updates`
  @TLObject(id: 0x6c5cf2a7, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct SendBotRequestedPeer: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 0) public var msgId: Int32? = nil
    @TLConditional("flags", bit: 1) public var webappReqId: String? = nil
    public var buttonId: Int32
    public var requestedPeers: [TL.InputPeerType]
  }
}
