// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getArchivedStickers#57f17692 flags:# masks:flags.0?true emojis:flags.1?true offset_id:long limit:int = messages.ArchivedStickers`
  @TLObject(id: 0x57f17692, returning: TL.Messages.ArchivedStickers.self)
  @TLFlagsEquatable
  public struct GetArchivedStickers: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var masks: Bool = false
    @TLConditional("flags", bit: 1) public var emojis: Bool = false
    public var offsetId: Int64
    public var limit: Int32
  }
}
