// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.toggleNoForwards#b2081a35 flags:# peer:InputPeer enabled:Bool request_msg_id:flags.0?int = Updates`
  @TLObject(id: 0xb2081a35, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct ToggleNoForwards: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var peer: TL.InputPeerType
    public var enabled: Bool
    @TLConditional("flags", bit: 0) public var requestMsgId: Int32? = nil
  }
}
