// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.markDialogUnread#8c5006f8 flags:# unread:flags.0?true parent_peer:flags.1?InputPeer peer:InputDialogPeer = Bool`
  @TLObject(id: 0x8c5006f8, returning: Bool.self)
  @TLFlagsEquatable
  public struct MarkDialogUnread: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var unread: Bool = false
    @TLConditional("flags", bit: 1) public var parentPeer: TL.InputPeerType? = nil
    public var peer: TL.InputDialogPeerType
  }
}
