// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getEmojiGroups#7488ce5b hash:int = messages.EmojiGroups`
  @TLObject(id: 0x7488ce5b, returning: TL.Messages.EmojiGroupsType.self)
  public struct GetEmojiGroups: Equatable, Sendable {
    public var hash: Int32
  }
}
