// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.rateTranscribedAudio#7f1d072f peer:InputPeer msg_id:int transcription_id:long good:Bool = Bool`
  @TLObject(id: 0x7f1d072f, returning: Bool.self)
  public struct RateTranscribedAudio: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var msgId: Int32
    public var transcriptionId: Int64
    public var good: Bool
  }
}
