// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.deleteTopicHistory#d2816f10 peer:InputPeer top_msg_id:int = messages.AffectedHistory`
  @TLObject(id: 0xd2816f10, returning: TL.Messages.AffectedHistory.self)
  public struct DeleteTopicHistory: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var topMsgId: Int32
  }
}
