// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.getForumTopicsByID#af0a4a08 peer:InputPeer topics:Vector<int> = messages.ForumTopics`
  @TLObject(id: 0xaf0a4a08, returning: TL.Messages.ForumTopics.self)
  public struct GetForumTopicsByID: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var topics: [Int32]
  }
}
