// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Messages {

  /// TL: `messages.report#fc78af9b peer:InputPeer id:Vector<int> option:bytes message:string = ReportResult`
  @TLObject(id: 0xfc78af9b, returning: TL.ReportResultType.self)
  public struct Report: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var id: [Int32]
    public var option: Data
    public var message: String
  }
}
