// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `invokeWithoutUpdates#bf9459b7 query:!X = X`
  @TLObject(id: 0xbf9459b7)
  public struct InvokeWithoutUpdates<Query: TLFunction>: TLFunction, Sendable {
    public typealias ReturnType = Query.ReturnType
    public var query: Query
  }
}
