// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `invokeWithGooglePlayIntegrity#1df92984 nonce:string token:string query:!X = X`
  @TLObject(id: 0x1df92984)
  public struct InvokeWithGooglePlayIntegrity<Query: TLFunction>: TLFunction, Sendable {
    public typealias ReturnType = Query.ReturnType
    public var nonce: String
    public var token: String
    public var query: Query
  }
}
