// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `invokeAfterMsg#cb9f372d msg_id:long query:!X = X`
  @TLObject(id: 0xcb9f372d)
  public struct InvokeAfterMsg<Query: TLFunction>: TLFunction, Sendable {
    public typealias ReturnType = Query.ReturnType
    public var msgId: Int64
    public var query: Query
  }
}
