// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `invokeWithApnsSecret#0dae54f8 nonce:string secret:string query:!X = X`
  @TLObject(id: 0x0dae54f8)
  public struct InvokeWithApnsSecret<Query: TLFunction>: TLFunction, Sendable {
    public typealias ReturnType = Query.ReturnType
    public var nonce: String
    public var secret: String
    public var query: Query
  }
}
