// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `invokeWithReCaptcha#adbb0f94 token:string query:!X = X`
  @TLObject(id: 0xadbb0f94)
  public struct InvokeWithReCaptcha<Query: TLFunction>: TLFunction, Sendable {
    public typealias ReturnType = Query.ReturnType
    public var token: String
    public var query: Query
  }
}
