// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Ephemeral {

  /// TL: `ephemeral.editMessage#cf9c725b flags:# invert_media:flags.5?true welcome:flags.6?true peer:flags.7?InputPeer receiver_id:InputUser id:int message:flags.0?string media:flags.3?InputMedia entities:flags.1?Vector<MessageEntity> reply_markup:flags.2?ReplyMarkup rich_message:flags.4?InputRichMessage = Updates`
  @TLObject(id: 0xcf9c725b, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct EditMessage: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 5) public var invertMedia: Bool = false
    @TLConditional("flags", bit: 6) public var welcome: Bool = false
    @TLConditional("flags", bit: 7) public var peer: TL.InputPeerType? = nil
    public var receiverId: TL.InputUserType
    public var id: Int32
    @TLConditional("flags", bit: 0) public var message: String? = nil
    @TLConditional("flags", bit: 3) public var media: TL.InputMediaType? = nil
    @TLConditional("flags", bit: 1) public var entities: [TL.MessageEntityType]? = nil
    @TLConditional("flags", bit: 2) public var replyMarkup: TL.ReplyMarkupType? = nil
    @TLConditional("flags", bit: 4) public var richMessage: TL.InputRichMessageType? = nil
  }
}
