// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsHelp
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `help.*` methods.
  public var help: HelpMethods {
    HelpMethods(client: self)
  }
  /// The `help.*` methods of a `TLClient`.
  public struct HelpMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `help.getConfig#c4f9186b = Config`
    public func getConfig() async throws -> TL.Config {
      try await client.invoke(TL.Help.GetConfig())
    }
    /// TL: `help.getNearestDc#1fb33026 = NearestDc`
    public func getNearestDc() async throws -> TL.NearestDc {
      try await client.invoke(TL.Help.GetNearestDc())
    }
    /// TL: `help.getAppUpdate#522d5a7d source:string = help.AppUpdate`
    public func getAppUpdate(source: String) async throws -> TL.Help.AppUpdateType {
      try await client.invoke(TL.Help.GetAppUpdate(source: source))
    }
    /// TL: `help.getInviteText#4d392343 = help.InviteText`
    public func getInviteText() async throws -> TL.Help.InviteText {
      try await client.invoke(TL.Help.GetInviteText())
    }
    /// TL: `help.getSupport#9cdf08cd = help.Support`
    public func getSupport() async throws -> TL.Help.Support {
      try await client.invoke(TL.Help.GetSupport())
    }
    /// TL: `help.setBotUpdatesStatus#ec22cfcd pending_updates_count:int message:string = Bool`
    public func setBotUpdatesStatus(pendingUpdatesCount: Int32, message: String) async throws -> Bool {
      try await client.invoke(TL.Help.SetBotUpdatesStatus(pendingUpdatesCount: pendingUpdatesCount, message: message))
    }
    /// TL: `help.getCdnConfig#52029342 = CdnConfig`
    public func getCdnConfig() async throws -> TL.CdnConfig {
      try await client.invoke(TL.Help.GetCdnConfig())
    }
    /// TL: `help.getRecentMeUrls#3dc0f114 referer:string = help.RecentMeUrls`
    public func getRecentMeUrls(referer: String) async throws -> TL.Help.RecentMeUrls {
      try await client.invoke(TL.Help.GetRecentMeUrls(referer: referer))
    }
    /// TL: `help.getTermsOfServiceUpdate#2ca51fd1 = help.TermsOfServiceUpdate`
    public func getTermsOfServiceUpdate() async throws -> TL.Help.TermsOfServiceUpdateType {
      try await client.invoke(TL.Help.GetTermsOfServiceUpdate())
    }
    /// TL: `help.acceptTermsOfService#ee72f79a id:DataJSON = Bool`
    public func acceptTermsOfService(id: TL.DataJSON) async throws -> Bool {
      try await client.invoke(TL.Help.AcceptTermsOfService(id: id))
    }
    /// TL: `help.getDeepLinkInfo#3fedc75f path:string = help.DeepLinkInfo`
    public func getDeepLinkInfo(path: String) async throws -> TL.Help.DeepLinkInfoType {
      try await client.invoke(TL.Help.GetDeepLinkInfo(path: path))
    }
    /// TL: `help.getAppConfig#61e3f854 hash:int = help.AppConfig`
    public func getAppConfig(hash: Int32) async throws -> TL.Help.AppConfigType {
      try await client.invoke(TL.Help.GetAppConfig(hash: hash))
    }
    /// TL: `help.saveAppLog#6f02f748 events:Vector<InputAppEvent> = Bool`
    public func saveAppLog(events: [TL.InputAppEvent]) async throws -> Bool {
      try await client.invoke(TL.Help.SaveAppLog(events: events))
    }
    /// TL: `help.getPassportConfig#c661ad08 hash:int = help.PassportConfig`
    public func getPassportConfig(hash: Int32) async throws -> TL.Help.PassportConfigType {
      try await client.invoke(TL.Help.GetPassportConfig(hash: hash))
    }
    /// TL: `help.getSupportName#d360e72c = help.SupportName`
    public func getSupportName() async throws -> TL.Help.SupportName {
      try await client.invoke(TL.Help.GetSupportName())
    }
    /// TL: `help.getUserInfo#038a08d3 user_id:InputUser = help.UserInfo`
    public func getUserInfo(userId: TL.InputUserType) async throws -> TL.Help.UserInfoType {
      try await client.invoke(TL.Help.GetUserInfo(userId: userId))
    }
    /// TL: `help.editUserInfo#66b91b70 user_id:InputUser message:string entities:Vector<MessageEntity> = help.UserInfo`
    public func editUserInfo(userId: TL.InputUserType, message: String, entities: [TL.MessageEntityType]) async throws -> TL.Help.UserInfoType {
      try await client.invoke(TL.Help.EditUserInfo(userId: userId, message: message, entities: entities))
    }
    /// TL: `help.getPromoData#c0977421 = help.PromoData`
    public func getPromoData() async throws -> TL.Help.PromoDataType {
      try await client.invoke(TL.Help.GetPromoData())
    }
    /// TL: `help.hidePromoData#1e251c95 peer:InputPeer = Bool`
    public func hidePromoData(peer: TL.InputPeerType) async throws -> Bool {
      try await client.invoke(TL.Help.HidePromoData(peer: peer))
    }
    /// TL: `help.dismissSuggestion#f50dbaa1 peer:InputPeer suggestion:string = Bool`
    public func dismissSuggestion(peer: TL.InputPeerType, suggestion: String) async throws -> Bool {
      try await client.invoke(TL.Help.DismissSuggestion(peer: peer, suggestion: suggestion))
    }
    /// TL: `help.getCountriesList#735787a8 lang_code:string hash:int = help.CountriesList`
    public func getCountriesList(langCode: String, hash: Int32) async throws -> TL.Help.CountriesListType {
      try await client.invoke(TL.Help.GetCountriesList(langCode: langCode, hash: hash))
    }
    /// TL: `help.getPremiumPromo#b81b93d4 = help.PremiumPromo`
    public func getPremiumPromo() async throws -> TL.Help.PremiumPromo {
      try await client.invoke(TL.Help.GetPremiumPromo())
    }
    /// TL: `help.getPeerColors#da80f42f hash:int = help.PeerColors`
    public func getPeerColors(hash: Int32) async throws -> TL.Help.PeerColorsType {
      try await client.invoke(TL.Help.GetPeerColors(hash: hash))
    }
    /// TL: `help.getPeerProfileColors#abcfa9fd hash:int = help.PeerColors`
    public func getPeerProfileColors(hash: Int32) async throws -> TL.Help.PeerColorsType {
      try await client.invoke(TL.Help.GetPeerProfileColors(hash: hash))
    }
    /// TL: `help.getTimezonesList#49b30240 hash:int = help.TimezonesList`
    public func getTimezonesList(hash: Int32) async throws -> TL.Help.TimezonesListType {
      try await client.invoke(TL.Help.GetTimezonesList(hash: hash))
    }
  }
}
