// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsAuth
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `auth.*` methods.
  public var auth: AuthMethods {
    AuthMethods(client: self)
  }
  /// The `auth.*` methods of a `TLClient`.
  public struct AuthMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `auth.sendCode#a677244f phone_number:string api_id:int api_hash:string settings:CodeSettings = auth.SentCode`
    public func sendCode(phoneNumber: String, apiId: Int32, apiHash: String, settings: TL.CodeSettings) async throws -> TL.Auth.SentCodeType {
      try await client.invoke(TL.Auth.SendCode(phoneNumber: phoneNumber, apiId: apiId, apiHash: apiHash, settings: settings))
    }
    /// TL: `auth.signUp#aac7b717 flags:# no_joined_notifications:flags.0?true phone_number:string phone_code_hash:string first_name:string last_name:string = auth.Authorization`
    public func signUp(noJoinedNotifications: Bool = false, phoneNumber: String, phoneCodeHash: String, firstName: String, lastName: String) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.SignUp(noJoinedNotifications: noJoinedNotifications, phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, firstName: firstName, lastName: lastName))
    }
    /// TL: `auth.signIn#8d52a951 flags:# phone_number:string phone_code_hash:string phone_code:flags.0?string email_verification:flags.1?EmailVerification = auth.Authorization`
    public func signIn(phoneNumber: String, phoneCodeHash: String, phoneCode: String? = nil, emailVerification: TL.EmailVerificationType? = nil) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.SignIn(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, phoneCode: phoneCode, emailVerification: emailVerification))
    }
    /// TL: `auth.logOut#3e72ba19 = auth.LoggedOut`
    public func logOut() async throws -> TL.Auth.LoggedOut {
      try await client.invoke(TL.Auth.LogOut())
    }
    /// TL: `auth.resetAuthorizations#9fab0d1a = Bool`
    public func resetAuthorizations() async throws -> Bool {
      try await client.invoke(TL.Auth.ResetAuthorizations())
    }
    /// TL: `auth.exportAuthorization#e5bfffcd dc_id:int = auth.ExportedAuthorization`
    public func exportAuthorization(dcId: Int32) async throws -> TL.Auth.ExportedAuthorization {
      try await client.invoke(TL.Auth.ExportAuthorization(dcId: dcId))
    }
    /// TL: `auth.importAuthorization#a57a7dad id:long bytes:bytes = auth.Authorization`
    public func importAuthorization(id: Int64, bytes: Data) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.ImportAuthorization(id: id, bytes: bytes))
    }
    /// TL: `auth.bindTempAuthKey#cdd42a05 perm_auth_key_id:long nonce:long expires_at:int encrypted_message:bytes = Bool`
    public func bindTempAuthKey(permAuthKeyId: Int64, nonce: Int64, expiresAt: Int32, encryptedMessage: Data) async throws -> Bool {
      try await client.invoke(TL.Auth.BindTempAuthKey(permAuthKeyId: permAuthKeyId, nonce: nonce, expiresAt: expiresAt, encryptedMessage: encryptedMessage))
    }
    /// TL: `auth.importBotAuthorization#67a3ff2c flags:int api_id:int api_hash:string bot_auth_token:string = auth.Authorization`
    public func importBotAuthorization(flags: Int32, apiId: Int32, apiHash: String, botAuthToken: String) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.ImportBotAuthorization(flags: flags, apiId: apiId, apiHash: apiHash, botAuthToken: botAuthToken))
    }
    /// TL: `auth.checkPassword#d18b4d16 password:InputCheckPasswordSRP = auth.Authorization`
    public func checkPassword(password: TL.InputCheckPasswordSRPType) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.CheckPassword(password: password))
    }
    /// TL: `auth.requestPasswordRecovery#d897bc66 = auth.PasswordRecovery`
    public func requestPasswordRecovery() async throws -> TL.Auth.PasswordRecovery {
      try await client.invoke(TL.Auth.RequestPasswordRecovery())
    }
    /// TL: `auth.recoverPassword#37096c70 flags:# code:string new_settings:flags.0?account.PasswordInputSettings = auth.Authorization`
    public func recoverPassword(code: String, newSettings: TL.Account.PasswordInputSettings? = nil) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.RecoverPassword(code: code, newSettings: newSettings))
    }
    /// TL: `auth.resendCode#cae47523 flags:# phone_number:string phone_code_hash:string reason:flags.0?string = auth.SentCode`
    public func resendCode(phoneNumber: String, phoneCodeHash: String, reason: String? = nil) async throws -> TL.Auth.SentCodeType {
      try await client.invoke(TL.Auth.ResendCode(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, reason: reason))
    }
    /// TL: `auth.cancelCode#1f040578 phone_number:string phone_code_hash:string = Bool`
    public func cancelCode(phoneNumber: String, phoneCodeHash: String) async throws -> Bool {
      try await client.invoke(TL.Auth.CancelCode(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash))
    }
    /// TL: `auth.dropTempAuthKeys#8e48a188 except_auth_keys:Vector<long> = Bool`
    public func dropTempAuthKeys(exceptAuthKeys: [Int64]) async throws -> Bool {
      try await client.invoke(TL.Auth.DropTempAuthKeys(exceptAuthKeys: exceptAuthKeys))
    }
    /// TL: `auth.exportLoginToken#b7e085fe api_id:int api_hash:string except_ids:Vector<long> = auth.LoginToken`
    public func exportLoginToken(apiId: Int32, apiHash: String, exceptIds: [Int64]) async throws -> TL.Auth.LoginTokenType {
      try await client.invoke(TL.Auth.ExportLoginToken(apiId: apiId, apiHash: apiHash, exceptIds: exceptIds))
    }
    /// TL: `auth.importLoginToken#95ac5ce4 token:bytes = auth.LoginToken`
    public func importLoginToken(token: Data) async throws -> TL.Auth.LoginTokenType {
      try await client.invoke(TL.Auth.ImportLoginToken(token: token))
    }
    /// TL: `auth.acceptLoginToken#e894ad4d token:bytes = Authorization`
    public func acceptLoginToken(token: Data) async throws -> TL.Authorization {
      try await client.invoke(TL.Auth.AcceptLoginToken(token: token))
    }
    /// TL: `auth.checkRecoveryPassword#0d36bf79 code:string = Bool`
    public func checkRecoveryPassword(code: String) async throws -> Bool {
      try await client.invoke(TL.Auth.CheckRecoveryPassword(code: code))
    }
    /// TL: `auth.importWebTokenAuthorization#2db873a9 api_id:int api_hash:string web_auth_token:string = auth.Authorization`
    public func importWebTokenAuthorization(apiId: Int32, apiHash: String, webAuthToken: String) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.ImportWebTokenAuthorization(apiId: apiId, apiHash: apiHash, webAuthToken: webAuthToken))
    }
    /// TL: `auth.requestFirebaseSms#8e39261e flags:# phone_number:string phone_code_hash:string safety_net_token:flags.0?string play_integrity_token:flags.2?string ios_push_secret:flags.1?string = Bool`
    public func requestFirebaseSms(phoneNumber: String, phoneCodeHash: String, safetyNetToken: String? = nil, playIntegrityToken: String? = nil, iosPushSecret: String? = nil) async throws -> Bool {
      try await client.invoke(TL.Auth.RequestFirebaseSms(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, safetyNetToken: safetyNetToken, playIntegrityToken: playIntegrityToken, iosPushSecret: iosPushSecret))
    }
    /// TL: `auth.resetLoginEmail#7e960193 phone_number:string phone_code_hash:string = auth.SentCode`
    public func resetLoginEmail(phoneNumber: String, phoneCodeHash: String) async throws -> TL.Auth.SentCodeType {
      try await client.invoke(TL.Auth.ResetLoginEmail(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash))
    }
    /// TL: `auth.reportMissingCode#cb9deff6 phone_number:string phone_code_hash:string mnc:string = Bool`
    public func reportMissingCode(phoneNumber: String, phoneCodeHash: String, mnc: String) async throws -> Bool {
      try await client.invoke(TL.Auth.ReportMissingCode(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, mnc: mnc))
    }
    /// TL: `auth.checkPaidAuth#56e59f9c phone_number:string phone_code_hash:string form_id:long = auth.SentCode`
    public func checkPaidAuth(phoneNumber: String, phoneCodeHash: String, formId: Int64) async throws -> TL.Auth.SentCodeType {
      try await client.invoke(TL.Auth.CheckPaidAuth(phoneNumber: phoneNumber, phoneCodeHash: phoneCodeHash, formId: formId))
    }
    /// TL: `auth.initPasskeyLogin#518ad0b7 api_id:int api_hash:string = auth.PasskeyLoginOptions`
    public func initPasskeyLogin(apiId: Int32, apiHash: String) async throws -> TL.Auth.PasskeyLoginOptions {
      try await client.invoke(TL.Auth.InitPasskeyLogin(apiId: apiId, apiHash: apiHash))
    }
    /// TL: `auth.finishPasskeyLogin#9857ad07 flags:# credential:InputPasskeyCredential from_dc_id:flags.0?int from_auth_key_id:flags.0?long = auth.Authorization`
    public func finishPasskeyLogin(credential: TL.InputPasskeyCredentialType, fromDcId: Int32? = nil, fromAuthKeyId: Int64? = nil) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.FinishPasskeyLogin(credential: credential, fromDcId: fromDcId, fromAuthKeyId: fromAuthKeyId))
    }
    /// TL: `auth.initFirebasePnvLogin#777df37a api_id:int api_hash:string = auth.FirebasePnvIntent`
    public func initFirebasePnvLogin(apiId: Int32, apiHash: String) async throws -> TL.Auth.FirebasePnvIntent {
      try await client.invoke(TL.Auth.InitFirebasePnvLogin(apiId: apiId, apiHash: apiHash))
    }
    /// TL: `auth.finishFirebasePnvLogin#2c85094c google_token:string = auth.Authorization`
    public func finishFirebasePnvLogin(googleToken: String) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.FinishFirebasePnvLogin(googleToken: googleToken))
    }
    /// TL: `auth.firebasePnvSignUp#783f6b56 flags:# no_joined_notifications:flags.0?true first_name:string last_name:string = auth.Authorization`
    public func firebasePnvSignUp(noJoinedNotifications: Bool = false, firstName: String, lastName: String) async throws -> TL.Auth.AuthorizationType {
      try await client.invoke(TL.Auth.FirebasePnvSignUp(noJoinedNotifications: noJoinedNotifications, firstName: firstName, lastName: lastName))
    }
  }
}
