// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsAicompose
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `aicompose.*` methods.
  public var aicompose: AicomposeMethods {
    AicomposeMethods(client: self)
  }
  /// The `aicompose.*` methods of a `TLClient`.
  public struct AicomposeMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `aicompose.createTone#4aa83913 flags:# display_author:flags.0?true emoji_id:long title:string prompt:string = AiComposeTone`
    public func createTone(displayAuthor: Bool = false, emojiId: Int64, title: String, prompt: String) async throws -> TL.AiComposeToneType {
      try await client.invoke(TL.Aicompose.CreateTone(displayAuthor: displayAuthor, emojiId: emojiId, title: title, prompt: prompt))
    }
    /// TL: `aicompose.updateTone#903bcf59 flags:# tone:InputAiComposeTone display_author:flags.0?Bool emoji_id:flags.1?long title:flags.2?string prompt:flags.3?string = AiComposeTone`
    public func updateTone(tone: TL.InputAiComposeToneType, displayAuthor: Bool? = nil, emojiId: Int64? = nil, title: String? = nil, prompt: String? = nil) async throws -> TL.AiComposeToneType {
      try await client.invoke(TL.Aicompose.UpdateTone(tone: tone, displayAuthor: displayAuthor, emojiId: emojiId, title: title, prompt: prompt))
    }
    /// TL: `aicompose.saveTone#1782cbb1 tone:InputAiComposeTone unsave:Bool = Bool`
    public func saveTone(tone: TL.InputAiComposeToneType, unsave: Bool) async throws -> Bool {
      try await client.invoke(TL.Aicompose.SaveTone(tone: tone, unsave: unsave))
    }
    /// TL: `aicompose.deleteTone#dd39316a tone:InputAiComposeTone = Bool`
    public func deleteTone(tone: TL.InputAiComposeToneType) async throws -> Bool {
      try await client.invoke(TL.Aicompose.DeleteTone(tone: tone))
    }
    /// TL: `aicompose.getTone#b2e8ba03 tone:InputAiComposeTone = aicompose.Tones`
    public func getTone(tone: TL.InputAiComposeToneType) async throws -> TL.Aicompose.TonesType {
      try await client.invoke(TL.Aicompose.GetTone(tone: tone))
    }
    /// TL: `aicompose.getTones#abd59201 hash:long = aicompose.Tones`
    public func getTones(hash: Int64) async throws -> TL.Aicompose.TonesType {
      try await client.invoke(TL.Aicompose.GetTones(hash: hash))
    }
    /// TL: `aicompose.getToneExample#d1b4ab14 tone:InputAiComposeTone num:int = AiComposeToneExample`
    public func getToneExample(tone: TL.InputAiComposeToneType, num: Int32) async throws -> TL.AiComposeToneExample {
      try await client.invoke(TL.Aicompose.GetToneExample(tone: tone, num: num))
    }
  }
}
