// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Aicompose {

  /// TL: `aicompose.updateTone#903bcf59 flags:# tone:InputAiComposeTone display_author:flags.0?Bool emoji_id:flags.1?long title:flags.2?string prompt:flags.3?string = AiComposeTone`
  @TLObject(id: 0x903bcf59, returning: TL.AiComposeToneType.self)
  @TLFlagsEquatable
  public struct UpdateTone: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    public var tone: TL.InputAiComposeToneType
    @TLConditional("flags", bit: 0) public var displayAuthor: Bool? = nil
    @TLConditional("flags", bit: 1) public var emojiId: Int64? = nil
    @TLConditional("flags", bit: 2) public var title: String? = nil
    @TLConditional("flags", bit: 3) public var prompt: String? = nil
  }
}
