// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Aicompose {

  /// TL: `aicompose.getTone#b2e8ba03 tone:InputAiComposeTone = aicompose.Tones`
  @TLObject(id: 0xb2e8ba03, returning: TL.Aicompose.TonesType.self)
  public struct GetTone: Equatable, Sendable {
    public var tone: TL.InputAiComposeToneType
  }
}
