// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Aicompose {

  /// TL: `aicompose.getToneExample#d1b4ab14 tone:InputAiComposeTone num:int = AiComposeToneExample`
  @TLObject(id: 0xd1b4ab14, returning: TL.AiComposeToneExample.self)
  public struct GetToneExample: Equatable, Sendable {
    public var tone: TL.InputAiComposeToneType
    public var num: Int32
  }
}
