// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Chatlists {

  /// TL: `chatlists.exportChatlistInvite#8472478e chatlist:InputChatlist title:string peers:Vector<InputPeer> = chatlists.ExportedChatlistInvite`
  @TLObject(id: 0x8472478e, returning: TL.Chatlists.ExportedChatlistInvite.self)
  public struct ExportChatlistInvite: Equatable, Sendable {
    public var chatlist: TL.InputChatlistDialogFilter
    public var title: String
    public var peers: [TL.InputPeerType]
  }
}
