// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Chatlists {

  /// TL: `chatlists.getLeaveChatlistSuggestions#fdbcd714 chatlist:InputChatlist = Vector<Peer>`
  @TLObject(id: 0xfdbcd714, returning: [TL.PeerType].self)
  public struct GetLeaveChatlistSuggestions: Equatable, Sendable {
    public var chatlist: TL.InputChatlistDialogFilter
  }
}
