// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Chatlists {

  /// TL: `chatlists.checkChatlistInvite#41c10fff slug:string = chatlists.ChatlistInvite`
  @TLObject(id: 0x41c10fff, returning: TL.Chatlists.ChatlistInviteType.self)
  public struct CheckChatlistInvite: Equatable, Sendable {
    public var slug: String
  }
}
