// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Chatlists {

  /// TL: `chatlists.leaveChatlist#74fae13a chatlist:InputChatlist peers:Vector<InputPeer> = Updates`
  @TLObject(id: 0x74fae13a, returning: TL.UpdatesType.self)
  public struct LeaveChatlist: Equatable, Sendable {
    public var chatlist: TL.InputChatlistDialogFilter
    public var peers: [TL.InputPeerType]
  }
}
