// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Communities {

  /// TL: `communities.toggleCommunityCollapsedInDialogs#d766e3ea flags:# collapsed:flags.0?true community:InputChannel = Updates`
  @TLObject(id: 0xd766e3ea, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct ToggleCommunityCollapsedInDialogs: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var collapsed: Bool = false
    public var community: TL.InputChannelType
  }
}
