// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Updates {

  /// TL: `updates.getChannelDifference#03173d78 flags:# force:flags.0?true channel:InputChannel filter:ChannelMessagesFilter pts:int limit:int = updates.ChannelDifference`
  @TLObject(id: 0x03173d78, returning: TL.Updates.ChannelDifferenceType.self)
  @TLFlagsEquatable
  public struct GetChannelDifference: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var force: Bool = false
    public var channel: TL.InputChannelType
    public var filter: TL.ChannelMessagesFilterType
    public var pts: Int32
    public var limit: Int32
  }
}
