// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Updates {

  /// TL: `updates.getState#edd4882a = updates.State`
  @TLObject(id: 0xedd4882a, returning: TL.Updates.State.self)
  public struct GetState: Equatable, Sendable {
  }
}
