// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsPhotos
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `photos.*` methods.
  public var photos: PhotosMethods {
    PhotosMethods(client: self)
  }
  /// The `photos.*` methods of a `TLClient`.
  public struct PhotosMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `photos.updateProfilePhoto#09e82039 flags:# fallback:flags.0?true bot:flags.1?InputUser id:InputPhoto = photos.Photo`
    public func updateProfilePhoto(fallback: Bool = false, bot: TL.InputUserType? = nil, id: TL.InputPhotoType) async throws -> TL.Photos.Photo {
      try await client.invoke(TL.Photos.UpdateProfilePhoto(fallback: fallback, bot: bot, id: id))
    }
    /// TL: `photos.uploadProfilePhoto#0388a3b5 flags:# fallback:flags.3?true bot:flags.5?InputUser file:flags.0?InputFile video:flags.1?InputFile video_start_ts:flags.2?double video_emoji_markup:flags.4?VideoSize = photos.Photo`
    public func uploadProfilePhoto(fallback: Bool = false, bot: TL.InputUserType? = nil, file: TL.InputFileType? = nil, video: TL.InputFileType? = nil, videoStartTs: Double? = nil, videoEmojiMarkup: TL.VideoSizeType? = nil) async throws -> TL.Photos.Photo {
      try await client.invoke(TL.Photos.UploadProfilePhoto(fallback: fallback, bot: bot, file: file, video: video, videoStartTs: videoStartTs, videoEmojiMarkup: videoEmojiMarkup))
    }
    /// TL: `photos.deletePhotos#87cf7f2f id:Vector<InputPhoto> = Vector<long>`
    public func deletePhotos(id: [TL.InputPhotoType]) async throws -> [Int64] {
      try await client.invoke(TL.Photos.DeletePhotos(id: id))
    }
    /// TL: `photos.getUserPhotos#91cd32a8 user_id:InputUser offset:int max_id:long limit:int = photos.Photos`
    public func getUserPhotos(userId: TL.InputUserType, offset: Int32, maxId: Int64, limit: Int32) async throws -> TL.Photos.PhotosType {
      try await client.invoke(TL.Photos.GetUserPhotos(userId: userId, offset: offset, maxId: maxId, limit: limit))
    }
    /// TL: `photos.uploadContactProfilePhoto#e14c4a71 flags:# suggest:flags.3?true save:flags.4?true user_id:InputUser file:flags.0?InputFile video:flags.1?InputFile video_start_ts:flags.2?double video_emoji_markup:flags.5?VideoSize = photos.Photo`
    public func uploadContactProfilePhoto(suggest: Bool = false, save: Bool = false, userId: TL.InputUserType, file: TL.InputFileType? = nil, video: TL.InputFileType? = nil, videoStartTs: Double? = nil, videoEmojiMarkup: TL.VideoSizeType? = nil) async throws -> TL.Photos.Photo {
      try await client.invoke(TL.Photos.UploadContactProfilePhoto(suggest: suggest, save: save, userId: userId, file: file, video: video, videoStartTs: videoStartTs, videoEmojiMarkup: videoEmojiMarkup))
    }
  }
}
