// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.receivedCall#17d54f61 peer:InputPhoneCall = Bool`
  @TLObject(id: 0x17d54f61, returning: Bool.self)
  public struct ReceivedCall: Equatable, Sendable {
    public var peer: TL.InputPhoneCall
  }
}
