// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.saveDefaultGroupCallJoinAs#575e1f8c peer:InputPeer join_as:InputPeer = Bool`
  @TLObject(id: 0x575e1f8c, returning: Bool.self)
  public struct SaveDefaultGroupCallJoinAs: Equatable, Sendable {
    public var peer: TL.InputPeerType
    public var joinAs: TL.InputPeerType
  }
}
