// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.toggleGroupCallRecord#f128c708 flags:# start:flags.0?true video:flags.2?true call:InputGroupCall title:flags.1?string video_portrait:flags.2?Bool = Updates`
  @TLObject(id: 0xf128c708, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct ToggleGroupCallRecord: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var start: Bool = false
    @TLConditional("flags", bit: 2) public var video: Bool = false
    public var call: TL.InputGroupCallType
    @TLConditional("flags", bit: 1) public var title: String? = nil
    @TLConditional("flags", bit: 2) public var videoPortrait: Bool? = nil
  }
}
