// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.setCallRating#59ead627 flags:# user_initiative:flags.0?true peer:InputPhoneCall rating:int comment:string = Updates`
  @TLObject(id: 0x59ead627, returning: TL.UpdatesType.self)
  @TLFlagsEquatable
  public struct SetCallRating: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var userInitiative: Bool = false
    public var peer: TL.InputPhoneCall
    public var rating: Int32
    public var comment: String
  }
}
