// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.getCallConfig#55451fa9 = DataJSON`
  @TLObject(id: 0x55451fa9, returning: TL.DataJSON.self)
  public struct GetCallConfig: Equatable, Sendable {
  }
}
