// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.checkGroupCall#b59cf977 call:InputGroupCall sources:Vector<int> = Vector<int>`
  @TLObject(id: 0xb59cf977, returning: [Int32].self)
  public struct CheckGroupCall: Equatable, Sendable {
    public var call: TL.InputGroupCallType
    public var sources: [Int32]
  }
}
