// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.requestCall#42ff96ed flags:# video:flags.0?true user_id:InputUser random_id:int g_a_hash:bytes protocol:PhoneCallProtocol = phone.PhoneCall`
  @TLObject(id: 0x42ff96ed, returning: TL.Phone.PhoneCall.self)
  @TLFlagsEquatable
  public struct RequestCall: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var video: Bool = false
    public var userId: TL.InputUserType
    public var randomId: Int32
    public var gAHash: Data
    public var `protocol`: TL.PhoneCallProtocol
  }
}
