// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.confirmCall#2efe1722 peer:InputPhoneCall g_a:bytes key_fingerprint:long protocol:PhoneCallProtocol = phone.PhoneCall`
  @TLObject(id: 0x2efe1722, returning: TL.Phone.PhoneCall.self)
  public struct ConfirmCall: Equatable, Sendable {
    public var peer: TL.InputPhoneCall
    public var gA: Data
    public var keyFingerprint: Int64
    public var `protocol`: TL.PhoneCallProtocol
  }
}
