// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.getGroupCallJoinAs#ef7c213a peer:InputPeer = phone.JoinAsPeers`
  @TLObject(id: 0xef7c213a, returning: TL.Phone.JoinAsPeers.self)
  public struct GetGroupCallJoinAs: Equatable, Sendable {
    public var peer: TL.InputPeerType
  }
}
