// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.exportGroupCallInvite#e6aa647f flags:# can_self_unmute:flags.0?true call:InputGroupCall = phone.ExportedGroupCallInvite`
  @TLObject(id: 0xe6aa647f, returning: TL.Phone.ExportedGroupCallInvite.self)
  @TLFlagsEquatable
  public struct ExportGroupCallInvite: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var canSelfUnmute: Bool = false
    public var call: TL.InputGroupCallType
  }
}
