// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Phone {

  /// TL: `phone.joinGroupCallPresentation#cbea6bc4 call:InputGroupCall params:DataJSON = Updates`
  @TLObject(id: 0xcbea6bc4, returning: TL.UpdatesType.self)
  public struct JoinGroupCallPresentation: Equatable, Sendable {
    public var call: TL.InputGroupCallType
    public var params: TL.DataJSON
  }
}
