#!/usr/bin/env bash
# Regenerates Sources/TelegramSchema from a TL schema.
#
# The committed Schemas/api.json is the pinned source of truth: it is what the
# checked-in Swift was generated from, so a plain run reproduces the tree
# byte-for-byte and a diff means someone edited generated code by hand.
#
# Usage:
#   Scripts/generate-schema.sh                      # regenerate from Schemas/api.json
#   Scripts/generate-schema.sh --fetch --layer 229  # re-pin from Telegram's published schema
#   Scripts/generate-schema.sh --from-mtcute <dir>  # re-pin from an mtcute checkout
#
# Telegram publishes the current layer as JSON in the same `{constructors,
# methods}` shape the generator consumes, so --fetch needs no conversion and no
# extra tooling. --from-mtcute reads mtcute's packed `{l, e}` layout instead
# (Scripts/convert-tl-schema.ts, which needs Deno) and takes the layer number
# from the schema itself — useful when pinning the exact layer another client
# speaks.
set -euo pipefail
cd "$(dirname "$0")/.."

SCHEMA_JSON="https://corefork.telegram.org/schema/json"
FETCH=0
MTCUTE=""
LAYER=""
while [ $# -gt 0 ]; do
  case "$1" in
    --fetch) FETCH=1; shift ;;
    --from-mtcute) MTCUTE="${2:?--from-mtcute needs a directory}"; shift 2 ;;
    --layer) LAYER="${2:?--layer needs a number}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -n "$MTCUTE" ]; then
  DENO="${DENO:-$(command -v deno || echo "$HOME/.deno/bin/deno")}"
  PACKED="$MTCUTE/packages/core/src/tl/api-schema.json"
  [ -f "$PACKED" ] || { echo "error: $PACKED not found" >&2; exit 1; }
  GOT="$("$DENO" eval "console.log(JSON.parse(await Deno.readTextFile('$PACKED')).l)")"
  if [ -n "$LAYER" ] && [ "$GOT" != "$LAYER" ]; then
    echo "error: $PACKED is layer $GOT but --layer says $LAYER." >&2
    exit 1
  fi
  "$DENO" run --allow-read --allow-write Scripts/convert-tl-schema.ts "$PACKED" Schemas/api.json
  echo "$GOT" > Schemas/latest-layer.txt
elif [ "$FETCH" = 1 ]; then
  # Telegram's published JSON carries no layer number, so pinning one is the
  # caller's statement about what was downloaded.
  [ -n "$LAYER" ] || { echo "error: --fetch needs --layer <n>" >&2; exit 1; }
  curl -fsSL "$SCHEMA_JSON" -o Schemas/api.json
  echo "$LAYER" > Schemas/latest-layer.txt
fi

LATEST_LAYER="$(cat Schemas/latest-layer.txt)"
echo "==> Generating layer $LATEST_LAYER from Schemas/api.json"

# The generator ships with swift-mtproto; build it from this package's own
# resolved dependencies so the emitted code matches the TLCoding runtime that
# will compile it.
swift build -j 4 --package-path .build/checkouts/swift-mtproto --product mtproto-gen-swift
TOOL="$(swift build --package-path .build/checkouts/swift-mtproto --product mtproto-gen-swift --show-bin-path)/mtproto-gen-swift"

SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

# --mode client emits the `TLClient` async facade over every method as well as
# the types. The root `TL` namespace is declared by MTProtoBaseSchema (the
# low-level MTProto schema), so this run extends it rather than redeclaring it.
# --exclude-namespace mtcute drops the vendor entries that checkout splices into
# its own schema; they are client-internal and must never reach generated code.
# --split-modules emits ~56 modules re-exported by a TelegramSchema umbrella, so
# one namespace's RPCs recompile on their own and the rest come from cache.
"$TOOL" --schema-url Schemas/api.json --output "$SCRATCH/out" \
  --mode client --visibility public \
  --root-namespace-module MTProtoBaseSchema \
  --exclude-namespace mtcute \
  --split-modules TelegramSchema

# Everything under the directory is generated, so it is replaced wholesale — no
# module survives its removal from the manifest.
rm -rf Sources/TelegramSchema
cp -r "$SCRATCH/out" Sources/TelegramSchema

# The layer is a property of the schema, so it is recorded with it rather than
# restated by hand somewhere a regeneration would not reach.
cat > Sources/TelegramSchema/Support/TelegramSchemaLayer.swift <<EOF
// Generated by Scripts/generate-schema.sh. DO NOT EDIT.

/// The API layer \`TelegramSchema\` was generated from.
public enum TelegramSchemaLayer {
  public static let current: Int32 = $LATEST_LAYER
}
EOF

# The module set follows the schema, so the manifest follows the module set.
DENO="${DENO:-$(command -v deno || echo "$HOME/.deno/bin/deno")}"
"$DENO" run --allow-read --allow-write Scripts/generate-package-targets.ts

echo "Regenerated layer $LATEST_LAYER into Sources/TelegramSchema."
