// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Fragment {

  /// TL: `fragment.getCollectibleInfo#be1e85ba collectible:InputCollectible = fragment.CollectibleInfo`
  @TLObject(id: 0xbe1e85ba, returning: TL.Fragment.CollectibleInfo.self)
  public struct GetCollectibleInfo: Equatable, Sendable {
    public var collectible: TL.InputCollectibleType
  }
}
