// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsPremium
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `premium.*` methods.
  public var premium: PremiumMethods {
    PremiumMethods(client: self)
  }
  /// The `premium.*` methods of a `TLClient`.
  public struct PremiumMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `premium.getBoostsList#60f67660 flags:# gifts:flags.0?true peer:InputPeer offset:string limit:int = premium.BoostsList`
    public func getBoostsList(gifts: Bool = false, peer: TL.InputPeerType, offset: String, limit: Int32) async throws -> TL.Premium.BoostsList {
      try await client.invoke(TL.Premium.GetBoostsList(gifts: gifts, peer: peer, offset: offset, limit: limit))
    }
    /// TL: `premium.getMyBoosts#0be77b4a = premium.MyBoosts`
    public func getMyBoosts() async throws -> TL.Premium.MyBoosts {
      try await client.invoke(TL.Premium.GetMyBoosts())
    }
    /// TL: `premium.applyBoost#6b7da746 flags:# slots:flags.0?Vector<int> peer:InputPeer = premium.MyBoosts`
    public func applyBoost(slots: [Int32]? = nil, peer: TL.InputPeerType) async throws -> TL.Premium.MyBoosts {
      try await client.invoke(TL.Premium.ApplyBoost(slots: slots, peer: peer))
    }
    /// TL: `premium.getBoostsStatus#042f1f61 peer:InputPeer = premium.BoostsStatus`
    public func getBoostsStatus(peer: TL.InputPeerType) async throws -> TL.Premium.BoostsStatus {
      try await client.invoke(TL.Premium.GetBoostsStatus(peer: peer))
    }
    /// TL: `premium.getUserBoosts#39854d1f peer:InputPeer user_id:InputUser = premium.BoostsList`
    public func getUserBoosts(peer: TL.InputPeerType, userId: TL.InputUserType) async throws -> TL.Premium.BoostsList {
      try await client.invoke(TL.Premium.GetUserBoosts(peer: peer, userId: userId))
    }
  }
}
