// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.updateUserEmojiStatus#ed9f30c5 user_id:InputUser emoji_status:EmojiStatus = Bool`
  @TLObject(id: 0xed9f30c5, returning: Bool.self)
  public struct UpdateUserEmojiStatus: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var emojiStatus: TL.EmojiStatusType
  }
}
