// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.getPopularAppBots#c2510192 offset:string limit:int = bots.PopularAppBots`
  @TLObject(id: 0xc2510192, returning: TL.Bots.PopularAppBots.self)
  public struct GetPopularAppBots: Equatable, Sendable {
    public var offset: String
    public var limit: Int32
  }
}
