// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.allowSendMessage#f132e3ef bot:InputUser = Updates`
  @TLObject(id: 0xf132e3ef, returning: TL.UpdatesType.self)
  public struct AllowSendMessage: Equatable, Sendable {
    public var bot: TL.InputUserType
  }
}
