// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.checkDownloadFileParams#50077589 bot:InputUser file_name:string url:string = Bool`
  @TLObject(id: 0x50077589, returning: Bool.self)
  public struct CheckDownloadFileParams: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var fileName: String
    public var url: String
  }
}
