// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.setCustomVerification#8b89dfbd flags:# enabled:flags.1?true bot:flags.0?InputUser peer:InputPeer custom_description:flags.2?string = Bool`
  @TLObject(id: 0x8b89dfbd, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetCustomVerification: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 1) public var enabled: Bool = false
    @TLConditional("flags", bit: 0) public var bot: TL.InputUserType? = nil
    public var peer: TL.InputPeerType
    @TLConditional("flags", bit: 2) public var customDescription: String? = nil
  }
}
