// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.getBotRecommendations#a1b70815 bot:InputUser = users.Users`
  @TLObject(id: 0xa1b70815, returning: TL.Users.UsersType.self)
  public struct GetBotRecommendations: Equatable, Sendable {
    public var bot: TL.InputUserType
  }
}
