// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.addPreviewMedia#17aeb75a bot:InputUser lang_code:string media:InputMedia = BotPreviewMedia`
  @TLObject(id: 0x17aeb75a, returning: TL.BotPreviewMedia.self)
  public struct AddPreviewMedia: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var langCode: String
    public var media: TL.InputMediaType
  }
}
