// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.reorderPreviewMedias#b627f3aa bot:InputUser lang_code:string order:Vector<InputMedia> = Bool`
  @TLObject(id: 0xb627f3aa, returning: Bool.self)
  public struct ReorderPreviewMedias: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var langCode: String
    public var order: [TL.InputMediaType]
  }
}
