// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.setBotGroupDefaultAdminRights#925ec9ea admin_rights:ChatAdminRights = Bool`
  @TLObject(id: 0x925ec9ea, returning: Bool.self)
  public struct SetBotGroupDefaultAdminRights: Equatable, Sendable {
    public var adminRights: TL.ChatAdminRights
  }
}
