// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.toggleUsername#053ca973 bot:InputUser username:string active:Bool = Bool`
  @TLObject(id: 0x053ca973, returning: Bool.self)
  public struct ToggleUsername: Equatable, Sendable {
    public var bot: TL.InputUserType
    public var username: String
    public var active: Bool
  }
}
