// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.getAccessSettings#213853a3 bot:InputUser = bots.AccessSettings`
  @TLObject(id: 0x213853a3, returning: TL.Bots.AccessSettings.self)
  public struct GetAccessSettings: Equatable, Sendable {
    public var bot: TL.InputUserType
  }
}
