// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.setBotMenuButton#4504d54f user_id:InputUser button:BotMenuButton = Bool`
  @TLObject(id: 0x4504d54f, returning: Bool.self)
  public struct SetBotMenuButton: Equatable, Sendable {
    public var userId: TL.InputUserType
    public var button: TL.BotMenuButtonType
  }
}
