// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Bots {

  /// TL: `bots.setBotInfo#10cf3123 flags:# bot:flags.2?InputUser lang_code:string name:flags.3?string about:flags.0?string description:flags.1?string = Bool`
  @TLObject(id: 0x10cf3123, returning: Bool.self)
  @TLFlagsEquatable
  public struct SetBotInfo: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 2) public var bot: TL.InputUserType? = nil
    public var langCode: String
    @TLConditional("flags", bit: 3) public var name: String? = nil
    @TLConditional("flags", bit: 0) public var about: String? = nil
    @TLConditional("flags", bit: 1) public var description: String? = nil
  }
}
