// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.

// The schema is generated as several modules so that a change to one of
// them does not rebuild the rest; this umbrella re-exports all of them,
// so `import TelegramSchema` presents the whole `TL.*` surface as one module.
@_exported import TLCoding
@_exported import MTProtoBaseSchema
@_exported import TelegramSchemaSupport
@_exported import TelegramSchemaTypes
@_exported import TelegramSchemaMethodsGlobal
@_exported import TelegramSchemaMethodsAccount
@_exported import TelegramSchemaMethodsAicompose
@_exported import TelegramSchemaMethodsAuth
@_exported import TelegramSchemaMethodsBots
@_exported import TelegramSchemaMethodsChannels
@_exported import TelegramSchemaMethodsChatlists
@_exported import TelegramSchemaMethodsCommunities
@_exported import TelegramSchemaMethodsContacts
@_exported import TelegramSchemaMethodsEphemeral
@_exported import TelegramSchemaMethodsFolders
@_exported import TelegramSchemaMethodsFragment
@_exported import TelegramSchemaMethodsHelp
@_exported import TelegramSchemaMethodsLangpack
@_exported import TelegramSchemaMethodsMessages
@_exported import TelegramSchemaMethodsPayments
@_exported import TelegramSchemaMethodsPhone
@_exported import TelegramSchemaMethodsPhotos
@_exported import TelegramSchemaMethodsPremium
@_exported import TelegramSchemaMethodsSmsjobs
@_exported import TelegramSchemaMethodsStats
@_exported import TelegramSchemaMethodsStickers
@_exported import TelegramSchemaMethodsStories
@_exported import TelegramSchemaMethodsUpdates
@_exported import TelegramSchemaMethodsUpload
@_exported import TelegramSchemaMethodsUsers
@_exported import TelegramSchemaClient
@_exported import TelegramSchemaClientGlobal
@_exported import TelegramSchemaClientAccount
@_exported import TelegramSchemaClientAicompose
@_exported import TelegramSchemaClientAuth
@_exported import TelegramSchemaClientBots
@_exported import TelegramSchemaClientChannels
@_exported import TelegramSchemaClientChatlists
@_exported import TelegramSchemaClientCommunities
@_exported import TelegramSchemaClientContacts
@_exported import TelegramSchemaClientEphemeral
@_exported import TelegramSchemaClientFolders
@_exported import TelegramSchemaClientFragment
@_exported import TelegramSchemaClientHelp
@_exported import TelegramSchemaClientLangpack
@_exported import TelegramSchemaClientMessages
@_exported import TelegramSchemaClientPayments
@_exported import TelegramSchemaClientPhone
@_exported import TelegramSchemaClientPhotos
@_exported import TelegramSchemaClientPremium
@_exported import TelegramSchemaClientSmsjobs
@_exported import TelegramSchemaClientStats
@_exported import TelegramSchemaClientStickers
@_exported import TelegramSchemaClientStories
@_exported import TelegramSchemaClientUpdates
@_exported import TelegramSchemaClientUpload
@_exported import TelegramSchemaClientUsers
