// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import TelegramSchemaClient
import TelegramSchemaMethodsChatlists
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TLClient {
  /// The `chatlists.*` methods.
  public var chatlists: ChatlistsMethods {
    ChatlistsMethods(client: self)
  }
  /// The `chatlists.*` methods of a `TLClient`.
  public struct ChatlistsMethods: Sendable {
    public let client: TLClient
    public init(client: TLClient) {
      self.client = client
    }
    /// TL: `chatlists.exportChatlistInvite#8472478e chatlist:InputChatlist title:string peers:Vector<InputPeer> = chatlists.ExportedChatlistInvite`
    public func exportChatlistInvite(chatlist: TL.InputChatlistDialogFilter, title: String, peers: [TL.InputPeerType]) async throws -> TL.Chatlists.ExportedChatlistInvite {
      try await client.invoke(TL.Chatlists.ExportChatlistInvite(chatlist: chatlist, title: title, peers: peers))
    }
    /// TL: `chatlists.deleteExportedInvite#719c5c5e chatlist:InputChatlist slug:string = Bool`
    public func deleteExportedInvite(chatlist: TL.InputChatlistDialogFilter, slug: String) async throws -> Bool {
      try await client.invoke(TL.Chatlists.DeleteExportedInvite(chatlist: chatlist, slug: slug))
    }
    /// TL: `chatlists.editExportedInvite#653db63d flags:# chatlist:InputChatlist slug:string title:flags.1?string peers:flags.2?Vector<InputPeer> = ExportedChatlistInvite`
    public func editExportedInvite(chatlist: TL.InputChatlistDialogFilter, slug: String, title: String? = nil, peers: [TL.InputPeerType]? = nil) async throws -> TL.ExportedChatlistInvite {
      try await client.invoke(TL.Chatlists.EditExportedInvite(chatlist: chatlist, slug: slug, title: title, peers: peers))
    }
    /// TL: `chatlists.getExportedInvites#ce03da83 chatlist:InputChatlist = chatlists.ExportedInvites`
    public func getExportedInvites(chatlist: TL.InputChatlistDialogFilter) async throws -> TL.Chatlists.ExportedInvites {
      try await client.invoke(TL.Chatlists.GetExportedInvites(chatlist: chatlist))
    }
    /// TL: `chatlists.checkChatlistInvite#41c10fff slug:string = chatlists.ChatlistInvite`
    public func checkChatlistInvite(slug: String) async throws -> TL.Chatlists.ChatlistInviteType {
      try await client.invoke(TL.Chatlists.CheckChatlistInvite(slug: slug))
    }
    /// TL: `chatlists.joinChatlistInvite#a6b1e39a slug:string peers:Vector<InputPeer> = Updates`
    public func joinChatlistInvite(slug: String, peers: [TL.InputPeerType]) async throws -> TL.UpdatesType {
      try await client.invoke(TL.Chatlists.JoinChatlistInvite(slug: slug, peers: peers))
    }
    /// TL: `chatlists.getChatlistUpdates#89419521 chatlist:InputChatlist = chatlists.ChatlistUpdates`
    public func getChatlistUpdates(chatlist: TL.InputChatlistDialogFilter) async throws -> TL.Chatlists.ChatlistUpdates {
      try await client.invoke(TL.Chatlists.GetChatlistUpdates(chatlist: chatlist))
    }
    /// TL: `chatlists.joinChatlistUpdates#e089f8f5 chatlist:InputChatlist peers:Vector<InputPeer> = Updates`
    public func joinChatlistUpdates(chatlist: TL.InputChatlistDialogFilter, peers: [TL.InputPeerType]) async throws -> TL.UpdatesType {
      try await client.invoke(TL.Chatlists.JoinChatlistUpdates(chatlist: chatlist, peers: peers))
    }
    /// TL: `chatlists.hideChatlistUpdates#66e486fb chatlist:InputChatlist = Bool`
    public func hideChatlistUpdates(chatlist: TL.InputChatlistDialogFilter) async throws -> Bool {
      try await client.invoke(TL.Chatlists.HideChatlistUpdates(chatlist: chatlist))
    }
    /// TL: `chatlists.getLeaveChatlistSuggestions#fdbcd714 chatlist:InputChatlist = Vector<Peer>`
    public func getLeaveChatlistSuggestions(chatlist: TL.InputChatlistDialogFilter) async throws -> [TL.PeerType] {
      try await client.invoke(TL.Chatlists.GetLeaveChatlistSuggestions(chatlist: chatlist))
    }
    /// TL: `chatlists.leaveChatlist#74fae13a chatlist:InputChatlist peers:Vector<InputPeer> = Updates`
    public func leaveChatlist(chatlist: TL.InputChatlistDialogFilter, peers: [TL.InputPeerType]) async throws -> TL.UpdatesType {
      try await client.invoke(TL.Chatlists.LeaveChatlist(chatlist: chatlist, peers: peers))
    }
  }
}
