// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Photos {

  /// TL: `photos.uploadContactProfilePhoto#e14c4a71 flags:# suggest:flags.3?true save:flags.4?true user_id:InputUser file:flags.0?InputFile video:flags.1?InputFile video_start_ts:flags.2?double video_emoji_markup:flags.5?VideoSize = photos.Photo`
  @TLObject(id: 0xe14c4a71, returning: TL.Photos.Photo.self)
  @TLFlagsEquatable
  public struct UploadContactProfilePhoto: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 3) public var suggest: Bool = false
    @TLConditional("flags", bit: 4) public var save: Bool = false
    public var userId: TL.InputUserType
    @TLConditional("flags", bit: 0) public var file: TL.InputFileType? = nil
    @TLConditional("flags", bit: 1) public var video: TL.InputFileType? = nil
    @TLConditional("flags", bit: 2) public var videoStartTs: Double? = nil
    @TLConditional("flags", bit: 5) public var videoEmojiMarkup: TL.VideoSizeType? = nil
  }
}
