// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Premium {

  /// TL: `premium.getBoostsList#60f67660 flags:# gifts:flags.0?true peer:InputPeer offset:string limit:int = premium.BoostsList`
  @TLObject(id: 0x60f67660, returning: TL.Premium.BoostsList.self)
  @TLFlagsEquatable
  public struct GetBoostsList: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var gifts: Bool = false
    public var peer: TL.InputPeerType
    public var offset: String
    public var limit: Int32
  }
}
