// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Premium {

  /// TL: `premium.applyBoost#6b7da746 flags:# slots:flags.0?Vector<int> peer:InputPeer = premium.MyBoosts`
  @TLObject(id: 0x6b7da746, returning: TL.Premium.MyBoosts.self)
  @TLFlagsEquatable
  public struct ApplyBoost: Equatable, Sendable {
    @TLFlags public var flags: UInt32 = 0
    @TLConditional("flags", bit: 0) public var slots: [Int32]? = nil
    public var peer: TL.InputPeerType
  }
}
