// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
import TelegramSchemaSupport
import TelegramSchemaTypes
import MTProtoBaseSchema
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL.Premium {

  /// TL: `premium.getMyBoosts#0be77b4a = premium.MyBoosts`
  @TLObject(id: 0x0be77b4a, returning: TL.Premium.MyBoosts.self)
  public struct GetMyBoosts: Equatable, Sendable {
  }
}
